### ISSUE TITLE
Any reason why ransack 1.8.9 pins rails at 5.1.1?

### ISSUE THREAD

**Issue by bdezonia** [activerecord-hackery/ransack#1000]
We are using ransack 1.8.8 with rails 5.1.6. We'd like to update to 1.8.9 if it has any relevant bug fixes. But 1.8.9 has rails gem dependency =5.1.1. Any reason why the dependency isn't ~>5.1.1 (or even < 5.2)? We are in a position, due to various gem dependencies in our project, that we can't yet update to rails 5.2.

**Comment by gregmolnar** [comment]
Ransack relies on Active Record internals, so we tend to lock on a minor release since even those can change internals and break compatibility. Having said that, I just release 1.8.10 which depends on Active Record < 5.2, it is unlikely to break anyways.
