### ISSUE TITLE
How do I filter results to user-related only?

### ISSUE THREAD

**Issue by alexvelickiy** [activerecord-hackery/ransack#1010]
Hi,

I'd like to use ransack search in an dashboard panel I'm developing.
How do search on user-related objects (those that have `user_id `equal to current user id)?

**Comment by connorgallopo** [comment]
Hey Alex, are you trying to search one or many user related objects?

**Comment by alexvelickiy** [comment]
Hi, now I'm trying to search for one object (i.e. Cars that belong to this particular user). But possibly I'll later try to search on many user related objects.

**Comment by mojobiri** [comment]
This should do the trick.
```ruby
Car.where(user_id: [1,2,3]).ransack(params[:q]).result
# or
current_user.cars.ransack(params[:q]).result
```

**Comment by alexvelickiy** [comment]
Oh, of course. Thank you for response.

**Comment by seanfcarroll** [comment]
Closed
