### ISSUE TITLE
Need a query that checks has_many relationship multiple times 

### ISSUE THREAD

**Issue by bdezonia** [activerecord-hackery/ransack#1011]
I am using the advanced mode UI of Ransack (1.8.10) with the following example in Rails 5.1.6 and using MySql 5.7. (We can't yet update to a newer version of Ransack due to some gem interdependencies.)

# id : integer

class Contact
  has_many :mystudymembs
end

# id : integer
# contact_id : integer
# name : string

class Mystudymemb
  belongs_to :contact
end

I am trying to do a nested query that in essence says give me back people who have two memberships (people who have both membership 'A' and membership 'B').

Basically you can define a query that looks correct visually

  ALL
    ALL
      Membership name = 'A'
    ALL
      Membership name = 'B'

The generated SQL however is something like this:

SELECT DISTINCT `contacts`.* FROM `contacts` LEFT OUTER JOIN `mystudymembs` ON `mystudymembs`.`contact_id` = `contacts`.`id` WHERE (`mystudymembs`.`name` = 'A' AND `mystudymembs`.`name` = 'B') ORDER BY `contacts`.`id` ASC

And the (name = 'A' and name = 'B') condition is logically impossible. No records are returned.

How, using the advanced mode user interface, can one define the necessary query?

FYI here is the param string as passed to the controller:

"q"=>{"g"=>{"0"=>{"m"=>"and", "g"=>{"1552670787588"=>{"m"=>"and", "c"=>{"1552670789762"=>{"a"=>{"0"=>{"name"=>"mystudymembs_name"}}, "p"=>"eq", "v"=>{"0"=>{"value"=>"A"}}}}}, "1552670797553"=>{"m"=>"and", "c"=>{"1552670799877"=>{"a"=>{"0"=>{"name"=>"mystudymembs_name"}}, "p"=>"eq", "v"=>{"0"=>{"value"=>"B"}}}}}}}}}

This issue may be related to issue #772?

**Comment by letiesperon** [comment]
This issue has been reported in many different places and it is quite important. Will it be solved?

**Comment by seanfcarroll** [comment]
Submitting a PR with some tests would be really helpful here. https://github.com/activerecord-hackery/ransack/issues/1175

**Comment by ylixir** [comment]
Sorry I don't have a PR for this, but you can reproduce it with the ransack demo app:
https://github.com/activerecord-hackery/ransack/issues/772#issuecomment-315634861

you should get back two users, since there are two users that have posts that start with S and post that start with R. But actually you get back 0 users since it tries to find a user with one post that starts with both S and R at the same time instead of a user that has one post that starts with S and a different post that starts with R.

 
curl command to reproduce:
```
curl -X POST https://ransack-demo.herokuapp.com/users/advanced_search \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -d 'q%5Bg%5D%5B0%5D%5Bm%5D=and&q%5Bg%5D%5B0%5D%5Bc%5D%5B0%5D%5Ba%5D%5B0%5D%5Bname%5D=posts_title&q%5Bg%5D%5B0%5D%5Bc%5D%5B0%5D%5Bp%5D=start&q%5Bg%5D%5B0%5D%5Bc%5D%5B0%5D%5Bv%5D%5B0%5D%5Bvalue%5D=S&q%5Bg%5D%5B0%5D%5Bc%5D%5B1%5D%5Ba%5D%5B0%5D%5Bname%5D=posts_title&q%5Bg%5D%5B0%5D%5Bc%5D%5B1%5D%5Bp%5D=start&q%5Bg%5D%5B0%5D%5Bc%5D%5B1%5D%5Bv%5D%5B0%5D%5Bvalue%5D=R&commit=Search'
```

**Comment by deivid-rodriguez** [comment]
This should do the trick using active record

```
User.joins("LEFT JOIN posts p1 on p1.user_id = users.id").joins("LEFT JOIN posts p2 on p2.user_id = users.id").where("p1.title ilike 'O%' and p2.title ilike 'S%'")
```

But not fully sure how one implements that using Ransack, I will investigate.

**Comment by deivid-rodriguez** [comment]
I added a solution to this to the demo application. See https://ransack-demo-allow-sear-7gvqaz.herokuapp.com.
