### ISSUE TITLE
Azerbaijani translation yml file issue

### ISSUE THREAD

**Issue by bigonese** [activerecord-hackery/ransack#1017]
Azerbaijani translation has the translations nested under the `tr:` item instead of `az:`, which I believe is overwriting the Turkish translation.

I believe this line needs correction: https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/locale/az.yml#L1

Found the issue when deploying the same code base to multiple servers and the complied JS was different between the two. It appears one server used the original `tr` while the other used the replaced `az`-version.

**Comment by seanfcarroll** [comment]
Addressed by https://github.com/activerecord-hackery/ransack/pull/1022

**Comment by seanfcarroll** [comment]
Closed
