### ISSUE TITLE
How to access polyamorous by itself

### ISSUE THREAD

**Issue by obromios** [activerecord-hackery/ransack#1038]
The code for ransack includes a gemspec for[ polyamorous](https://github.com/activerecord-hackery/ransack/blob/master/polyamorous/polyamorous.gemspec).  Is it is possible to access ```polyamorous``` code without loading all of ```ransack``` which would be useful if someone just wants the polyamorous functionality. It this possible?

I have already asked [this question](https://stackoverflow.com/q/56782261/1299362) on SO without receiving an answer.

**Comment by obromios** [comment]
I was able to do this by putting the following my Gemfile:
```
git 'git@github.com:activerecord-hackery/ransack.git' do
  gem 'polyamorous'
end

```
but is it also possible to load it from rubygems?

**Comment by obromios** [comment]
My guess is that it is not possible to load ransack/polyamorous from rubygems at present.

I am thinking of cloning ransack, and then create a new gem called something like ```ransack_polyamorous``` and push it to rubygems. I am happy to work with the ransack team, so making it an official release, and also doing the work of updating it each time there is a version bump.  Are you interested in this?

**Comment by seanfcarroll** [comment]
Hi @obromios thanks for your message. In fact Polyamorous was previously an independent gem, but it was absorbed into Ransack in order to simplify management but also as it was thought it would not be used alone. Out of interest, how do you plan to use it?

The original gem is [here](https://github.com/activerecord-hackery/polyamorous) but it is no longer maintained. 

Hope that helps, Sean

**Comment by obromios** [comment]
I used the original ```polyamorous``` gem to make a polymorphous association work i.e
```
class User < ApplicationRecord
  has_and_belongs_to_many :eclubs
end

```
At some point, in order to accomodate a new Rails version, I had to use ```ransack```  because the original ```polyamorous``` no longer worked. I do not use any of the ransack functionality, apart from what is derived from the internal polyamorous gem.  According to ```derailed```, ```ransack``` takes up about 6MiB, but the polyamorous part is less than 1MiB, so for a memory constained application it is temping to just use the internal gem.

In app, if I remove the ```ransack``` gem, then I see errors like
```
     Failure/Error: eclubs.first
      
      ArgumentError:
        wrong number of arguments (given 3, expected 2)

```
whereas in development if I omit the ```ransack``` gem and use the internal ```polyamorous``` gem, as described in my comment above, then all my tests pass.

However this does not work on Heroku.  It would not surprise me if quite a few of people who used the original ```polyamorous``` gem also upgraded to ```ransack``` without using  the ```ransack``` functionality, so would benefit from an independent release of the internal ```polyamorous 2.1.1``` gem.  Or is there some simpler way of solving this problem?

**Comment by obromios** [comment]
I have done a bit more investigation on this.  

I created a new gem from your polyamorous codebase, and was able to deploy my app to heroku without using ransack.  I gave the gem a nondescript name with a uninformative description, so it is intended to be  for my own use only.  This solves my immediate problem.
 
Looking at polyamorous on rubygems.org there have been over one million downloads of the most recent version, which is two years old. This indicates there could be many people who could benefit from an up-to-date version of polyamorous.

I can understand why you may not want to create and maintain a standalone up-to-date polyamorous gem from your  codebase.  So, if you do not want to create an up-to-date polyamorous gem, do you have any objections if I create a shadow repository of ransack, and use it to create a gem with a name like ```ransack_polyamorous``` or ```polyamorous_continued```, and then continue to update it each time there is a version bump in the ransack gem? 

Another possibility is for someone to update the exisiting polyamorous github respository with the ransack/polyamorous code and start to push out fresh versions of the existing polyamorous gem.

**Comment by gregmolnar** [comment]
you can add ransack to the gemfile with `require: false` and manually require just polyamorous.

**Comment by gregmolnar** [comment]
> Looking at polyamorous on rubygems.org there have been over one million downloads of the most recent version, which is two years old. This indicates there could be many people who could benefit from an up-to-date version of polyamorous.
Most of those downloads are related to ransack, but actually we are planning to separately release the 2 gems, just maintain them from a single repository.

**Comment by obromios** [comment]
Thank you @gregmolnar. I will use the ```gem ransack require: false```  option for the time being.

Look forwarding to seeing the ```polyamorous``` gem revived.

**Comment by gregmolnar** [comment]
polyamorous is released as a separate gem now.
