### ISSUE TITLE
Difficulty running tests on repository

### ISSUE THREAD

**Issue by obromios** [activerecord-hackery/ransack#1042]
According to the ```Contributing to Ransack``` guide, in order to run the tests using postgres, I should do
```
bundle install
DB=pg bundle exec rake spec
```
but when I do that, I get an exception
```
Failure/Error:
  establish_connection(
    adapter: 'sqlite3',
    database: ':memory:'
  )

LoadError:
  Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-1.3.13. Make sure all dependencies are added to Gemfile.
```
Similarly for mysql.  Using git bisect, I found the issue starts with this [commit](https://github.com/activerecord-hackery/ransack/commit/131e52aec0e0acd910b9480683fd685ae52264c5).

Looking at your travis file, I found a work around is to do
```
RAILS=v5.2.3 DB=pg bundle install
DB=pg bundle exec rake spec
```

**Comment by gregmolnar** [comment]
The problem is, now we default to Rails 6 when running the specs, but our Gemfile is defaults to the older version of the sqlite gem, which is incompatible with Rails 6.  
Do you want to give a try fixing that in the Gemspec?

**Comment by obromios** [comment]
OK, hope to find time this weekend or the one after.

Chris

**Comment by gregmolnar** [comment]
This one should be resolved now.
