### ISSUE TITLE
Docs don't make clear how to use the functionality Skip Sanitize Args

### ISSUE THREAD

**Issue by jeduardo824** [activerecord-hackery/ransack#1043]
After facing an issue caused by Ransack interpreting `1`/`'t'` as `true` and some unsuccessful research, I found about the sanitize args and the recommended way to skip them. The documentation never mentions that `ransackable_scopes_sanitize_args` must be a class method and the example shown defines an instance method.

I think that's worth a documentation update, making more clear how to use the functionality.

Link to file: https://github.com/activerecord-hackery/ransack/blame/master/README.md#L758

![Screen Shot 2019-07-18 at 09 49 31](https://user-images.githubusercontent.com/27960597/61458799-b9ff5e80-a941-11e9-8c83-b12e9a243b4b.png)

**Comment by seanfcarroll** [comment]
Would you be interested in making a small PR to document this @jeduardo824 ?

**Comment by seanfcarroll** [comment]
Bump @jeduardo824

**Comment by jeduardo824** [comment]
Sorry! Did not catch your first comment! Yeah, I can do the doc update! Will try to do it during the weekend.

**Comment by seanfcarroll** [comment]
Hi @jeduardo824 no need to be sorry!! Thank you for your reply and I'm looking forward to seeing the doc update!

Thank you for contributing to Ransack!

**Comment by jeduardo824** [comment]
Hey @seanfcarroll, it looks like somebody already did the job! Closing!

https://github.com/activerecord-hackery/ransack/commit/e055c0d4e6f47a7ff2b6839f38f7dc40115c3387

**Comment by seanfcarroll** [comment]
Really? Awesome! @jeduardo824
