### ISSUE TITLE
The search is based on item from database

### ISSUE THREAD

**Issue by raphox** [activerecord-hackery/ransack#1063]
https://github.com/activerecord-hackery/ransack/blob/85fc41b329ca2b316bab32c464dd8920fae74998/lib/ransack/nodes/bindable.rb#L21

I'm using ransack-mongoid. When I try filter by reference (like `role_id_eq`) the value of `parent` is a constant refering model `Role`. So the code try check if exists a item on collection `roles` on database. Why?

Maybe the correct check is `parent.to_s.present?`.

**Comment by seanfcarroll** [comment]
Ransack-mongoid is [looking for a maintainer](https://github.com/activerecord-hackery/ransack-mongoid#maintainer-wanted). The MongoDB code is no longer in this repo.

Thanks for the issue, but it will be closed for these reasons.
