### ISSUE TITLE
Ransack filter "*_eq" does not work with large numbers

### ISSUE THREAD

**Issue by pedrofurtado** [activerecord-hackery/ransack#1064]
@gregmolnar 

The latest version of ransack (2.3.0) with the latest version of Rails (6.0.0) this code below (with ransack filters `*_eq`) does not work:

```ruby
# This code works.
Person.where(id: 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111).to_sql
#=> "SELECT \"people\".* FROM \"people\" WHERE 1=0"

# This code does not work.
Person.ransack(id_eq: 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111).result.to_sql
#=> ActiveModel::RangeError: 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 is out of range for ActiveModel::Type::Integer with limit 8 bytes from /usr/local/lib/ruby/gems/2.6.0/gems/activemodel-6.0.0/lib/active_model/type/integer.rb:40:in `ensure_in_range'
```

The first code snippet, in Rails 6, works because of this PR: https://github.com/rails/rails/pull/30000

Thanks! :+1:

**Comment by pedrofurtado** [comment]
@marciojg @willradi

**Comment by pedrofurtado** [comment]
@gregmolnar 👍

**Comment by seanfcarroll** [comment]
That's a pretty big number @pedrofurtado !

**Comment by pedrofurtado** [comment]
@seanfcarroll Could you help us? Because I know the bug, but not the solution :laughing: :see_no_evil: 
Once we have a PR created, I could help testing in our application :+1:

**Comment by seanfcarroll** [comment]
It would be really helpful if you could point me to a basic Rails app where the problem exists.

Why is this needed urgently? Are you working with such large numbers?

**Comment by seanfcarroll** [comment]
@pedrofurtado can you explain why such a large number might be needed? This issue will be closed otherwise.

**Comment by pedrofurtado** [comment]
@seanfcarroll In the application, the user can search for records by id. Then, it is possible user provides a long number 👍 can you reopen the issue?

**Comment by pedrofurtado** [comment]
@seanfcarroll is there any workaround?

**Comment by pedrofurtado** [comment]
For anyone looking for a workaround, there is a monkey patch:

```ruby
##
# Monkey-patch.
#
# URLs for reference:
# https://github.com/activerecord-hackery/ransack/issues/1064
# https://github.com/kamipo/activerecord-suppress_range_error
# https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/integer.rb#L47-L52
module ActiveRecord
  module SuppressRangeError
    private

    def ensure_in_range(value)
      value
    end
  end

  module Type
    class Integer
      prepend SuppressRangeError
    end
  end
end
```

**Comment by pedrofurtado** [comment]
I also open a PR in https://github.com/kamipo/activerecord-suppress_range_error gem, that could provide this workaround to used in Rails 6 + Ransack 🤝
