### ISSUE TITLE
problem with has one association

### ISSUE THREAD

**Issue by alebacca89** [activerecord-hackery/ransack#1069]
Why has_one association not works with ransack 1.8.10?
I've inserted my association in whitlist but search with field of has_one not works.

Example:

s = Oreder.ransack(billing_info_vat_number_eq: "ASASAS")
results = s.result

results contains all orders

Why?

**Comment by seanfcarroll** [comment]
Could you please submit a PR with a failing test in it @alebacca89 ?

**Comment by seanfcarroll** [comment]
Closed due to inactivity.
