### ISSUE TITLE
Can't use scopes on nested relations

### ISSUE THREAD

**Issue by llekn** [activerecord-hackery/ransack#1087]
Having the following models

```ruby
class Post
  ...
  def self.my_scope(args)
    where(foo: args)
  end
end

class User
  ...
  has_many :posts  
end
```

It is possible to use ransack with `my_scope` directly on the `Post` model:
```ruby
Post.ransack(my_scope: 'foo').result
#=> works
```

But it doesn't work if I try to use the same scope from the `User` model:
```ruby
User.ransack(posts_my_scope: 'foo')
#=> ArgumentError: Invalid search term posts_my_scope
```

Are scopes limited only to be usable with the same model? Or am I missing something?

**Comment by urkle** [comment]
Right now the README states this is not supported right now.
```Scopes are a recent addition to Ransack and currently have a few caveats: First, a scope involving child associations needs to be defined in the parent table model, not in the child model. 
```

This would be nice to get supported though.

**Comment by seanfcarroll** [comment]
Closing as unsupported, feel free to reopen and submit a PR to enhance Ransack.

**Comment by clousky2020** [comment]
Is this feature supported now? I also encountered the same problem.
