### ISSUE TITLE
Dynamically set distinct option

### ISSUE THREAD

**Issue by chrismhilton** [activerecord-hackery/ransack#109]
I would like to set the result :distinct option dynamically depending on whether or not my search requires a join.

Previously when using MetaSearch I was able to determine whether or not a join was required using the following:

```
@search.join_dependency.join_associations.empty?
```

Could you please advise how I could implement an equivalent check using Ransack.

**Comment by aripollak** [comment]
It looks like `distinct` is automatically used when necessary now, at least under Rails 4.1. Maybe the explicit `distinct` option is no longer necessary for most cases?
