### ISSUE TITLE
MongoidAdapter missing : No support for mongo since 2.0.0

### ISSUE THREAD

**Issue by fmonvoisin** [activerecord-hackery/ransack#1090]
Hi,

Is it possible to add the adapter for mongoid which is missing since 2.0.0 ?

Thanks

**Comment by seanfcarroll** [comment]
Thanks for asking @fmonvoisin, the Mongoid adapter did not have much demand, and it was [moved here](https://github.com/activerecord-hackery/ransack-mongoid). This repo is looking for a maintainer if you are interested.

**Comment by fmonvoisin** [comment]
Thank you for your reply. I'll check the repo. If I manage to understand it, I might try to help you maintain it.
Best Regards

**Comment by seanfcarroll** [comment]
@fmonvoisin if you are interested in working on this we can work together to bring it back to life ... as a plug-in to Ransack.
