### ISSUE TITLE
Update supported versions in Travis

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#1092]
Update Travis configuration with support under `sqlite3`, `postgres` and `mysql` for :

- 6-0-stable
- 5-2-stable
- 6-0-2
- 6-0-1
- 6-0-0
- 5-2-4
- 5-2-3

Remove [allowed to fail for 6-0-0 stable](https://github.com/activerecord-hackery/ransack/blob/master/.travis.yml#L27-L30) from CI configuration.

**Comment by seanfcarroll** [comment]
https://www.upwork.com/ab/applicants/1215911323418488832/job-details

**Comment by gregmolnar** [comment]
> Remove allowed to fail for 6-0-0 stable from CI configuration.  

The reason we have that as an allowed failure is to see on CI when we break against that branch, but that should block the pipeline, since we are not supporting unreleased versions of Rails, due to relying on internal APIs which might change at any point.

**Comment by seanfcarroll** [comment]
https://github.com/activerecord-hackery/ransack/pull/1114
