### ISSUE TITLE
Please publish polyamorous 2.3.2 gem to RubyGems

### ISSUE THREAD

**Issue by sunpoet** [activerecord-hackery/ransack#1096]
Though 0356739cd70d0db7ecdfb4f920ab1ed64ba01fc3 fixes the version issue between ransack and polyamorous, there is no polyamorous 2.3.2 gem on [RG](https://rubygems.org/gems/polyamorous).

**Comment by seanfcarroll** [comment]
Thank you @sunpoet, but Polyamorous is no longer in it's own repo. It is embedded in Ransack. https://github.com/activerecord-hackery/ransack/tree/master/polyamorous

Work is needed to properly integrate this code.

**Comment by seanfcarroll** [comment]
If this answer clears it up for you, please close this issue.

**Comment by tvdeyen** [comment]
The gem needs to be published on rubygems. See #1098
