### ISSUE TITLE
Convert Polyamorous into a module

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#1099]
Previously Polyamorous was a [separate gem](https://github.com/activerecord-hackery/polyamorous). It has been moved into the Ransack repo, which is a great step forward. 

However, it is still a gem **_inside_** the Ransack repo. What needs to be done is to convert this code purely into a module. A later refactoring can more closely merge the code, but for now the work needed is:

- Remove the Polyamorous gem-specific code
   - https://github.com/activerecord-hackery/ransack/blob/master/polyamorous/polyamorous.gemspec
  - https://github.com/activerecord-hackery/ransack/blob/master/polyamorous/lib/polyamorous/version.rb
- Add any dependencies needed into the Ransack gemspec
- Move everything under the main `/lib/polyamorous` folder
- Remove the Polyamorous dependency from Ransack
  - https://github.com/activerecord-hackery/ransack/blob/master/ransack.gemspec#L20
- Add the [Polyamorous tests](https://github.com/activerecord-hackery/polyamorous/tree/master/spec) into the Ransack repo and get them to pass

**Comment by seanfcarroll** [comment]
I'm thinking the Polyamorous gem should be removed from Rubygems also. Any thoughts on this?

**Comment by tvdeyen** [comment]
> I'm thinking the Polyamorous gem should be removed from Rubygems also. Any thoughts on this?

I think we should release polyamorous 2.3.1 and 2.3.2 so that ransack 2.3.1 and 2.3.2 can actually be installed via bundler (#1098)

Then release a ransack 3.0 with included polyamorous (once this issue has been resolved) and leave the old polyamorous gems on rubygems for old projects and do not release a 3.0

That way we do not break peoples CIs and local development

**Comment by tvdeyen** [comment]
And probably include some deprecation warnings in the 2.3.2 releases of polyamorous telling the people about the removal and inclusion in ransack 3.0

**Comment by tvdeyen** [comment]
@seanfcarroll I am a little confused about this issue, actually. In #1002 you decided to make polyamorous a seperate gem. There was some discussion around to use polyamorous with other gems as well (https://github.com/rzane/baby_squeel/issues/97).

Is this issue about reverting #1002? I am willing to work on this, but I am not sure what is the goal here? Maybe @gregmolnar can shed some light?

**Comment by gregmolnar** [comment]
@tvdeyen see my reply here: https://github.com/activerecord-hackery/ransack/issues/1098#issuecomment-573617666

**Comment by tvdeyen** [comment]
@gregmolnar @seanfcarroll can this be closed now?

**Comment by seanfcarroll** [comment]
@tvdeyen this is part of the work the Upwork contracter will be doing. https://www.upwork.com/ab/applicants/1215911323418488832/job-details

**Comment by gregmolnar** [comment]
Do we need a contractor for this? @tvdeyen offered to work on it, he just need guidance about what's needed to be done. I could also sort this, as it shouldn't be a big deal.

**Comment by seanfcarroll** [comment]
@gregmolnar It is preferable if the community handles these issues, but Ransack has been broken for a long time.

https://github.com/activerecord-hackery/ransack/issues/1081

The contractor has already accepted the job, so I don't know what the best approach is here.

How about we let the contractor do the work and community members can deal with some of the many other Ransack issues?

**Comment by seanfcarroll** [comment]
The other option is to try and cancel the Upwork contract, but I don't know what is involved there. If someone submits a PR to at least fix https://github.com/activerecord-hackery/ransack/issues/1081 that would resolve the immediate problems...

**Comment by gregmolnar** [comment]
If there is already a contractor, than it wouldn't make sense to cancel the contract.
AS for #1081, we should make CI pass for 6.0.1 and 6.0.2. That would probably also fix it for 6-0-stable, but since we rely on internal APIs, spending time fixing issue on an unreleased version might end up wasted work if things are changing again before a release.
