### ISSUE TITLE
Packaged gem includes polyamorous code twice

### ISSUE THREAD

**Issue by tvdeyen** [activerecord-hackery/ransack#1102]
The `ransack` gem package includes the code of the `polyamorous` code twice because of this line 

https://github.com/activerecord-hackery/ransack/blob/master/ransack.gemspec#L22

Since polyamorous is shipped as its own gem we now have the polyamorous code twice.

We should exclude the files from the ransack gem package.

**Comment by seanfcarroll** [comment]
Thanks for the issue @tvdeyen 

The decision was made previously to absorb the undocumented polyamorous code into Ransack, and the repo was later archived. The intention behind this was to simplify ongoing development of Ransack, which is becoming quite critical.

I think Ransack would benefit from being completely merged with Polyamorous.

Unfortunately, only a couple of people have stepped up with PRs and there are lots of open issues. I have put forward a [job on upwork](https://github.com/activerecord-hackery/ransack/issues/1097) to resolve these three issues:

- https://github.com/activerecord-hackery/ransack/issues/1099
- https://github.com/activerecord-hackery/ransack/issues/1092
- https://github.com/activerecord-hackery/ransack/issues/1081

Part of the work is to bring the specs from Polyamorous into Ransack. It seems the main maintenance work on Ransack is dealing with changes to ActiveRecord in each version of Rails, which is housed under Polyamorous.

PRs for any Ransack issues are highly welcome. I'd really like to get Ransack down to zero issues, but for this to happen the community needs to get more engaged. We all benefit from open source, but for it to survive it needs community contributions.

I hope that makes sense and is agreeable? Is there a reason to maintain Polyamorous as a separate gem ?

**Comment by tvdeyen** [comment]
@seanfcarroll opened #1104 that fixes this issue.
