### ISSUE TITLE
How can I use lockbox gem with ransack gem?

### ISSUE THREAD

**Issue by shubhamsharma4587** [activerecord-hackery/ransack#1106]
Using Lockbox gem I encrypted my email column in the database (removed email column and added email_ciphertext, email_bidx column) but now I'm facing error when trying to use <%= f.search_field :email_cont %>. Please suggest me how can I handle it.

Error:

undefined method `email_cont' for Ransack::Search<class: User, base: Grouping <combinator: and>>:Ransack::Search

**Comment by seanfcarroll** [comment]
I don't know, but it's a good question. According to the [documentation](https://github.com/ankane/lockbox#active-record) the encrypted fields should just translate to regular field names.

```
User.create!(email: "hi@example.org")
```

Did you make any progress on this @shubhamsharma4587 ?

**Comment by seanfcarroll** [comment]
Closed due to inactivity.

**Comment by dminchev** [comment]
@shubhamsharma4587 @seanfcarroll you can check my solution here https://github.com/ankane/lockbox/issues/29#issuecomment-909884234
