### ISSUE TITLE
Ransack Sorting on a decorated object

### ISSUE THREAD

**Issue by RobbieKatzZappi** [activerecord-hackery/ransack#1133]
Hey all,

I'm using ransack to enable all the fun stuff (searching, pagination, filtering) on a particular DB model of mine. The problem I'm having is that after querying the DB with ransack, I then decorate the model with extra fields, which are not sortable using ransack. I'm wondering if there is a possible way to sort the model by these decorated fields using ransack, or if there's best practice for sorting by something that's not supported by this gem? 

thanks

**Comment by seanfcarroll** [comment]
I think we would need an example, but it sounds like an edge case.

**Comment by ncliffor** [comment]
@RobbieKatzZappi would something like this solve your problem?
```ruby
module TableSortHelper
  def sortable(search, column, **options)
    title = options.fetch(:title, nil)
    title ||= search.klass.human_attribute_name(column)

    if column.to_s == search.sort_column
      if search.sort_direction == 'asc'
        direction = 'desc'
        title = (title + '&#9650;').html_safe
      else
        direction = 'asc'
        title = (title + '&#9660;').html_safe
      end
    else
      direction = 'asc'
    end

    parameters = { search: search.params.merge({ s: "#{column} #{direction}" }) }
    link_to(title, parameters, class: 'sort_link')
  end
end
```

**Comment by seanfcarroll** [comment]
Nice code @ncliffor 

Closing this.
