### ISSUE TITLE
wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by Karthikds** [activerecord-hackery/ransack#1134]
Hi, 
I am using Recurring_select gem in my app which also, uses ransack. After, Upgrading my Rails version to 5, It's throwing wrong number of arguments (given 1, expected 0) error. When I tried to check the backtrace, it's seems like it's an error from ransack. Can you please help me to resolve tihs issue?

ransack - 2.3.2
recurring_select - 2.0

Thanks for the help, in advance

**Comment by kjg** [comment]
Try requiring recurring_select before ransack in your Gemfile.

Ransack re-opening `ActionView::Helpers::Tags::Base` seems to cause some issue when other gems subclass it

**Comment by seanfcarroll** [comment]
Looks like this is an implementation issue, closing.
