### ISSUE TITLE
When the relationship is polymorphic, the query results are abnormal

### ISSUE THREAD

**Issue by LPFpengfei** [activerecord-hackery/ransack#1137]
I had some problems using ransack today，I have a table "banks",  He associates the organization table and the worker table with source_type and source_id,But there was an error when I used source_of_Worker_type_code_eq to query a worker's card data，Like this `Bank.ransack({source_of_Worker_type_code_eq: "C201907160W1"}).result.to_sql` ，I hoped to get the bank card data with the worker id "C201907160W1" (the worker id is 4), but I not only got the bank card data of the worker, but also the bank card data of organization id 4, which surprised me， sql like "SELECT "banks".* FROM "banks" LEFT OUTER JOIN "workers" ON "workers"."id" = "banks"."source_id" WHERE "workers"."code" = 'C201907160W1'", I think the correct SQL should look like this `SELECT "banks".* FROM "banks" LEFT OUTER JOIN "workers" ON "workers"."id" = "banks"."source_id" WHERE "workers"."code" = 'C201907160W1' and bank.source_type = "Worker"`

**Comment by PhilCoggins** [comment]
I fixed this in https://github.com/activerecord-hackery/ransack/pull/1122/files but I don't think a new tag has been released yet.

**Comment by LPFpengfei** [comment]
I'm using `Bank.ransack({source_type: 'Worker',source_of_Worker_type_code_eq: "C201907160W1" })`to prevent the above problem, but I don't think it's a good idea
