### ISSUE TITLE
Sorting on numeric field inside json object

### ISSUE THREAD

**Issue by r-zia** [activerecord-hackery/ransack#1141]
I am trying to perform sorting based on JSONB field using ransack but it performs text-based sorting rather than numeric sorting. Is there a workaround for this?
 
Inside my model, I have following code
```ruby
ransacker :accounts do |parent|
   Arel::Nodes::InfixOperation.new('->>', parent.table[:values], Arel::Nodes.build_quoted(:number))
end
```
Seach works fine for this but when I perform sort it returns wrong sorting

it return 1,100,1000,2,2000 instead of 1,2,100,1000,2000

**Comment by PhilCoggins** [comment]
`->>` operator returns text, see https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-OP-TABLE. You will need to cast to numeric yourself, maybe something like:

```ruby
ransacker :accounts do |parent|
  Arel::Nodes::NamedFunction.new(
    'CAST',
    [Arel::Nodes::InfixOperation.new('->>', parent.table[:values], Arel::Nodes.build_quoted(:number))
      .as(Arel::Nodes::Quoted.new('INTEGER'))]
  )
end
```

**Comment by r-zia** [comment]
thanks, @PhilCoggins. Although I couldn't get it working for both sorting and search at a time, it helped a lot. I figured it out by separating definitions for sorting  and search with different operators 

**For Sorting** 

```ruby
ransacker :account_sort do |parent|
  Arel::Nodes::InfixOperation.new('->', parent.table[:values], Arel::Nodes.build_quoted(:number))
end
```
**For Text-Based Searching**

```ruby
ransacker :account do |parent|
  Arel::Nodes::InfixOperation.new('->>', parent.table[:values], Arel::Nodes.build_quoted(:number))
end
```
