### ISSUE TITLE
Warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

### ISSUE THREAD

**Issue by OttilieWilliams** [activerecord-hackery/ransack#1146]
**Steps to reproduce**
Install latest Ruby 2.7.1 from Rbenv
Run Cucumber tests

**Expected behavior**
No errors or deprecation messages.

**Actual behavior**
Warnings:
```
/Users/example_user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ransack-2.3.2/lib/ransack/translate.rb:86: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/example_user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/i18n-1.8.5/lib/i18n.rb:195: warning: The called method `translate' is defined here
```
**System configuration**

Rails version:
`Rails 6.0.3`

Ruby version:
`Ruby 2.7.1`

**Additional Comments:**

The warnings only appear when in the gemfile ransack is set as:
`gem "ransack"`

The warnings stopped appearing when we changed this to:
`gem "ransack", git: "https://github.com/activerecord-hackery/ransack"`

We would like to continue using the gem version - perhaps this needs to be updated in line with the master branch?

**Comment by coding-chimp** [comment]
As far as I can tell this has been fixed in #1121, but there hasn't been any new release since then.

**Comment by pond** [comment]
👍 on this - under 2.7.x, this deprecation warning happens quite often. Good to see a PR merged in & looking forward to a new release.

**Comment by seanfcarroll** [comment]
Closing this as fixed, @OttilieWilliams please reopen if still a problem.
