### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#1159]
Looking for a new maintainer for Ransack, I am sorry but don't have the time myself.

Please email me at ransack AT seancarroll.com if you are interested.

**Comment by deivid-rodriguez** [comment]
I talked to @seanfcarroll privately and I will try spend some time on getting ransack more stable and usable under rails 6.1.

**Comment by seanfcarroll** [comment]
Thank you @deivid-rodriguez 

Additional maintainers are still wanted if you are interested.

**Comment by seanfcarroll** [comment]
Thank you everyone who has sent messages, we will look over them and reply soon. Closing this issue out now.
