### ISSUE TITLE
Migrate to TravisCI.com

### ISSUE THREAD

**Issue by deivid-rodriguez** [activerecord-hackery/ransack#1168]
I'll be enabling the migration to the newer TravisCI infrastructure, just to make sure whether that makes the CI not unbearably slow. If that doesn't work, we'll need to migrate to another CI system.

**Comment by seanfcarroll** [comment]
GitLab comes to mind, and they do have an open source program. It would even be possible to migrate to GitLab and mirror the repo back here.

Any thoughts on that? What about you @ernie ?

Disclaimer: I work for GitLab 😄

**Comment by deivid-rodriguez** [comment]
I've never migrated a gem to Gitlab, but if you feel confident about doing the migration in a 100% compatible way for end users, I don't mind moving!

For now I hope travis-ci.com will make CI reasonably fast again :pray:.

**Comment by seanfcarroll** [comment]
>  you feel confident about doing the migration in a 100% compatible way for end users, I don't mind moving!

The main change for users would be that issues would be opened on GitLab rather than GitHub. Perhaps we should have an issue to discuss among Ransack users.

In the meantime I will discuss what could be available within GitLab. It is also possible to use the GitLab CI (which is awesome by the way) from a GitHub repo ... it's just a bit more fiddly. 

https://about.gitlab.com/solutions/open-source/join/

Maybe it's something for the future?

**Comment by deivid-rodriguez** [comment]
> The main change for users would be that issues would be opened on GitLab rather than GitHub. Perhaps we should have an issue to discuss among Ransack users.

That seems fine, I was thinking more on the mirror you mentioned and to keep existing Gemfiles pointing directly to the github repo working.

In any case, I just want a fast CI at the moment, it seems a bit overkill to migrate everything just for that?

Anyways, hopefully running on travis-ci-com will do the trick.

**Comment by deivid-rodriguez** [comment]
I requested the migration on the travis-ci.com side, and now it's in a "pending" state. I think some `activerecord-hackery` organization owner needs to approve it, but I'm not fully sure.

**Comment by seanfcarroll** [comment]
@deivid-rodriguez I just checked and I don't appear to have permissions. 

@ernie could you please approve the migration?

**Comment by deivid-rodriguez** [comment]
I think the request should appear on https://github.com/organizations/activerecord-hackery/settings/installations.

**Comment by ernie** [comment]
@deivid-rodriguez it was a little wonky, but i think it went through now.

**Comment by deivid-rodriguez** [comment]
Yes, CI is running on travis-ci.com now, thanks a lot @ernie!

**Comment by seanfcarroll** [comment]
Thank you @ernie and @deivid-rodriguez !!

**Comment by slonopotamus** [comment]
How do you live with build time limits?

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

Do you somehow periodically request additional credits from Travis?

**Comment by slonopotamus** [comment]
Oh, you don't. I found commit 5396ae1adc597939dabbdca3541ae52c7f76577f.
