### ISSUE TITLE
Tests wanted

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#1175]
Ransack is an awesome Gem, isn't it?

There are many open issues in Ransack that appear to be real bugs, but there is not the capacity to fix them.

Do you want to help, but don't feel up the task of contributing to the codebase? Well, there are other super-helpful things you could do:

- Some issues are marked  "tests wanted". If you want to help please write a failing test that describes the issue on a branch and submit a PR with a note that it is a test only. It will make the job of the developers a **lot** easier.

- Read through older issues and see if you have any insights add a comment.

Every bit helps! Thank you !

**Comment by mcmegavolt** [comment]
Can I write a small Rails app with a failing test that describes the issue I faced with?

**Comment by seanfcarroll** [comment]
@mcmegavolt thanks for your question. If possible it is best to write failing test(s) and submit them as a PR with some detail. That way other contributors can just make the tests pass and we are good.

**Comment by seanfcarroll** [comment]
Closing this issue out.
