### ISSUE TITLE
select tag with prompt option -- prompt goes away after search

### ISSUE THREAD

**Issue by tomharrisonjr** [activerecord-hackery/ransack#119]
Brilliant gem -- thanks!!!

I have a select tag in my search form like this

```
    <%= f.label :status_eq, "Status" %>
    <%= f.select :status_eq, Bill::STATUS.invert, :prompt => "Any" %>

```

When I first display the form, the "Any" prompt appears as expected.  If I search by this field by selecting an option, I get the proper filter, but the options in the select tag no longer contain the "Any" prompt.  Am I doing something wrong?

I can work around by using `:include_blank => true` instead of the prompt.

Thanks --

Tom

**Comment by pnomolos** [comment]
For anyone else getting this problem, using `include_blank: "Any"` (or whatever label you want to use instead of 'Any') is the correct solution.  `prompt: 'Any'` will only show up when nothing is selected.

**Comment by seanfcarroll** [comment]
Can someone add this to the Wiki?

**Comment by seanfcarroll** [comment]
Closed
