### ISSUE TITLE
Search for strings containing leading whitespace is broken

### ISSUE THREAD

**Issue by DCrow** [activerecord-hackery/ransack#1198]
After #1115 ransack started removing whitespace from search queries.
 
It is now impossible to search for those kind of strings. 
Some users in my project use names/label with leading spaces, so they depend on previous behavior.

Example
```ruby
Person.ransack("name_start" => " Wilson").to_sql
# => "SELECT \"people\".* FROM \"people\" WHERE \"people\".\"name\" LIKE 'Wilson%' ORDER BY \"people\".\"id\" DESC"
# Expecting 
# => "SELECT \"people\".* FROM \"people\" WHERE \"people\".\"name\" LIKE ' Wilson%' ORDER BY \"people\".\"id\" DESC"
```

Maybe add some kind of option to turn off whitespace stripping?

**Comment by seanfcarroll** [comment]
@DCrow that is a good point, I think the best option would be strip as default but to have a way to opt-out.

**Comment by seanfcarroll** [comment]
[This code](https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/configuration.rb#L29-L38) could become something like:

```ruby
    self.options = {
      :search_key => :q,
      :ignore_unknown_conditions => true,
      :hide_sort_order_indicators => false,
      :up_arrow => '&#9660;'.freeze,
      :down_arrow => '&#9650;'.freeze,
      :default_arrow => nil,
      :sanitize_scope_args => true,
      :postgres_fields_sort_option => nil,
      :strip_whitespace => true
    }
```

Which would give the ability to do:

```ruby
Ransack.configure do |c|
  c.strip_whitespace = false
end
```

**Comment by DCrow** [comment]
Seems good to me. Opt-out also seems logical since there might be projects which already utilize whitespace stripping.

Also maybe add some notes about this change(which version started whitespace stripping, etc) and option in README?

**Comment by seanfcarroll** [comment]
Closed by https://github.com/activerecord-hackery/ransack/pull/1214
