### ISSUE TITLE
cronjob is failing

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#1204]
[cronjob](https://github.com/activerecord-hackery/ransack/blob/master/.github/workflows/cronjob.yml) has been failing since 5th February. Not sure what the cause is, as the most recent commit to master was 26th January.

@yahonda do you have any insights here?

**Comment by yahonda** [comment]
Thanks for the info.
It is because the next version of Rails is 7. It used to be 6.2. Let me open a pull request later.

**Comment by seanfcarroll** [comment]
@yahonda FYI cronjob is failing again, it looks like Ruby version.

**Comment by yahonda** [comment]
https://github.com/activerecord-hackery/ransack/pull/1209 has been opened.
