### ISSUE TITLE
Custom predicate for searching multiple columns

### ISSUE THREAD

**Issue by brewpoo** [activerecord-hackery/ransack#122]
Can't find any info on this. Is there any way to do something like this.

Model has two attributes defining a range, something like:
optimum_temp_high
optimum_temp_low

Want user to be able to put a single value in and have ransack search both columns, like:
optimum_temp_low < input_value < optimum_temp_high

**Comment by jeffleeismyhero** [comment]
This is an old issue, but it's still open. Is there a way to do this currently?

Example: `start_range_gteq_and_end_range_lteq`

**Comment by jeffleeismyhero** [comment]
I found this: https://github.com/activerecord-hackery/ransack#using-scopesclass-methods

Which allows me to do:

```
scope :voucher_in_range, -> (n) {
    joins(:voucher_books).where(
      '? BETWEEN voucher_books.start_range AND voucher_books.end_range', n
    )
  }
```

Then, I can use `voucher_in_range` to achieve my goal.

**Comment by seanfcarroll** [comment]
Any chance of adding this to the Wiki?

**Comment by seanfcarroll** [comment]
Closed
