### ISSUE TITLE
Ransack trims trailing whitespaces.

### ISSUE THREAD

**Issue by omaik** [activerecord-hackery/ransack#1222]
Hey, could you please advise me whether this expected behavior or not, and what the intention behind it. Thanks. 

See example.

```
[4] pry(main)> Quote.ransack(error_details_eq: 'abc  ').result.to_sql
=> "SELECT \"quotes\".* FROM \"quotes\" WHERE \"quotes\".\"error_details\" = 'abc'"
[5] pry(main)> Quote.where(error_details: 'abc   ').to_sql
=> "SELECT \"quotes\".* FROM \"quotes\" WHERE \"quotes\".\"error_details\" = 'abc   '"
```

and btw, thanks for an awesome gem and the work you do here ❤️

**Comment by deivid-rodriguez** [comment]
We started doing this at https://github.com/activerecord-hackery/ransack/pull/1126, and while the default is now to strip whitespace, a way to opt-out was added at https://github.com/activerecord-hackery/ransack/pull/1214.

So, to keep the original string use

```ruby
Ransack.configure do |c|
  # Change whitespace stripping behaviour.
  # Default is true
  c.strip_whitespace = false
end
```
