### ISSUE TITLE
Handle `not_eq` with null rows

### ISSUE THREAD

**Issue by avit** [activerecord-hackery/ransack#123]
Given this query in raw SQL:

`SELECT x FROM records WHERE x != 'abcd'`

For records where the x value is null, SQL simply ignores the row. If I really want to find _all_ rows where the value is not "abcd", I need to specify:

`SELECT x FROM records WHERE x != 'abcd' OR x IS NULL`

From the front-end, having to add the "or null" in the form UI is not desirable. Could Ransack consider adding "or null" as an option for the negative predicates, or is there a better workaround?

I tried to wrap my head around possibly adding a replacement `not_eq` predicate to my Ransack::Configuration. I got close with this:

```
config.add_predicate("not_eq", arel_predicate: "not_eq_any", compounds: false, formatter: proc { |v| [nil, v] })
```

But this needs to flip the "nil" to "IS NOT NULL", which I don't think is possible in a `not_eq_any` which maps everything to `!=`, including various ways of defining "NOT NULL".

**Comment by ajporterfield** [comment]
An alternate solution for this is to monkey patch Arel::Predications in an arel.rb initializer with something like...

    def not_eq_or_null(other)
      left = not_eq(other)
      right = eq(nil)
      left.or(right)
    end

Then add the new predicate in a ransack.rb initializer.

    Ransack.configure do |config|
      config.add_predicate 'not_eq_or_null', arel_predicate: 'not_eq_or_null'
    end

That is producing the correct SQL for me.

    2.1.6 :001 > User.search(last_name_not_eq_or_null: 'Smith').result.to_sql
    => "SELECT \"users\".* FROM \"users\" WHERE (\"users\".\"last_name\" != 'Smith' OR \"users\".\"last_name\" IS NULL)"

**Comment by seanfcarroll** [comment]
Closed due to inactivity
