### ISSUE TITLE
Sort link should accept options for link_to

### ISSUE THREAD

**Issue by aurril** [activerecord-hackery/ransack#124]
The Rails link_to helper method gives you options for confirmation (:confirm), Ajax-request through unobtrusive JavaScript (:remote) and the HTTP-Verb used (:method). 

The sort_link helper should at least accept the :remote and :method options aswell. In the current stable release this is not possible.

**Comment by sajawalkhan** [comment]
as

**Comment by cecomp64** [comment]
> You just need to pass them via the `:html_options` like so
> 
> ```
> <%= sort_link @search, :name, {}, { :remote => true, :method => :post } %>
> ```

This very similar version worked for me, too:

```
<%= sort_link @search, :name, 'My Name', {}, { :remote => true } %>
```
