### ISSUE TITLE
Source code in ransack gem v2.4.2 is not the same as in master branch

### ISSUE THREAD

**Issue by r72cccp** [activerecord-hackery/ransack#1243]
Hi! I'm stuck on problem - the gem version 2.4.2 isn't contains source code from master branch.
For example, README.md in master branch contains from line #92 next block:

> After version 2.4.0 when searching a string query Ransack by default strips all whitespace around the query string.
This may be disabled by setting the `strip_whitespace` option in a Ransack initializer file:
```ruby
Ransack.configure do |c|
  # Change whitespace stripping behaviour.
  # Default is true
  c.strip_whitespace = false
end
```

But when i'm open the README.md file from my rvm (~/.rvm/gems/ruby-2.6.5/gems/ransack-2.4.2/README.md) this code block is absent. Why?

**Comment by gregmolnar** [comment]
@r72cccp master has a lot of commits since the `2.4.2` release. You can look at that version on this link on github: https://github.com/activerecord-hackery/ransack/tree/v2.4.2
