### ISSUE TITLE
Rails 7.0.0.alpha-1 - cannot load such file -- polyamorous/activerecord_7.0_ruby_2/join_association

### ISSUE THREAD

**Issue by dwightwatson** [activerecord-hackery/ransack#1251]
Hi, this is a follow-up to issue #987. It now occurs again when running with Rails 7.0.0.alpha-1.

Simple fix it run from GitHub, but ideally a new tagged release can be made.

```
gem 'ransack', github: 'activerecord-hackery/ransack'
```

**Comment by cloudsbird** [comment]
Tested and run in "rails", "~> 7.0.0.alpha2"

**Comment by Intrepidd** [comment]
Hello ! Rails 7 is now rc1 and I just stumbled into this issue while trying to upgrade, just so you know more and more people are going to experience it

**Comment by dwightwatson** [comment]
7.0.0 has now landed, would be great to see a versioned release made.

**Comment by kitsuneyo** [comment]
> Hi, this is a follow-up to issue #987. It now occurs again when running with Rails 7.0.0.alpha-1.
> 
> Simple fix it run from GitHub, but ideally a new tagged release can be made.
> 
> ```
> gem 'ransack', github: 'activerecord-hackery/ransack'
> ```

Thank you for this, it works great on my local system, although deploying to Elastic Beanstalk failed with this line in the gemfile.

**Comment by juanmanuelramallo** [comment]
> 7.0.0 has now landed, would be great to see a versioned release made.

This would be much appreciated!

**Comment by gregmolnar** [comment]
I released 2.5.0 with Rails 7 support.
