### ISSUE TITLE
Rename attributes

### ISSUE THREAD

**Issue by thomaschauffour** [activerecord-hackery/ransack#1264]
Hello,

I'm using the "attribute_select" helper and I can't find a way to rename the attributes to make them more explicit for users. 

Or is there a way to pass an array of attributes to this helper?

Thanks

**Comment by deivid-rodriguez** [comment]
Have a look at https://github.com/activerecord-hackery/ransack#i18n, I think it should answer your question!

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
