### ISSUE TITLE
Rails 7 undefined method `page' for #<ActiveRecord::Relation

### ISSUE THREAD

**Issue by mnifakram** [activerecord-hackery/ransack#1265]
ruby version: 3.0.3
rails version: Rails 7.0.0.alpha-2

installed gem from github using 
```
gem 'ransack', github: 'activerecord-hackery/ransack'
```

Issue:
```bash
irb(main):004:0> tmp = Person.ransack()
=> Ransack::Search<class: Person, base: Grouping <combinator: and>>
irb(main):005:0> tmp.result.page(50).per(10)
/Users/akram/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/rails-b6bc552c1f56/activerecord/lib/active_record/relation/delegation.rb:110:in `method_missing': undefined method `page' for #<ActiveRecord::Relation [#<Person email:, ...]> (NoMethodError)
irb(main):006:0>
```

Any ideas on how to get around it?

Thanks.

**Comment by pustomytnyk** [comment]
You probably intended to use it with another gem for pagination.

**Comment by mnifakram** [comment]
Well I figured out that the conflict is due to [jsonapi.rb](https://github.com/stas/jsonapi.rb) gem which uses the latest release of ransack which is way behind master branch. So I think in order to get this fixed, we need to have a new release of ransack. Is there any plans to do this? Or if someone please give me some tips on how to get this fixed. Thanks

**Comment by gregmolnar** [comment]
@mnifakram you can always just bundle the gem from master instead of the released version and that should've fixed the issue. I will try to cut a release shortly.
