### ISSUE TITLE
search in polymorphic association end up with error

### ISSUE THREAD

**Issue by ghn** [activerecord-hackery/ransack#1270]
Hey 👋 

Just notice a bug with latest version 2.5.0 with polymorphic association

This works: ✅ `<input name="q[taskable_of_Product_type_name_eq]"`
This not ❌ `<input name="q[taskable_of_product_type_name_eq]"` (notice `product` with lowercase)

--> and boom 💥  `wrong constant name product`

It would be nice to `string#capitalize`

**Comment by deivid-rodriguez** [comment]
Hi! Would you be able to verify whether #1275 fixes the issue?

**Comment by ghn** [comment]
> Hi! Would you be able to verify whether #1275 fixes the issue?

Hello!
I just tested with your branch and I'm sorry, but this is not fixing the problem described above.

**Comment by deivid-rodriguez** [comment]
Ok, can you share steps to reproduce your problem, then?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
