### ISSUE TITLE
ASK: Can we find latest record of an association?

### ISSUE THREAD

**Issue by helmiattastify** [activerecord-hackery/ransack#1272]
Can we find the latest association using ransack?

Let's say we have two models are User and Subscription

```
class User
   has_many :subscriptions
end
```

```
class Subscription
   belongs_to :user
end
```

User has many subscriptions

Let's say I have a user view

and 
```
User.ransack(params[:q])
````
Can I get the latest of the subscriptions of the users on user view?

**Comment by deivid-rodriguez** [comment]
It doesn't sound like you need ransack for this? On a user view you'll normally have access to the user instance, so you should be able to do `user.subscriptions.last`?

**Comment by helmiattastify** [comment]
@deivid-rodriguez,

So in my case is, the user has many subscriptions,

let's say I have 3 subscription types.

1. free trial
2. paid
3. suspend

In a year a user has
January: tree trial
February: paid
march: paid
April: suspend
may: paid
etc.

I have users list in the table and I have advanced search, one of the search params is a subscription
The easy way is using joins, but I have other search params like date, sales name, etc.

In fact, I have to show the user list left outer joins subscriptions

In this case, I want to show the last subscription has from a user if want to search "Suspend" subscription

Ransack still show the user in may with paid status

So I make my own filter like

user.subscription.last == params[:subscription_type]

let say params[:subscription_type] = :suspend

I know that's too dirty and load so many caches from association data.

That's a bad idea.

My question is how do in ransack side filter last subscriptions from a user?
