### ISSUE TITLE
How to query using multiple search values?

### ISSUE THREAD

**Issue by masudhossain** [activerecord-hackery/ransack#1274]
Any idea how i can do a query by entering multiple search values?

I tried below, but it doesn't work. 
Single search value: `q[specialization_cont]=product_des`
Multiple search values separated using a comma:`q[specialization_cont]=[product_des,graphic_designer]`

Also tried `?q[specialization_or_description_cont]=product&q[specialization_or_description_cont]=graphic`, but only shows last one.

**Comment by deivid-rodriguez** [comment]
I thing you want the `_in` matcher? https://github.com/activerecord-hackery/ransack/tree/49a43fc9519408e47a4844d3cdbeb2838687041a#search-matchers.

```
q[specialization_in][]=product_des&q[specialization_in][]=graphic_designer
```

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
