### ISSUE TITLE
Poll: Update the Ransack Logo

### ISSUE THREAD

**Issue by scarroll32** [activerecord-hackery/ransack#1283]
The [activerecord-hackery](https://github.com/activerecord-hackery) logo is IMHO far cooler than the current Ransack logo. This issue proposes replacing the existing logo with the group logo as part of the [3.0.0]() release.

Please cast your vote by adding an emoji to this issue! 

**We also need help from a designer to produce the new assets.**

If the vote is a tie, we will stay with the current logo.

<img width="123" alt="Screenshot 2022-03-10 at 16 17 22" src="https://user-images.githubusercontent.com/11340230/157692893-3291c723-fdcd-46b4-936a-6cd47a1a41e6.png"> - Vote with 🎉 

<img width="116" alt="Screenshot 2022-03-10 at 16 17 12" src="https://user-images.githubusercontent.com/11340230/157692923-0d116766-d009-4dd3-b180-bff62fa42cb8.png"> - Vote with ❤️ 

![ransack](https://user-images.githubusercontent.com/32838548/157927775-1dc49ebe-9f6d-4745-8e3a-4ad630b3b1dc.png) - Vote with 🚀

**Comment by Ancez** [comment]
> In my mind, the Ransack logo makes more sense for Ransack, although maybe less cool indeed. I voted for the current logo but I'm happy if you decide to change it 👍.

I agree, Ideally I'd consider a third option that's not on the list, which includes a search icon instead of the ax, to keep the logo project specific

**Comment by scarroll32** [comment]
> > In my mind, the Ransack logo makes more sense for Ransack, although maybe less cool indeed. I voted for the current logo but I'm happy if you decide to change it 👍.
> 
> I agree, Ideally I'd consider a third option that's not on the list, which includes a search icon instead of the ax, to keep the logo project specific

@Ancez that could be cool ... we would need a designer to create the icon. Any ideas ?

**Comment by Ancez** [comment]
Hmm, so I'm imagining something like this
![ransack](https://user-images.githubusercontent.com/32838548/157927775-1dc49ebe-9f6d-4745-8e3a-4ad630b3b1dc.png)

What do you think? But yeah, we would need a designer, I'm just a developer 🤘

**Comment by scarroll32** [comment]
> Hmm, so I'm imagining something like this ![ransack](https://user-images.githubusercontent.com/32838548/157927775-1dc49ebe-9f6d-4745-8e3a-4ad630b3b1dc.png)
> 
> What do you think? Can tidy it up a bit further. But yeah, we would need a designer, I'm just a developer 🤘

I love this ... simple and clear

**Comment by deivid-rodriguez** [comment]
Why not, looks nice to me too.

**Comment by scarroll32** [comment]
@anilkilic you designed Ransack's last logo, would you be available to update it for us with new SVGs etc. ?

**Comment by scarroll32** [comment]
Still looking for a UX person to do the SVGs if available?

**Comment by Ancez** [comment]
The majority still prefers the original so unsure whether the suggested logo is still worth it?

I'll spend some time this week/weekend iterating over it. I would like to use a new magnifying glass though as the suggested one doesn't seem perfect

**Comment by rubyFeedback** [comment]
Has there been a resolution to this? Personally I prefer the magnifier glass over the axe or other objects; and I like blue more than the reddish diamond too. Note I refer to the third image logo actually; while the "R" and lens is interesting, the lens are hard to see, which is why I prefer the look of the lens in the third image.

**Comment by scarroll32** [comment]
> Has there been a resolution to this?

**13 votes** to leave it as-is vs **5 votes** for the "Rails" logo. 

I'm going to call this as leaving it as-is, as close this issue with no changes!
