### ISSUE TITLE
Revert Rails version drop from 2.6 release

### ISSUE THREAD

**Issue by tvdeyen** [activerecord-hackery/ransack#1284]
You released a breaking change in a minor version update. Rails 5.2 still receives security patches. The drop could have been release as a major version Bump. 

I suggest to 

- release a 2.6.1 that reverts the drop 
- release a 3.0.0 (maybe pre) that includes the drop

Thanks

**Comment by deivid-rodriguez** [comment]
I don't consider dropping support for dependencies as a breaking change. The rationale is that... it doesn't break anything. Version managers (bundler & rubygems) will simply not choose Ransack 2.6.0 if you are still using Rails 5.2. Once you upgrade Rails, version managers will allow you to use Ransack 2.6.0.
