### ISSUE TITLE
Why doesn't Ransack's search function work?

### ISSUE THREAD

**Issue by KtKeaton** [activerecord-hackery/ransack#1286]
I'm trying to set the Ransack gem to search for my "name" field in the homepage list. However, after I enter the name value that actually exists, the web page becomes blank and has no effect.

This is my controller#action
```
  def index
    @tasks = Task.all.order("created_at desc")

    @name = Task.ransack(name_cont: params[:name])
    @tasks = @name.result
  end
```

This is my View
```
<%= search_form_for @name do |f| %>
  <%= f.label "Search for Mission Name" %>
    <%= f.search_field :name %>
      <%= f.submit %>
        <% end %>
```

**Comment by scarroll32** [comment]
@KtKeaton please ask "how to" questions on [StackOverflow](https://stackoverflow.com/questions/tagged/ransack)
