### ISSUE TITLE
Delete Wiki content

### ISSUE THREAD

**Issue by scarroll32** [activerecord-hackery/ransack#1295]
As the Wiki content has now been moved into the documentation site, the Wiki can be deleted. Leaving it around for a few weeks just in case.

- https://activerecord-hackery.github.io/ransack/
- https://github.com/activerecord-hackery/ransack/pull/1291

**Comment by deivid-rodriguez** [comment]
Something I think should be done is at least credit the original Wiki authors. It just came to my mind that it was possible to export wiki content as git commits, and that would've been the right way to approach this and preserve original authorship but that ship has now sailed so I think we can still grab a full list of wiki contributors and credit them in the documentation site?

**Comment by scarroll32** [comment]
> credit the original Wiki authors.

This is an excellent idea @deivid-rodriguez 

> t was possible to export wiki content as git commits, and that would've been the right way to approach this and preserve original authorship

I didn't think of that 🤦  Part of the process was a reorganisation of the docs though.

I think it would still be possible to preserve this history:

- export all of the wiki entries on branch and create a PR
- close the PR without merging, to keep as a history
- Add entries to the CHANGELOG and also within the docs site itself to credit each author

I can look after this if you think this is a good approach.

**Comment by deivid-rodriguez** [comment]
It seems too much trouble to me at this point, I think it would be fine to add a list of original contributors to the documentation site and that would be enough.

**Comment by scarroll32** [comment]
List of contributors [added](https://activerecord-hackery.github.io/ransack/going-further/wiki-contributors).

**Comment by scarroll32** [comment]
Deactivated the Wiki in the settings. It's not actually deleted.
