### ISSUE TITLE
Increased gem size since 3.0.0

### ISSUE THREAD

**Issue by ybiquitous** [activerecord-hackery/ransack#1296]
Hi there, congrats on the major release 3.0.0 🎉 

I notice that 3.0.0 has increased the gem size much more than 2.6.0.

<img width="228" alt="image" src="https://user-images.githubusercontent.com/473530/161184129-c4448f11-2509-4117-ba68-bc5108c01500.png">

https://rubygems.org/gems/ransack/versions

Maybe, added files in the `docs/` directory is a cause:

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/473530/161184422-3b06103f-9dcc-4f85-b444-8615c8b630bd.png">

https://my.diffend.io/gems/ransack/2.6.0/3.0.0

Is it acceptable to reduce the gem size?

**Comment by deivid-rodriguez** [comment]
Hello @ybiquitous! This is somewhat expected because the whole wiki content has been moved inside the gem. I think the size increase is acceptable, and the docs are fine to be shipped together with the gem, so in principle I wouldn't do anything about this. Is this very critical to you?

**Comment by ybiquitous** [comment]
Hi @deivid-rodriguez, thank you for the quick feedback.

Unless big files will be added, the gem size won’t be a problem.

I often check diff between the gem versions on <https://my.diffend.io>, so I’m a bit concerned about noises but it’s not a big problem.

Feel free to close the issue if no concerns. Thank you. 😃

**Comment by scarroll32** [comment]
@ybiquitous I don't expect the memory size to have changed, but it would be a worthwhile activity to check before and after the 3.0.0 release. 

I will get to it, but feel free to check it yourself and add the results here. This [blog post](https://www.honeybadger.io/blog/profile-your-gem-memory-usage-with-derailed/) explains how to do it.

**Comment by deivid-rodriguez** [comment]
@scarroll32 I think memory usage is not related to this ticket, the is only about the gem package size increase. Anyways, it's still less that 1Mb, it doesn't seem too bad, so I'll close this!

**Comment by scarroll32** [comment]
Another option would be to keeping the markdown docs in the main repo and move the website build code in an another and build it with CI.

**Comment by deivid-rodriguez** [comment]
I created #1297 which reduces gem size to 516K.
