### ISSUE TITLE
No search in docs site

### ISSUE THREAD

**Issue by deivid-rodriguez** [activerecord-hackery/ransack#1314]
I don't see a search bar in documentation site, I guess we need to configure something else? It's strange, I think I recall the search bar working at some point?

**Comment by scarroll32** [comment]
I thought it was previously working also. It doesn't need anything external AFAIK.

**Comment by scarroll32** [comment]
We can add Algolia for free 

https://docusaurus.io/docs/search#using-algolia-docsearch

**Comment by deivid-rodriguez** [comment]
I applied!
