### ISSUE TITLE
Unable to customize the attribute_select options

### ISSUE THREAD

**Issue by lironbeni** [activerecord-hackery/ransack#133]
Want to be able to customize the ransackable_attributes keys.

meaning if my code is this:

ARRAY_OF_COLUMNS_YOU_WANT_TO_INCLUDE = ["description","name","sysid"]

def self.ransackable_attributes (auth_object = nil)
  ARRAY_OF_COLUMNS_YOU_WANT_TO_INCLUDE + _ransackers.keys
end

my select box would be this:

<select  name="q[c][0][a][0][name]" id="q_c_0_a_0_name" class="valid">
<option value="description">Description</option>
<option value="name">Name</option>
<option value="sysid">Sysid</option>
</select>

I would like to be able to send select_attribute or ransackable_attributes strings to present to the user such as:
ARRAY_OF_COLUMNS_YOU_WANT_TO_INCLUDE = [{"description"=>"Description"},{"name"=>"Title"},{"sysid"=>"System ID"}]

That will produce:
<select  name="q[c][0][a][0][name]" id="q_c_0_a_0_name" class="valid">
<option value="description">Description</option>
<option value="name">Title</option>
<option value="sysid">System ID</option>
</select>

I think this is mandatory functionality, to be able to customize what you present to the user. (hide DB table columns is important if you want to save yourself from SQL injection)

**Comment by pallavihegde1** [comment]
Is there a way to remove some attributes from the dropdown in the view?? 
I am basically trying to remove all the integer attributes and use it separately to give a dropdown for it. 
If i remove the attribute from ransackable attributes i wont be able to use it in a separate dropdown too...

**Comment by chase1745** [comment]
@pallavihegde1 I did what you are asking using jquery by using the following function to change the search box to a select drop-down box, and then dynamically added the options, and hid the predicate select when the user selects one of the attributes that should have a drop-down instead of a search box.
    
    function change_tag(classToChange, type) {
        var attrs = { };

         $.each($(classToChange)[0].attributes, function(idx, attr) {
             attrs[attr.nodeName] = attr.nodeValue;
         });

         $(classToChange).replaceWith(function () {
             attrs.text = $(this).text();
             return $(type, attrs);
         });
    }
