### ISSUE TITLE
Search by minutes

### ISSUE THREAD

**Issue by marcioniliolive** [activerecord-hackery/ransack#1335]
I have the following question, is it possible to create a query in ransack, where in the filter screen we enter a minute: EX: 04 or 53. Soon all the records that were created in that minute will come, regardless of the day or time, I want to filter by the minutes. Taking advantage of the question, if it is possible by the minute, by the hour too, right?

**Comment by deivid-rodriguez** [comment]
I'm sure it's possible, but this is a question more appropriate for https://stackoverflow.com where a wider community can help you!
