### ISSUE TITLE
Would an ActsAsTaggableOn extension for Ransack be possible?

### ISSUE THREAD

**Issue by jhilden** [activerecord-hackery/ransack#135]
Hi,

we just started using Ransack and I have to say, I really, really love it's API!

We are also using ActsAsTaggableOn (https://github.com/mbleigh/acts-as-taggable-on) and I was wondering what it would take to write something like a Ransack "extension" or so to integrate with ActsAsTaggableOn?

```
# model
class User < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :skills, :interests
end

# view
f.text_field :tagged_with_skills
f.text_field :tagged_with_skills_any
...

# would be translated into:
User.tagged_with(params[:q][:tagged_with_skills], :on => :skills)
User.tagged_with(params[:q][:tagged_with_skills], :on => :skills, :any => true)
...
```

Any assessment on whether and how this would be possible, would be very appreciated.

**Comment by norato** [comment]
You can add it by association, f.e.:
```
class Person < ActiveRecord::Base
   PERSON_SEARCH_OPTIONS = :name_or_email_or_tags_name_cont
end
```
It works for me

I think it is the better way to do it.

**Comment by dominiceden** [comment]
The answer from @norato above worked well, but I found I didn't need to add anything to the model, just the view. This worked for my recipes page (`index.html.erb`):

    <%= search_form_for(@search) do |f| %>
      <%= f.search_field :title_or_ingredients_or_tags_name_cont %>
      <%= f.submit %>
    <% end %>

**Comment by norato** [comment]
@dominiceden I just created this constant in model, the functionality is the same. I did it 'cause we use a lot of custom searches in this page so we prefered to create as constants :-)

**Comment by metalelf0** [comment]
The problem with @norato solution is that you have the following tags: `['tag', 'tag_longer', 'tag_even_longer']`, when your search key is `'tag'` it will also find items tagged with `'tag_longer'` and `'tag_even_longer'`. Using `_eq` instead of `_cont` will only find elements with just one tag, so it's not a viable solution. Right now the only way I've found to perform a search with correct results is using the `tagged_with` helper from `acts_as_taggable_on`, but I have yet to find a way to put that into a Ransack `search_form_for` block.

**Comment by seanfcarroll** [comment]
@metalelf0 Any chance to document your findings in the Wiki?

**Comment by metalelf0** [comment]
Sure. Here's the link: https://github.com/activerecord-hackery/ransack/wiki/How-to-search-on-ActsAsTaggableOn-fields. Let me know if it's ok. :)

**Comment by taniarv** [comment]
I have been trying the proposed solution in https://github.com/activerecord-hackery/ransack/wiki/How-to-search-on-ActsAsTaggableOn-fields  but no luck. 

I have a model with just "acts_as_taggable", I use the 'tags' scope.
If I try to do a `<%= f.select :tags_in %>`
I get `undefined method tags_in for #<Ransack::Search:0x007f89bab7fa98>`

If I try `<%= f.select :tags_name_in %>`
It works!

**Comment by sutherland007** [comment]
@metalelf0 I've tried the [wiki link](https://github.com/activerecord-hackery/ransack/wiki/How-to-search-on-ActsAsTaggableOn-fields) and it throws "undefined method" this is my case:

in my model:
```
class Movie < ActiveRecord::Base
  acts_as_taggable_on :genres
end
```

in my view:
```
<%= search_form_for [:my_namespace, @q] do |f| %>
  <%= f.search_field :genres_in %> genres_in _eq or _cont throws "undefined method for #<Ransack::Search:0xaf45c20>" 
  <%= f.submit %>
<%= end %>
```

I'm using ruby 2.2.4, rails 4.2.6 and ransack 1.8.3

**Comment by metalelf0** [comment]
@sutherland007 if you don't mind uploading your app on github I'll download it and give it a try. Feel free to contact me on gitter.

**Comment by sutherland007** [comment]
@metalelf0 this is the [app](https://github.com/sutherland007/movies-ransack-test) feel free to test it.

**Comment by metalelf0** [comment]
@sutherland007 In your scenario the field name should be `genres_name_in`, `genres_name_cont`, or `genres_name_eq`. My guide is based on the simplest scenario possible, when tags are serialized on a model field of the same class; in your app `acts_as_taggable_on` stores the tag in a `name` attribute of the `Genre` model, and `ransack` has to know it has to traverse the `has_many :genres` association and use the `name` field for searching. See [the ransack Readme section on associations](https://github.com/activerecord-hackery/ransack#associations) for a deeper explanation. I'm sorry if my guide confused you.

**Comment by sutherland007** [comment]
@metalelf0 Thanks, i think you need to update your guide using this little experience with my app.  So I must say that` acts_as_taggable_on` is now working well with `ransack`.
