### ISSUE TITLE
search only specific attributes in association queries

### ISSUE THREAD

**Issue by lironbeni** [activerecord-hackery/ransack#136]
Hi Ernie,

How can I restrict the attributes of associated module in association query.

Say I have this in my condition_fields.html.erb file:
   <%= a.attribute_select :associations => [:member] %>

It will show in the select box about 24 member fields, while I would like to show only the name and the email of the member.

How to that?

Thanks,
Liron

**Comment by seanfcarroll** [comment]
Closed
