### ISSUE TITLE
Bug: undefined method `merge' for "abc":String

### ISSUE THREAD

**Issue by stereobooster** [activerecord-hackery/ransack#1365]
If I use URL like `...?utf8=%E2%9C%93&query[s]=&query=abc` there is an error `undefined method 'merge' for "abc":String`.

I added `params.permit(query: {})`, but it doesn't help

```
ransack (3.2.1) lib/ransack/helpers/form_helper.rb:179:in `search_and_sort_params'
ransack (3.2.1) lib/ransack/helpers/form_helper.rb:134:in `url_options'
ransack (3.2.1) lib/ransack/helpers/form_helper.rb:54:in `sort_link' 
```

**Comment by stereobooster** [comment]
```diff
def search_params
-  @params[@search.context.search_key].presence || {}
+  search_params = @params[@search.context.search_key]
+  search_params.is_a?(Hash) ? search_params : {}
end
```

**Comment by scarroll32** [comment]
@stereobooster I would look into how `=&query=abc` is being appended to your query. Ransack needs to manage the full query params.

Maybe we should validate the structure of the input? 🤔

**Comment by stereobooster** [comment]
> @stereobooster I would look into how =&query=abc is being appended to your query.

it's not. It was the user who manipulated URL

**Comment by scarroll32** [comment]
> > @stereobooster I would look into how =&query=abc is being appended to your query.
> 
> it's not. It was the user who manipulated URL

I see, OK I think your change makes sense. Any change to submit a PR?

**Comment by stereobooster** [comment]
I will try to get some time on weekend
