### ISSUE TITLE
ransack 2.3 with will_paginate 3.05

### ISSUE THREAD

**Issue by yulay** [activerecord-hackery/ransack#1366]
Hi everyone

a pleasure to greet you

i am working on a project with rails 5.1.7 and ruby ​​2.6.10

I'm showing records from a database but I can't paginate the results returned by ransack with will_paginate

can you give me a complete example please

I want to paginate the results five by five

I manage to paginate all the database records, but the ransack results are not

can you help me please

thankyou so much

**Comment by scarroll32** [comment]
Hi @yulay 

> Ransack is supported for Rails 7.0, 6.x on Ruby 2.6.6 and later.

Sorry, we don't support Rails 5.1.7
