### ISSUE TITLE
COMBINING ACUTE ACCENT search?

### ISSUE THREAD

**Issue by gingerlime** [activerecord-hackery/ransack#1369]
This is a bit of an odd one, but hope this is the right place to ask :)

We store utf-8 unicode data in our database, and we use active admin with ransack to search for it. All works well most of the time. However, we recently noticed that when we search for a specific type of letters that *look* the same, but aren't the same, we get no results.

For example, the letter [ú](https://qaz.wtf/u/show.cgi?show=%C3%BA&type=string) is stored in the database, but when we search for the letter [ú](https://qaz.wtf/u/show.cgi?show=u%CC%81&type=string) we get no results. The latter is a combination of `u` and what's called `COMBINING ACUTE ACCENT`.

I found [this SO answer](https://stackoverflow.com/a/31883184) which suggests we can use `unicode_normalize` to make them equivalent. I just wonder if there's a way to apply it by default with ransack? 

Code example:

```ruby
# returns results
Model.ransack(:spanish_name_cont => CGI.unescape("%C3%BA")).result

# empty results
Model.ransack(:spanish_name_cont => CGI.unescape("u%CC%81")).result
```

**Comment by stereobooster** [comment]
Hi. Did you check if this works with ActiveRecord?

```rb
Model.where('spanish_name LIKE ?', "%" + CGI.unescape("u%CC%81") + "%")
```

**Comment by gingerlime** [comment]
What we ended up doing as a workaround:

```ruby
# app/admin/active_admin/base_controller.rb
module ActiveAdmin
  class BaseController
    before_action :unicode_normalize_query

    def unicode_normalize_query
      return if params[:q].blank?

      params[:q] =
        params[:q].to_unsafe_h.deep_transform_values(&:unicode_normalize)
    end
  end
end
```

I guess we can close this, although it would be nice if something like this was included in activeadmin :)
