### ISSUE TITLE
Question: does Ransack follow SemVer?

### ISSUE THREAD

**Issue by tagliala** [activerecord-hackery/ransack#1381]
Hi,

I've tried to search into issues and the documentation but I wasn't able to understand if Ransack follows [SemVer](https://semver.org/)

It would be important to understand in order to properly configure the dependency on third-party gemspecs

**Comment by scarroll32** [comment]
@tagliala yes in theory we follow Semver. There may have been some lapses in the past, but we are being strict going forward.

Have you seen a mistake in previous version bumps?

**Comment by tagliala** [comment]
> Have you seen a mistake in previous version bumps?

Hi, nope thanks.

I've asked because I want to submit a PR to a third party library which has an upper limit to `< 3.2`
