### ISSUE TITLE
`ransack!` should fail when given an invalid combinator

### ISSUE THREAD

**Issue by kalsan** [activerecord-hackery/ransack#1396]
Hi and thanks for providing this incredible useful gem. Here's a small change that could make a developer's life even simpler:

Line in question: `User.ransack!(id_eq: 1, first_name_cont: 'Henry', combinator: :or)`

The combinator is invalid because it is of type `Symbol` instead of `String`. Since we are using `ransack!` and not `ransack`, I'd expect this to fail. However, Ransack silently converts this to `'and'`, which is unexpected (in my opinion).

I feel that if the bang method `ransack!` is used, any unexpected input (including to `combinator:`, `m:` etc.), be it the wrong class or the wrong word, should lead to an exception. However, I understand that this is a subjective topic and others might disagree.

Best,
Kalsan

**Comment by scarroll32** [comment]
@kalsan might this be handled by a custom rspec matcher?

**Comment by kalsan** [comment]
@scarroll32 I'm not familiar with rspec, could you elaborate?

**Comment by kalsan** [comment]
@bagp1 thank you very much for addressing this. Much appreciated. This issue can be closed whenever you are ready :-)

Cheers!
Kalsan
