### ISSUE TITLE
Datetime to date search

### ISSUE THREAD

**Issue by Epiju** [activerecord-hackery/ransack#143]
Hi,

I have in my model a datetime for created_at although I wanted the "equals" predicate to compare the created_at and a date (like '2012-09-26').

So I added in my model (in order to add casted attributes and take off the old created_at/update_at/deleted_at :

``` ruby
ransacker :created_at do
    Arel::Nodes::SqlLiteral.new("date(items.created_at)")
  end

  ransacker :updated_at do
    Arel::Nodes::SqlLiteral.new("date(items.updated_at)")
  end

  ransacker :deleted_at do
    Arel::Nodes::SqlLiteral.new("date(items.deleted_at)")
  end

  # Hide some attributes for advanced search
  UNRANSACKABLE_ATTRIBUTES = ["created_at", "updated_at", "deleted_at"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end
```

But when I confirm the query (created_at equals to '2012-03-24') I have this error:

> NoMethodError (undefined method `name' for "date(items.created_at)":Arel::Nodes::SqlLiteral):

Surprisingly, it works with "greater than" and "less than". Only "equals" occurs this error.

I made all of this for all my models and 60% works (the remain 40% occurs this error). 

In the console : 

> irb(main):232:0> Item.search(:created_at_eq => Date.today.to_s).result
> (Object doesn't support #inspect)

Thanks for your help

EDIT : 

I have a default_scope which makes  :
Item(:deleted_at false)

But I don't know why it occurs the error

**Comment by alexisraca** [comment]
You could just send greater than and less than symbols with the range dates and avoid all this fuzz
