### ISSUE TITLE
Sorting non-english characters

### ISSUE THREAD

**Issue by davideluque** [activerecord-hackery/ransack#1435]
In the Danish alphabet, we use the letters æ, ø, and å, which come last in sequence. But with Ransack's default sorting, "ø" seems to be recognized as either "o" or maybe "oe". Not quite sure.

<img width="205" alt="Screenshot 2023-08-21 at 13 52 56" src="https://github.com/activerecord-hackery/ransack/assets/10492210/950b3db2-8914-4cef-8905-cde8d21c90f2">

Controller

```ruby
@q = MyModel.ransack(params[:q])
@q.sorts = "position asc" if @q.sorts.empty?
```

View

```erb
<th class="text-nowrap"><%= sort_link(@q, :name, t(".headers.name")) %></th>
```

**Comment by davideluque** [comment]
I noticed we didn't have the correct sorting for Danish characters in our PostgreSQL database. To fix this, I used the ICU (International Components for Unicode) extension. I chose the da-DK-x-icu collation for Danish language sorting, as it's used in Denmark.

Here’s the migration I added:

```ruby
class UpdateMyModelNameCollation < ActiveRecord::Migration[7.0]
  def up
    execute <<-SQL
      ALTER TABLE MyModel
      ALTER COLUMN name TYPE varchar COLLATE "da-DK-x-icu";
    SQL
  end

  def down
    execute <<-SQL
      ALTER TABLE MyModel
      ALTER COLUMN name TYPE varchar;
    SQL
  end
end
```

Now our system can sort Danish characters correctly.

To see the collations your PostgreSQL installation supports, run:

```sql
SELECT collname FROM pg_collation;
```

**Comment by davideluque** [comment]
@scarroll32  Would this be something interesting to add to the documentation? I can only write the Postgres part or maybe just give users a lead on what could be the problem

**Comment by scarroll32** [comment]
@davideluque thank you for opening this issue, it is indeed a problem across many different languages.

Can you think of a way to make it language independent? ie: is the only way to do this in Postgres is by adding the collation?

>       ALTER COLUMN name TYPE varchar COLLATE "da-DK-x-icu";

**Comment by davideluque** [comment]
@scarroll32, database-level sorting seems to be the most efficient approach. While we could resort to Ruby's Array Sorting, it's not scalable for larger datasets.

Upon investigating collations, I found that they're specific to DBMS. 

I expect this issue to guide users and I wonder if there is something else we can do to help.
