### ISSUE TITLE
Suggested addition: a "clear" button for a search field, plus "clear all fields" button

### ISSUE THREAD

**Issue by leisti** [activerecord-hackery/ransack#147]
The title pretty much says it all. It'd be nice to have the possibility of adding a "Clear" button next to each search field that would (a) clear what the user had written in that field, and (b) immediately perform a new search with the changed parameters, that is, subtracting the filtering previously done by the cleared search parameter.

In the same vein, you could have a "Clear all fields" button, to be placed below the search fields, along with the "Search" button. Pressing this button would clear all search fields (surprise!), and perform a new "search" with the changed (empty) parameters -- that is, all the rows of the search space would be shown.

**Comment by Jack-Barry** [comment]
@mattconnolly Ha, funny how I'll forget simple tricks like this.  Beautiful

**Comment by sushiltech123** [comment]
<%= link_to "Clear Search", request.path, class:"cancel-button" %> after using Clear Search it will redirecting to main search not staying on current search page can you please give me a sol for that.
