### ISSUE TITLE
Bash "ShellShock" Injection 

### ISSUE THREAD

**Issue by Renforcer** [activerecord-hackery/ransack#1508]
I have implemented the ranksack for the application but when i do the Subgraph Vega scan , it shows the following error, i suspect that the ranksack gem is not entirely safe even i added all the search params to be strong params.
Could anybody have a look at it and see if it needed to be fixed?
![image](https://github.com/user-attachments/assets/6def7bf4-81f8-4789-9964-b2c1ae20e480)

**Comment by scarroll32** [comment]
Can you demonstrate what the vulnerability is?
