### ISSUE TITLE
Does Ransack support the same polymorhpic belongs_to associations in searches as MetaSearch does?

### ISSUE THREAD

**Issue by gladgit** [activerecord-hackery/ransack#152]
I am migrating from the MetaSearch gem to the Ransack gem for an upgrade to Rails 3.1 and I am having problems with my searches on polymorphic associations. The existing MetaSearch syntax isn't working for Ransack, but I couldn't find any documentation mentioning any syntax changes. Or whether this feature is supported in Ransack.

For example, from the MetaSearch github page, given the following classes:

```
class Article < ActiveRecord::Base
  has_many :comments, :as => :commentable
end

class Post < ActiveRecord::Base
  has_many :comments, :as => :commentable
end

class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  validates_presence_of :body
end
```

you can create a search field in your form like this:

```
<%= f.text_field :commentable_article_type_body_contains %>
```

I am using this type of syntax, which works perfectly in MetaSearch, but with Ransack my application is throwing an exception when the query parameter contains this field. The exception is:

```
ActiveRecord::EagerLoadPolymorphicError (Can not eagerly load the polymorphic association :ownable)
```

How do I search on polymorphic associations in Ransack?

**Comment by wkoffel** [comment]
May be addressed [here](https://github.com/activerecord-hackery/ransack/wiki/Polymorphic-searches)
