### ISSUE TITLE
Polymorphic searches broken by 4.0 allowlist

### ISSUE THREAD

**Issue by budu** [activerecord-hackery/ransack#1527]
Polymorphic searches as documented here:

https://activerecord-hackery.github.io/ransack/going-further/polymorphic-search/

don't work since 4.0. Even after adding the polymorphic keys to the allowed attributes, I get:

```
undefined method `type' for nil:NilClass (NoMethodError)

      attr.klass.columns.find { |column| column.name == name }.type
                                                              ^^^^^
```

I've tried to patch the `type_for` method but then Ransack tries to use the polymorphic attribute as a column.

**Comment by budu** [comment]
Scratch that, I messed up the my allow lists.

**Comment by justrenato** [comment]
> Scratch that, I messed up the my allow lists.

I'm getting this error to ;-; how do u find a solution?

**Comment by budu** [comment]
In my case, this issue was caused by wrong authorization of ransackable attributes.

The faulty code was defined as an attribute which worked fine for a `belongs_to` association (ransack could use the foreign key) but wasn't working for `has_one` associations. In that case, ransack thinks the attribute is a column, it tries to find the type of that column and fails with a relatively obscure error message because there's no such column.

The solution is to change the attribute's authorization to be an association and add the id in the corresponding model.

For example:

```ruby
class Supplier < ApplicationRecord
  has_one :account

  # Problem: This only works for belongs_to associations where account_id
  # is a actual database column
  def ransackable_attributes(auth_object = nil)
    %w[account_id]
  end

  # Solution: For has_one associations, authorize the association itself
  def ransackable_associations(auth_object = nil)
    %w[account]
  end
end

class Account < ApplicationRecord
  # Then authorize the specific attributes you want searchable
  def ransackable_attributes(auth_object = nil)
    %w[id]
  end
end
```

If your ransack code is complex and you can't find the faulty attribute, you can always debug the `Ransack::Adapters::ActiveRecord::Context#type_for` method from the ransack gem itself.
