### ISSUE TITLE
Ransack localisation fails

### ISSUE THREAD

**Issue by rutgerg** [activerecord-hackery/ransack#162]
My  app uses localisation so urls have eg ?locale=en in the url. I implemented the Ransack gem. Searching is great but the locale parameter is lost in the search. It looks like it is ignoring the before_filter :set_locale and the default_url_options. Any help is very much appreciated.

**Comment by pietere** [comment]
FYI, I fixed it this way

      = search_form_for @q do |f|
        = f.text_field :name
        = hidden_field_tag :lang, params[:lang]
        = f.submit t('.search')
