### ISSUE TITLE
Displaying non-empty defaults for sort drop-downs?

### ISSUE THREAD

**Issue by jlstr** [activerecord-hackery/ransack#163]
Hello guys!

Sorting a model works very well via: build_sort, But is there a way to change the defaults displayed for the drop downs that ransack generates? The defaults are No-Field, No-Option Selected. Can I change that to something different to be displayed when the page loads?

This Question has more details about what I'm trying to accomplish:

http://stackoverflow.com/questions/13369909/how-to-set-defaults-for-ransack-sorting

Thanks in advance!

**Comment by seanfcarroll** [comment]
Closed
