### ISSUE TITLE
Searching full_name with ransack (first_name & last_name)

### ISSUE THREAD

**Issue by yigitbacakoglu** [activerecord-hackery/ransack#166]
How can i concat first_name and last_name to search with full name using ransack? @radar 

Thanks

**Comment by codebycliff** [comment]
If anyone gets the following error: 

Unsupported argument type: String. Construct an Arel node instead.

The solution is to build a quoted node: 

```ruby
  ransacker :full_name do |parent|
    Arel::Nodes::NamedFunction.new('CONCAT_WS', [
      Arel::Nodes.build_quoted(' '), parent.table[:first_name], parent.table[:last_name]
    ])
  end
```
