### ISSUE TITLE
sort_link with association count

### ISSUE THREAD

**Issue by jwg2s** [activerecord-hackery/ransack#183]
Let's say I have two objects that are associated, such as product has_many categories.  If I was looking at a list of categories, and wanted to sort by the the number of products within each categories, how would I do that?

I've tried looking into the sort_link source code but this seems like it's common enough someone might have come up with a clever solution already?  Had seen a few examples using scopes but had no luck with that.

**Comment by meliborn** [comment]
Seems it ignore counter_cache. I have Company model that has_many :real_estates
And when I do 
```
= sort_link(@q, :real_estates_count, {default_order: :desc}, {remote: true, class: 'dropdown-item'}) do
```
it bring LEFT OUTER JOIN and take a lot of time with many records.
