### ISSUE TITLE
Rails 3.1.0, ransack 0.5.6, and will_paginate 3.0.0 not happy

### ISSUE THREAD

**Issue by spovich** [activerecord-hackery/ransack#21]
Using ruby 1.9.2 p290, rails 3.1.0, ransack 0.5.6 and will_paginate 3.0.0 (also tried latest git), will blow up when you have > 1 page of results.  Everything is fine with only 1 page of results.  I have no idea whether this is a ransack or will_paginate issue or just the combination of both.

Perhaps I'm doing this wrong, so let me know if this looks ok.

In my controller:

def index
  @search = State.paginate(:page => params[:page]).search(params[:q])
  @search.sorts = 'name asc' if @search.sorts.empty?
  @states = @search.result
end

This line in my view:

= will_paginate @states

will produce::

 undefined method `-' for nil:NilClass
 /home/www/cats/cats/shared/bundle/ruby/1.9.1/bundler/gems/will_paginate-e1f4af74351f/lib/will_paginate/view_helpers/link_renderer_base.rb:30:in`windowed_page_numbers'

If I remove the ransack, pagination works fine.  Will paginate docs say that it return an active record relation which should be chainable, but I think something that will_paginate is adding is getting clobbered by ransack.

I think the current_page value in windowed_page_numbers (and maybe some other values) are being overwritten thus the error subtracting from nil.  Here is the will_paginate code: https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/view_helpers/link_renderer_base.rb

Thanks for any help on this!

**Comment by frandugo** [comment]
How can I do so that the results initially passed are 0, until the search is done?
