### ISSUE TITLE
Passing a empty array to predicate IN

### ISSUE THREAD

**Issue by ricardokrieg** [activerecord-hackery/ransack#212]
It would be good if when we pass a empty array to the predicate IN, the predicate was turned in the predicate NULL.

A example:

Currently the search:

```
User.search(age_in: []).result.to_sql
```

results on this:

```
"SELECT `users`.* FROM `users` "
```

Why not it results on this:

```
"SELECT `users`.* FROM `users`  WHERE `users`.`age` IS NULL"
```

That is the equivalent for calling:

```
User.search(age_null: 1).result.to_sql
```

After all, if I have a list of ages to choose from and this list is empty, why should I receive all the ages?

**Comment by tyronewilson** [comment]
thanks @ricardokrieg. great lifehack!

**Comment by interu** [comment]
My approach.
```
User.where(id: []).search(age_in: []).result.to_sql
```
