### ISSUE TITLE
`search` method name conflict with solr 

### ISSUE THREAD

**Issue by zhouguangming** [activerecord-hackery/ransack#214]
I have a project need to use solr as my search engine,  it will define a `search` method to my model as well as ransack does. How to solve it with little pain.

**Comment by mklemme** [comment]
Just posting in case anyone else needs a solution since I was running into the same problem:

Ransack makes `.ransack` available and Solr has `.solr_search`

**Comment by jonatack** [comment]
I think it's fairly-well documented in the README:

[https://github.com/activerecord-hackery/ransack#ransack-search-method](https://github.com/activerecord-hackery/ransack#ransack-search-method)

**Comment by mklemme** [comment]
@jonatack Right! This was a problem with conflicts with Solr & Ransack. I use the `.ransack` and `.solr_search` instead of `.search` just to be on the safer side.
