### ISSUE TITLE
serching records in between start date and end date

### ISSUE THREAD

**Issue by shrikant-ror** [activerecord-hackery/ransack#219]
i am searching records in between start_date and end_date but it gives blank  for this i am using search predicates 

rooms controller  
def guest_search 
  @search = Room.search(params[:q]).result.to_sql
  @roome = @search.result(:distinct => true)
  @room= @roome.where("status IS ?", true).order("room_type_id desc")
 end 

guest_serch.rb
<%= search_form_for @search, url: guest_search_rooms_path, html: {:method =>:post} do |f| %>
  <%= f.label :start_date_eq , "Start Date"%>  
  <%= f.text_field :start_date_eq, class: 'release_date' %>   

  <%=f.label :end_date_eq, "End Date" %>  
  <%= f.text_field :end_date_lteq, class: 'release_date' %> 
<%= f.submit "search" %>
<%end%>

how can do this

**Comment by JoshuaNovak919** [comment]
There seems to be an issue with using `end_date`. I can use `start_date_gteq` or `start_date_lteq` just fine, but nothing works with `end_date`. If I try `end_date_lteq`, `end_date_gteq`, or even `end_date_eq` it won't work. The date gets removed from the search field in the form as well. Anyone know a work around or why this happens?

**Note:** start_date and end_date are both Date fields in my model.

**Comment by JoshuaNovak919** [comment]
Scratch that. If anyone else has this issue. Add the `american_date` gem. Seems to be an issue with ruby and formatting dates in the m/d/Y format.

**Comment by seanfcarroll** [comment]
Thanks for the information @JoshuaNovak919
