### ISSUE TITLE
Case Insesitive Searches

### ISSUE THREAD

**Issue by leequarella** [activerecord-hackery/ransack#225]
In test, working with the mysql2 gem and a default mysql setup, the ransack gem is returning all my searches via insensitive match (this is good, I like this, I'd like to keep doing this).  When I switch over to an RDS instance of mysql, however, all searching then requires case sensitive matches.  This is using `Model.search`.

Am I missing something here?  Where has my brain led me astray?

**Comment by Steamcow** [comment]
+1
