### ISSUE TITLE
Unary operations do not work in advance mode

### ISSUE THREAD

**Issue by nagyt234** [activerecord-hackery/ransack#249]
None of the unary operation (predicate) work in advance mode. Not even on the ransack demo.

If I select 'true', 'false', 'is present', 'is blank', 'is null' or 'is not null' the SQL contains no where clause and the condition disapperas, i.e. ransack treats the condition invalid.

I've found a silly workaround. If I write 'true' into the value field, it works.

**Comment by seanfcarroll** [comment]
Closed
