### ISSUE TITLE
There are a many useless items on  the predicate list

### ISSUE THREAD

**Issue by nagyt234** [activerecord-hackery/ransack#250]
This great gem would be a little better if the predicate list would be shorter.

The following conditions are quite useless:

```
equals all:                   an attribute can not be equal to two or more different values
not equal to any:             filters nothing if two values are different
less than any:                the user is able perhaps to enter the minimum value to look for
less than all:                similar to the previous one
less than or equal to any:    same as the previous ones
less than or equal to all:    same as the previous ones
greater than any:             same as the previous ones
greater than all:             same as the previous ones
greater than or equal to any: same as the previous ones
greater than or equal to all: same as the previous ones
in any:                       the same as 'in'
in all:                       an attribute can not be equal to two or more different values
not in any:                   filters nothing if two values are different
not in all:                   same as 'not in'
starts with all:              an attribute can not be started with two or more different values
doesn't starts with any:      filters nothing if two values are different
ends with all:                an attribute can not be ended with two or more different values
doesn't ends with any:        filters nothing if two values are different
```

Summarized:
- Some predicates shouldn't have compounded versions and if more than one values passed they should be "and"-ed: not equal, less than, greater than, less then or equal, greater than or equal, doesn't starts with, doesn't ends with.
- Some predicates shouldn't have compounded versions and if more than one values passed they should be "or"-ed: equal, starts with, ends with.
- Some predicates shouldn't have compounded versions at all: in. not in.

This changes would increase the value of this gem. Thx.

**Comment by driehuis** [comment]
If the list of predicates bothers you, you can trim the list, either to a specific list using
```
<%= f.predicate_select only: %i(cont not_cont eq not_eq blank null) %>
```
or to a list without the "any/all" variants with
```
<%= f.predicate_select compounds: false %>
```
This info is in the Wiki, but a Google search for "ransack useless predicates" turns up this issue, so I thought I'd make it clear that while intentional, the long list is not unavoidable.
