### ISSUE TITLE
How to sort by field from joined table?

### ISSUE THREAD

**Issue by sigmaray** [activerecord-hackery/ransack#254]
Here is connection between Lesson and User written in lesson.rb:

``` ruby
has_many :user_lessons
has_many :users, through: :user_lessons
```

Here is code which I have in my controller:

``` ruby
@lessons_search = current_user.lessons.search(params[:q])
if @lessons_search.sorts.empty?
  @lessons_search.sorts = 'created_at desc'
end
@lessons = @lessons_search.result.page(params[:page])
```

Code generates this query. Query is ok.

``` sql
SELECT "lessons".* FROM "lessons" INNER JOIN "user_lessons" ON "lessons"."id" = "user_lessons"."lesson_id" WHERE "user_lessons"."user_id" = 4 ORDER BY "lessons"."created_at" DESC LIMIT 24 OFFSET 0
```

I have task to change this functionality. New sorting must be made by user_lessons.created_at field. So I change code in my controller:

``` ruby
@lessons_search = current_user.lessons.search(params[:q])
if @lessons_search.sorts.empty?
  @lessons_search.sorts = 'user_lessons_created_at desc' # <-- this line is changed
end
@lessons = @lessons_search.result.page(params[:page])
```

And now this query is generated:

``` sql
SELECT "lessons".* FROM "lessons" LEFT OUTER JOIN "user_lessons" "user_lessons_lessons" ON "user_lessons_lessons"."lesson_id" = "lessons"."id" INNER JOIN "user_lessons" ON "lessons"."id" = "user_lessons"."lesson_id" WHERE "user_lessons"."user_id" = 4 ORDER BY "user_lessons_lessons"."created_at" DESC LIMIT 24 OFFSET 0
```

With new code app is not working as supposed to work.
How sorting should be made when I want to sort by field from table which is joined to original model?

**Comment by woto** [comment]
Adding `select` helped me. My working code: `@messages = @messages.select('messages.*, devices.*')` BTW, wondering if there is there a 'magic' method which could do it for me.

**Comment by woto** [comment]
Adding `select` helped me. My working code: `@messages = @messages.select('messages.*, devices.*')` BTW, wondering if there is there a 'magic' method which could do it for me. And in some cases it also nececcary to add `includes` and `references`
