### ISSUE TITLE
How to persist ransack gem searching parameters in rails

### ISSUE THREAD

**Issue by rakeshostwal** [activerecord-hackery/ransack#265]
I'm using ransack gem for searching users based on their company and active/inactive parameter. This works fantastic when used alone. but i want to make use of both simultaniously. for example if i select company first and then select active/inacitve user then company name should persist.

Also is there facility in ransack to keep both values persisted when i click back or agian on users.

**Comment by BKSpurgeon** [comment]
@waiting-for-dev thank you - would you also know how one can clear all search parameters at the click of a button?

**Comment by waiting-for-dev** [comment]
@BKSpurgeon In the example passing `clear=true` as param will clean search parameters

**Comment by richardrails** [comment]
I have made the gem for this:
https://github.com/richardrails/ransack_memory

**Comment by seanfcarroll** [comment]
@richardrails great effort! Feel free to do a PR on the Ransack README to point to your gem.
