### ISSUE TITLE
How to search for hstore attributes?

### ISSUE THREAD

**Issue by manoj2411** [activerecord-hackery/ransack#267]

**Comment by kogre** [comment]
I was unable to get this to work in Rails 4.2 due to some changes in Arel.
Wrapping the value in a `build_quoted` call did the trick, though.

Found out through this ticket: https://github.com/rails/arel/issues/323

Here is the updated example:
```
class Foo < ActiveRecord::Base
  ransacker :link_type do |parent|    
    Arel::Nodes::InfixOperation.new('->', parent.table[:properties], Arel::Nodes.build_quoted('link_type'))
  end
end
```

If anyone can confirm the same issue (and working solution), we should update the wiki.

**Comment by jonatack** [comment]
Hi @kogre, thanks for the heads up!

In #490, @JanStevens just confirmed a few days ago that he needed to add `build_quoted` with Arel 6 for another ransacker example in the wiki (the one that searches on a full name combined from first name and last name attributes). I updated the wiki with his findings.

Please do go ahead and update the wiki with your example as well in a similar way:  Leaving the original code example and adding the new one just below with an explanation.

**Comment by kogre** [comment]
Ok, I've updated the wiki.

**Comment by jonatack** [comment]
Thank you!

**Comment by dinshaw** [comment]
I needed this to work with dynamic hstore keys. I ended up using `instance_exec` to dynamically create the `ransackers` every time i hit the search form. It works for my purposes, and may be helpful to someone else, but I'm sure it's not ideal.

Case is a hstore column named `:categories` and I want select lists for every category.
```ruby
