### ISSUE TITLE
Sql server don't found table

### ISSUE THREAD

**Issue by marcelo-marqueti-movile** [activerecord-hackery/ransack#276]
Hi,

I trying to use the ransack with sql server and when I send some parameter at :q we receive the error table not found.

If I don't send parameters, they found the table correct.

Success:
@q = DailyIndicator.search()
@count = @q.result.count
=> 2111

Error:
@q = DailyIndicator.search({"name_cont" => "apps"})
@count = @q.result.count

<code>RuntimeError: No table named [DATABASE].[dbo].[TABLENAME] exists
    from /Users/marcelomarqueti/.rvm/gems/ruby-1.9.3-p194/gems/ransack-1.0.0/lib/ransack/adapters/active_record/3.2/context.rb:28:in `type_for'
    from /Users/marcelomarqueti/.rvm/gems/ruby-1.9.3-p194/gems/ransack-1.0.0/lib/ransack/nodes/attribute.rb:29:in`type'</code>

Enviroments

Ruby 1.9.3
Rails 3.2.13
Ransack 1.0.0
activerecord-sqlserver-adapter 3.2.12
tiny_tds 0.6.1
Freetds 0.91

**Comment by seanfcarroll** [comment]
Closing. Please re-open with a failing repo / test if still needed. 

Where could we test easily against SQL Server?

**Comment by kwerle** [comment]
> Where could we test easily against SQL Server?

I *highly* recommend using the newish docker sqlserver image: 
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-docker
