### ISSUE TITLE
sort_link with more than one column and associations

### ISSUE THREAD

**Issue by elfassy** [activerecord-hackery/ransack#277]
Example:

``` ruby
= sort_link @q, :name_and_salary
```

and

``` ruby
= sort_link @q, :user_name_and_user_salary
```

should this work already? 
Thanks

**Comment by robinbortlik** [comment]
I was able to achieve this functionality with this code.

```ruby
#                          filter name                    order option
= sort_link(@search, 'physician_display_name', ['physician_display_name', 'start asc'], 'Behandler')
```

In this case the physician is relation and start is attribute of 'event' object.

**Comment by aruprakshit** [comment]
Good related link [link](http://projectidealism.com/posts/2015/1/12/three-ways-you-can-bend-the-ransack-gem-to-your-liking)

**Comment by yenshirak** [comment]
@robinbortlik thanks

**Comment by ducnguyenhuy** [comment]
Hi guys,

I have tried your suggestion but was not successful. I'm being on Products list, and each Product has relation with Doctor. I'm showing Doctor Name (first_name + last_name) as a column header. For now, I want that when user click on header Doctor Name, Products list should sort first_name by specifying the sort direction and last_name ascending. Below is my code
`<%= sort_link(@search, 'doctor_first_name', ['doctor_first_name', 'doctor_last_name asc'], 'Doctor Name') %>`

I have checked the log and seen that it's only ordering by doctor_first_name, not doctor_last_name.
Do you guys know how to obtain that?

Thanks.

**Comment by robinbortlik** [comment]
@ddomingues I think, the passed attribute name is wrong. It should not be composed from ```object_name_attribute_name```. The ```attribute_name``` should be enough. Add the ```object_name``` just in case, that you are sorting and filtering by relation, otherwise use just ```attribute_name```.

So the code should look like this.
```ruby
<%= sort_link(@search, 'first_name', ['first_name', 'last_name asc'], 'Doctor Name') %>
```

Also, try to set ```config.ignore_unknown_conditions = true```. Here is more info https://github.com/activerecord-hackery/ransack/wiki/Configuration .
Ransack usually just omit search condition when the query is composed wrong, which is not much helpful in development.

**Comment by ducnguyenhuy** [comment]
@robinbortlik: Thanks for your help. Yes, I'm sorting by relation, so I added `object_name`. Have you even used the sorting by relation? And does it works?

I will try to set `config.ignore_unknown_conditions` to `false` and let you know if I see anythings.
