### ISSUE TITLE
search by column of Array type in PostgreSQL

### ISSUE THREAD

**Issue by rilian** [activerecord-hackery/ransack#279]
I have a postgres database and a column of `array` type

``` ruby
change_table :users do |t|
  t.string :offer, array: true
end
```

I'm trying to search user with a `ransack (1.0.0)` and semantic form (formtastic) which is managed by a helper from here https://github.com/ernie/ransack/issues/31

``` ruby
= f.input :offer_in, as: :check_boxes, collection: User::OFFERS
```

So when i run the search it generates an URI like 

```
http://0.0.0.0:3000/users?q[offer_in][]=cookie&q[offer_in][]=pie
```

And with controller code

``` ruby
@q = User.search(params[:q])
@users = @q.result
```

I get database query

``` sql
SELECT "users".* FROM "users" 
  WHERE "users"."offer" IN ('cookie', 'pie')
```

which returns an error

```
PG::InvalidTextRepresentation: ERROR:  array value must start with "{" or dimension information
LINE 1: ..."users".* FROM "users"  WHERE "users"."offer" IN ('cookie', ...
```

**Comment by lehug** [comment]
what can I do to support array with postgresql? Thanks

**Comment by jpmermoz** [comment]
Same issue here

**Comment by vanboom** [comment]
See #321, requires the `postgres_ext` gem, but works like a champ.

**Comment by FX-HAO** [comment]
@vanboom `postgres_ext` doesn't support Rails 5. So how to achieve this in Rails 5?
