### ISSUE TITLE
No Ransack::Search object was provided to search_form_for!

### ISSUE THREAD

**Issue by alopes** [activerecord-hackery/ransack#3]
Hi Ernie,

I'm trying to move a search form into my website header using a partial. It works ok unless I switch to another controller while browsing the site. Do I need to pass anything extra into my search_form_for in order to render outside its related controller? As you can see I'm fairly new to rails. 

Thanks for your help.

ArgumentError in Videos#show

Showing /Users/x/Documents/Development/webdev/x/app/views/application/_search.html.erb where line #2 raised:

No Ransack::Search object was provided to search_form_for!
Extracted source (around line #2):

1: <div id="search">
2:  <%= search_form_for @q do |f| %>
3:    <%= f.label :title_cont %>
4:    <%= f.text_field :title_cont %>
5: 
Trace of template inclusion: app/views/application/_header.html.erb, app/views/layouts/application.html.erb

**Comment by merlin2049er** [comment]
Very nice!  This is what I needed as well!  Now how do I keep the bootstrap styling for the search box?
