### ISSUE TITLE
Passing arguments to ransackers

### ISSUE THREAD

**Issue by zethix** [activerecord-hackery/ransack#315]
Is there any way to pass additional arguments to ransacker? I would like to do for example:

```
ransacker args: [arg1] do |parent|
  Arel::Nodes::SqlLiteral.new("tests.field_1 = #{arg1} AND tests.field_2")
end
```

**Comment by mateuszbialowas** [comment]
@zethix How did you resolve your case? How did you pass user params into a custom ransacker?

**Comment by graywh** [comment]
ransackable_scopes is probably what you need
