### ISSUE TITLE
Cannot visit Range

### ISSUE THREAD

**Issue by polimorfico** [activerecord-hackery/ransack#32]
Hi,

I'm trying to use a custom predicate, but I get always the same error.

Ransack.configure do |config|
  config.add_predicate 'btw', 
    :arel_predicate => 'in',
    :formatter => proc {|v| Range.new(Date.today, Date.today+1)}
end

Thanks,
Carlos

**Comment by Pavling** [comment]
Thanks for the hints. Here's a slightly terser way (without the monkey patch of the `:wants_array` attribute:

```
Ransack.configure do |config|
  config.add_predicate 'btw', 
    :arel_predicate => 'in',
    :formatter => proc {|v| Range.new(Date.today, Date.today+1)}

  Ransack::predicates['btw'].instance_variable_set('@wants_array', false)
end
```

I'm just working on a PR to allow the same functionality to be achieved by passing `:wants_array => false` in the options, like this:

```
Ransack.configure do |config|
  config.add_predicate 'btw', 
    :wants_array => false,
    :arel_predicate => 'in',
    :formatter => proc {|v| Range.new(Date.today, Date.today+1)}
end
```
