### ISSUE TITLE
search only year in a date input field.

### ISSUE THREAD

**Issue by ghost** [activerecord-hackery/ransack#34]
With ransack I can search for a date in a date input field, so I can search for example for 2011-02-02. How can I search only for year?

**Comment by bonyiii** [comment]
The wiki now has an example for this: https://github.com/activerecord-hackery/ransack/wiki/Using-Ransackers

In my view i have this search:
```ruby
    f.text_field :version_created_at_gteq
    f.text_field :version_created_at_lteq
```
in the model i added this:
```ruby   
   ransacker :created_at, type: :date do
     Arel.sql('date(versions.created_at)')
   end
```

**Comment by jonatack** [comment]
@bonyiii thanks, which example is it?

I see a new one (#7) that could use better documentation concerning the what attributes are and the relation between them.
