### ISSUE TITLE
Documentation for Ransacker

### ISSUE THREAD

**Issue by svoop** [activerecord-hackery/ransack#345]
The Ransacker class is IMHO a crutial part of Ransack, however, due to the lack of documentation and examples, it's both a time consuming and frustrating task to work with Ransacker. Fortunately, not too many people had to deal with them so far.

This is going to change because ActiveAdmin (master branch) has switched from meta_search to Ransack. This means all existing Rails 3.2 applications with ActiveAdmin backend must port their custom filters to Ransack in order to update to Rails 4. The old approach with scopes/search_method is no longer possible... enter Ransacker.

It would be very helpful to have some documentation and examples for Ransacker. I'd even throw in a few bucks, say $50 or so. Anybody else willing to tip as well?

---

To illustrate, here's an example from a real application. First the Rails 3.2 code which uses meta_search. The `search_in_all_translated` method searches all attributes which hold translations in a Postgres HSTORE structure. ActiveAdmin uses Formtastic to render forms:

```
# app/models/user.rb
scope :full_text_contains, ->(search) { search_in_all_translated(search) }
search_method :full_text_contains

# app/admin/users.rb (ActiveAdmin)
filter :full_text_contains,
  label: 'full text search'
```

And here the port to Ransacker ready for Rails 4:

```
# app/models/user.rb
ransacker :full_text, formatter: ->(search) {
  ids = User.search_in_all_translated(search).map(&:id)
  ids = ids.any? ? ids : nil
} do |parent|
  parent.table[:id]
end

# app/admin/users.rb (ActiveAdmin)
filter :full_text_in,
  label: 'full text search',
  as: :string
```

The search itself works, but the value in the search form input is not correct after the search [as described on Stackoverflow](http://stackoverflow.com/questions/22473391/custom-search-with-ransacker):

Before:

![dhuok](https://f.cloud.github.com/assets/7255/2447816/706cac90-ae9d-11e3-9fb0-4f657d7c764e.png)

After:

![o53uy](https://f.cloud.github.com/assets/7255/2447819/7858c47a-ae9d-11e3-8565-01adcbfeec02.png)

Looking at "my" Ransacker, it feels wrong, ill-used. But without documentation and maybe some examples, I'm lost - and apparently, I'm not the only one.

**Comment by Gabriel-Inacio** [comment]
Thanks great job, but not work in .json?
