### ISSUE TITLE
sort_link method only respects search_key, not search state

### ISSUE THREAD

**Issue by ressu** [activerecord-hackery/ransack#346]
The sort_link method is called with search object, but still it internally queries the parameters for sort_link from ```params[search.context.search_key]```.

This causes problems if one wants to pass default search values to the search instance. Those default values aren't reflected in params so the sort_link doesn't actually reflect the current search state.

**Comment by panyamin** [comment]
Hello,

is `sort_link` should reflect `default_scope` too?

**Comment by jonatack** [comment]
Closing this issue for the moment as stalled.

@panyamin please see the ReadMe and the Wiki :heart:

**Comment by panyamin** [comment]
Oh my! Well, I can see that I misread. Sorry!

Btw, It would be interesting/possible to reflect `default_scope` to build default search params?

**Comment by luislezcair** [comment]
Is there any update on this?
