### ISSUE TITLE
not_null predicate not working

### ISSUE THREAD

**Issue by johnvh** [activerecord-hackery/ransack#359]
Using version 1.2.2 advanced mode:

``` ruby
search = Entry.ransack({
  'c' => {
    '0' => {'a' => ['body'], 'p' => 'not_null', 'v' => []},
  }
})

puts search.result.to_sql
# > SELECT `entries`.* FROM `entries`
```

Unless I'm missing something, the query should contain a WHERE. 

Using the contains predicate -  `'p' => 'cont', 'v' => ['with']` - works as expected.

**Comment by Timmitry** [comment]
A decade later, yet I had the same problem. For future readers: A value needs to be provided, which should be a boolean-like truthy value (1, "1", true, "true"). For example "5" does not work and will lead to the condition being ignored!

When providing a falsey value, the condition seems to get inverted, so `'p' => 'not_null', 'v' => ['1']` does the same as `'p' => 'null', 'v' => ['0']`.
