### ISSUE TITLE
How to use predicate_select without advanced form pattern?

### ISSUE THREAD

**Issue by hillmandj** [activerecord-hackery/ransack#364]
Hey everyone!

I have had issues trying to use predicate_select in 'Simple Mode' when using Ransack. My initial goal was to have something like:

```
= search_form_for @search, url: admin_products_new_index_path do |f|
  = f.label :sku, 'Sku: '
  = f.predicate_select
  = f.text_field :sku

```

Where predicate_select would essentially determine the Arel predicate that was used in the query. The above, obviously, does not work. I have had no issues using the pattern that everyone else seems to be using:

In the view:

```
    = search_form_for @search, url: admin_products_new_index_path do |f|
      = f.condition_fields do |c|
        = render :partial => 'condition_fields', :locals => {:f => c }
      %p
        = link_to_add_fields 'Add Conditions', f, :condition
      .form-footer
      = f.submit 'Search',:name => nil, :class => 'search-submit'
      = link_to t("reset"), admin_products_new_index_path, :class => 'reset'
```

View partial: 

```
.field
  = f.attribute_fields do |a|
    = a.attribute_select :associations => [:variants]
  = f.predicate_select :only => [:cont, :not_cont, :eq, :not_eq, :blank, :null, :not_null]
  = f.value_fields do |v|
    = v.text_field :value
  = link_to 'remove', '#', :class => 'remove_fields'
```

However, this is not exactly what I want. How would you use predicate_select without using this pattern/an attribute select?

**Comment by Sprachprofi** [comment]
I had the same problem. Here's some code that the next person can drop into their project:

Define all your predicate selectors as select_tags (not f.select!) with the name of the attribute plus _predicate. Have them all call changePredicate(this) on change:
`<%= select_tag :title_predicate, options_for_select([['contains', 'cont'], ['is', 'eq'], ['starts_with', 'start'], ['ends_with', 'end']]), onchange: "changePredicate(this)" %>`

The function only needs to be defined once:
```
<script>    
  function changePredicate(selectBox) {    
    predicate = selectBox.value;    
    attribute = selectBox.name.replace('_predicate', '');    
    next_el = $(selectBox).next();    
    next_el.attr('name', 'q[' + attribute + '_' + predicate + ']');    
  }    
</script>
```
