### ISSUE TITLE
has_many and negative predicates

### ISSUE THREAD

**Issue by Serpico84** [activerecord-hackery/ransack#381]
Is it possible somehow to use negative predicates like not_cont, not_in etc... on has_many associations?

Right now this doesn't seem to work in specific cases, for example in my application a User has_many Emails. What should i do if I want to find all users that do not have one or more "gmail.com" emails? (in other words, exclude from the results all users having at least a gmail.com address)

If i do a search like "q" => {:emails_address_not_cont => "gmail.com"}, this would exclude users that have ONLY gmail.com addresses, but will still include users with gmail.com emails if they have at least one email that's not gmail.com.

**Comment by adisos** [comment]
I added this scope to my `User` model:
```ruby
def self.without_tag_id id
  join_sql = <<-SQL
    LEFT OUTER JOIN
    taggings taggings_exclude
    ON (
      taggings_exclude.taggable_id = users.id
      AND taggings_exclude.taggable_type = 'User'
    )
  SQL
  join_sql = join_sql.squish
  having_sql = <<-SQL
    NOT (
      ? = ANY(
        ARRAY_REMOVE(
          ARRAY_AGG(taggings_exclude.tag_id),
          NULL
        )
      )
    )
  SQL
  having_sql = having_sql.squish

  joins(join_sql).group('users.id').having(having_sql, id)
end
```
Then also added this method:
```ruby
def self.ransackable_scopes(auth_object = nil)
  %i(without_tag_id)
end
```

And then I can use this:
```ruby
User.ransack({ without_tag_id: 5})
```

**Comment by avit** [comment]
I opened #645 to address this.
