### ISSUE TITLE
Ransacker with swapped predicate operand order

### ISSUE THREAD

**Issue by svoop** [activerecord-hackery/ransack#388]
I'm trying to build the following Postgres ARRAY query with Ransack, however, I believe Ransack (or AREL) don't feature this yet:

```
SELECT "projects".* FROM "projects"  WHERE 'de' = ANY("projects"."locales")
```

The following ransacker brings my only this far:

```
ransacker :any_locale do |parent|
  Arel::Nodes::NamedFunction.new('ANY', [Project.arel_table[:locales]])
end

Project.search(:any_locale => 'de').result.to_sql
# => SELECT "projects".* FROM "projects"  WHERE ANY("projects"."locales") = 'de'
```

Unfortunately, the order is relevant, so the `ANY` has to be after the predicate `=` for this to work.

As a side note: The same result could be produced with this query, but I know even less how to ransack this:

```
SELECT "projects".* FROM projects WHERE locales @> ARRAY['de'::varchar]
```

**Comment by MrKirat** [comment]
Hello @svoop!
I see this issue is pretty old (10 years have passed, omg), but I've faced the same issue recently. Have you managed to solve it?

**Comment by hugolepetit** [comment]
@svoop Stumbled on this, saved my day ❤️
