### ISSUE TITLE
Ignore #sorts

### ISSUE THREAD

**Issue by bjensen** [activerecord-hackery/ransack#391]
In my effort of updating to Rails 4 I am switching out meta_search with ransack. I came across this issue of sort being ignored:

Normal query in irb:

```
Stay.joins(student: :profile).order("profiles.name asc")
  SELECT `stays`.* FROM `stays`
  INNER JOIN `users` ON `users`.`id` = `stays`.`student_id`
  AND `users`.`type` IN ('Student')
  INNER JOIN `profiles` ON `profiles`.`user_id` = `users`.`id`
  ORDER BY profiles.name asc
```

Ransack query

```
search = Stay.joins(student: :profile).search
# => Ransack::Search<class: Stay, base: Grouping <combinator: and>>

search.sorts = "profiles.name asc"
# => "profiles.name asc"

search.result 
# =>
  SELECT `stays`.* FROM `stays`
  INNER JOIN `users` ON `users`.`id` = `stays`.`student_id`
  AND `users`.`type` IN ('Student')
  INNER JOIN `profiles` ON `profiles`.`user_id` = `users`.`id`
```

Notice the order clause is not being appended

**Comment by robinbortlik** [comment]
Hi I think, issue is that when you want to sort by relation you have to use convention model_attribute and not model.attribute . See this issue https://github.com/activerecord-hackery/ransack/issues/13

**Comment by jonatack** [comment]
It seems to me that assocations should currently be specified as location.name in the sort link and location_name pretty much everywhere else (search field, controller, rails console, etc.)
