### ISSUE TITLE
Move rails 4.0 compatibility support into its own files like the other versions

### ISSUE THREAD

**Issue by avit** [activerecord-hackery/ransack#416]
I'd like to clean up the adapters directory to remove the version conditionals from the latest version. Does it make sense to move 4.0 compatibility out to a separate file like the others now? It's getting messy.

It could end up like the 3.x series:

`adapters/active_record/context.rb` for latest 4.x requires `4.0/context.rb`

Another thought was to move everything into feature modules (by version) and just use the main context.rb adapter file to switch the inclusion of the right feature modules. Any thoughts?

**Comment by avit** [comment]
Oh my goodness I so want to dive in and do this after my recent adventures in this codebase again...

- [ ] Always load one base file, then load version compatibility files as overload
- [ ] Move Arelish/Visitory things out of Nodes classes (& somewhat from Context)
- [ ] Make different Visitors for different things instead of conditionals
- [ ] Restore sanity

Not sure when I'll ever have the time, but I might just make smaller attempts at this as I pick off other fixes with my drive-by pull requests.

**Comment by seanfcarroll** [comment]
@avit would be great to have your contributions ... any progress on this?

**Comment by seanfcarroll** [comment]
If we can wait for EOF on Rails 4.2, I vote for removing the code from older versions completely, or leaving available on a branch but removed from master.

https://stackoverflow.com/questions/43050213/ruby-on-rails-4-2-end-of-life

**Comment by seanfcarroll** [comment]
Looks like this has been done. Issue closed.
