### ISSUE TITLE
sort_link on polymorphic association

### ISSUE THREAD

**Issue by glaucocustodio** [activerecord-hackery/ransack#421]
Hi guys, I am on Rails 4.1 (Ruby 2.1.2) and ransack branch: 'rails-4.1'.

I have this search field working as expected:
`xxxable_of_Ymodel_type_some_attr_gteq`

But when I try to sort by the same field:
`= sort_link(@q, :xxxable_of_Ymodel_type_some_attr`

I get this error: `uninitialized constant Model::Xxxable`

Sort link does not work with polymorphic association? Thank you.

**Comment by dipaktc** [comment]
How to sort_link with multiple polymorphic relationship ?

**Comment by seanfcarroll** [comment]
Closing as a workaround exists.
