### ISSUE TITLE
how to use custom (non-ransack) form fields in search_form_for?

### ISSUE THREAD

**Issue by JeanMertz** [activerecord-hackery/ransack#422]
I'm trying to add some form fields that should be ignored by ransack, but can't use the `text_field_tag` alternative, because I need the formatting provided by SimpleForm.

Is there any way to ignore specific fields in a form? Right now, any name that does not match `<database_column>_<predicate>` will result in the error:

```
undefined method `my_custom_event' for #<Ransack::Search:0x007fe7827b55e0>
```

**Comment by hieunguyentrung** [comment]
@JeanMertz Did you have solution ?
