### ISSUE TITLE
ransackable_scopes doesn't seem to work though an association

### ISSUE THREAD

**Issue by cotcomsol** [activerecord-hackery/ransack#423]
As an example I forked the ransack_demo app and added a scope to the Comment model, 'created_after'.  I can now use ransack to search the Comment model using this scope, but I can't search it via the User model:

Comment.search(:created_after=>'2014-01-01').result.to_sql
=> "SELECT \"comments\".\* FROM \"comments\"  WHERE (created_at>'2014-01-01')"

vs:

User.search(:comments_created_after=>'2014-01-01').result.to_sql
=> "SELECT \"users\".\* FROM \"users\" 

But normal searches across the association work fine:
User.search(:comments_body_cont=>'hi').result.to_sql
=> "SELECT \"users\".\* FROM \"users\" LEFT OUTER JOIN \"comments\" ON \"comments\".\"user_id\" = \"users\".\"id\" WHERE (\"comments\".\"body\" ILIKE '%hi%')"

The view pukes with:
undefined method `comments_created_since' for Ransack::Search<class: User, base: Grouping <combinator: and>>:Ransack::Search

My modified demo is at: https://github.com/cotcomsol/ransack_demo

**Comment by dmitry** [comment]
@jonatack @avit @cotcomsol have you found a solution to this issue?
