### ISSUE TITLE
Custom sort link like in meta-search?

### ISSUE THREAD

**Issue by hendricius** [activerecord-hackery/ransack#424]
GI would like to apply a custom scope for sorting by a specific column.

I found this in the `meta-search` doc: https://www.dropbox.com/s/o86o3t2w63r2sji/Screenshot%202014-09-01%2013.37.49.png?dl=0

Basically it allows you to add a `sort_link` like this:

`sort_link @q, :comment_due_date, "Due"`

Then internally it will use a scope in the model. Is this feature already supported? Is there a better way? Sorry, still can't 100% wrap my head around this.

Thanks!

```
class User
  scope :sort_by_comment_due_date_asc, -> {
    order("CASE WHEN editor_comment_due_date IS NULL THEN 0 ELSE 1 END DESC").
    order("editor_comment_due_date ASC")
  }
  scope :sort_by_comment_due_date_desc, -> {
    order("CASE WHEN editor_comment_due_date IS NULL THEN 0 ELSE 1 END DESC").
    order("editor_comment_due_date DESC")
  }
end

```

I found the code in the `search.rb` that seems to add the scopes:
https://github.com/activerecord-hackery/ransack/blob/28433f9707d0f1fa61b95e7277d39f5de4ff0e7a/lib/ransack/search.rb#L35

**Comment by kannans** [comment]
@jonatack Thank you!.  Some correction in the condition. 
```rb
@users, sort = @q.result, @q.sorts.first
@users = @users.order_by_due_date(sort.dir) if sort.name == 'editor_comment_due_date'
```

**Comment by jonatack** [comment]
Thanks @kannans for the catch. Corrected.

**Comment by jonatack** [comment]
Thanks @kannans for the catch! Corrected.
