### ISSUE TITLE
bug when sorting by association when using postresql with distinct(:true)

### ISSUE THREAD

**Issue by gotqn** [activerecord-hackery/ransack#429]
I know this is a known bug:
1. http://stackoverflow.com/questions/19748959/ransack-postgres-sort-on-column-from-associated-table-with-distinct-true
2. http://stackoverflow.com/questions/19910574/distinct-for-sorting-with-ransack

but is there a fix?

This code works:

```
def index
  @search = LogFile.search(params[:q])
  @log_files = @search.result(distinct: false).includes(:search_statistic).page(params[:page]).per(5)
end
```

This code does not:

```
def index
  @search = LogFile.search(params[:q])
  @log_files = @search.result(distinct: true).includes(:search_statistic).page(params[:page]).per(5)
end
```

Error:

```
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
```

**Comment by gurgelrenan** [comment]
Someone have tried this solution: http://stackoverflow.com/questions/19748959/ransack-postgres-sort-on-column-from-associated-table-with-distinct-true

Doesn't work for me :/ for while I will use the solution @jonatack sad.

**Comment by jonatack** [comment]
If by chance you're using Rails 3, try replacing `relation.distinct` with `relation.uniq`.

**Comment by mikel** [comment]
Perhaps solved by https://github.com/activerecord-hackery/ransack/pull/599 ?

**Comment by jatin-maropost** [comment]
> Well yes, it won't work if you call it before other methods expecting an ActiveRecord relation; call it at the end.
> 
> As per the README that I added yesterday:
> 
> ```ruby
> # or use `to_a.uniq` to remove duplicates (can also be done in the view):
>   @people = @q.result.includes(:articles).page(params[:page]).to_a.uniq
> ```
> 
> If you want it to happen as late as possible because `.to_a` triggers the database query, put it in your render partial collection call in your view.

Thanks this worked for me.
