### ISSUE TITLE
predicate present or true with null checkbox

### ISSUE THREAD

**Issue by kaluznyo** [activerecord-hackery/ransack#434]
Hi,

Before 1.4, i use check box with field_present or field_true. If the check box is not checked, no condition is add to request.

But since 1.4 if I use this, I get 'WHERE field != 1' when check box is not checked.

Seem to be related to this features #335.

What is the 'new' way to make this work again. No check -> ignore predicat.

**Comment by aselder** [comment]
@kaluznyo Don't know if you've seen this or not: http://stackoverflow.com/questions/27890997/ransack-return-records-with-boolean-attribute-both-true-and-false-with-checkbox

TL;DR include the `include_hidden: false` option

**Comment by aldosolis** [comment]
@kaluznyo I did the following:

f.check_box :field_true, {}, 1, nil 

nil is the value when is not checked. Did you find a simple way?
