### ISSUE TITLE
Polymorphic Association Issue. Does ransack support it?

### ISSUE THREAD

**Issue by llopez** [activerecord-hackery/ransack#436]
This is my code:

```ruby
class Comment
  belongs_to :commentable, polymorphic: true
end

class Video
  has_many :comments, as: :commentable
end

class Image
  has_many :comments, as: commentable
end
```

What I am doing:

```
Comment.search(commentable_title_eq: 'some title').result.to_sql
```

What I am getting:

NameError: uninitialized constant Comment::Commentable

If I change my code to:

```ruby
class Comment
  belongs_to :commentable, polymorphic: true, class_name: 'Video'
end
```
It works, but I am breaking the polymorphic association.

Can anyone help please?

Thanks

**Comment by avit** [comment]
Please try: `commentable_of_Video_type_title_eq`, see the wiki for details on [Polymorphic Searches][1].

[1]: https://github.com/activerecord-hackery/ransack/wiki/Polymorphic-searches

**Comment by dongli** [comment]
How would I know which type to search for when writing search form?

**Comment by m-abdurrehman** [comment]
@avit I have the same scenario but I not sure how deal with sorting. Kindly assist me.
I am getting `Polymorphic associations do not support computing the class.`

when I try something in view
= sort_link(@search, :licensee_of_Device_type_quantity, {} , {remote: true})

**Comment by Tashows** [comment]
> Please try: `commentable_of_Video_type_title_eq`, see the wiki for details on [Polymorphic Searches](https://github.com/activerecord-hackery/ransack/wiki/Polymorphic-searches).

What happens when the type you want to reference is namespaced? :cry:

**Comment by jeantristan** [comment]
My reference is namespaced. Have you find a solution?

**Comment by jeantristan** [comment]
> My reference is namespaced. Have you find a solution?

Just use Namespace:: in front
For example commentable_of_MyNameSpace::Video_type_title_eq

**Comment by stathoula** [comment]
> > My reference is namespaced. Have you find a solution?
> 
> Just use Namespace:: in front For example commentable_of_MyNameSpace::Video_type_title_eq

Just do not forget to quote it: `Model.ransack('commentable_of_MyNameSpace::Video_type_title_eq': 'some title').result`

**Comment by berti92** [comment]
> @avit I have the same scenario but I not sure how deal with sorting. Kindly assist me. I am getting `Polymorphic associations do not support computing the class.`
> 
> when I try something in view = sort_link(@search, :licensee_of_Device_type_quantity, {} , {remote: true})

I had the exact same problem. You forgot "_type" after the polymorphic class.

**Comment by EhtuCom** [comment]
> Please try: `commentable_of_Video_type_title_eq`, see the wiki for details on [Polymorphic Searches](https://github.com/activerecord-hackery/ransack/wiki/Polymorphic-searches).

Just for another example for a Form.Select:
`      <%= f.select :adable_of_Boat_type_manufacturer_id_eq,
          boats_get_CO_manufacturers,
          { include_blank: 'Select Manufacturer' },
          { class: 'form-select' } 
      %>`


And the boat_helper.rb contains the pluck function:
`def boats_get_CO_manufacturers
    return [] if current_organization.nil?

    Rails.cache.fetch('boats_get_CO_manufacturers', expires_in: 2.seconds) do
      current_organization.ads
        .where(adable_type: 'Boat')
        .joins("INNER JOIN boats ON ads.adable_id = boats.id")
        .joins("INNER JOIN manufacturers ON boats.manufacturer_id = manufacturers.id")
        .distinct
        .pluck('manufacturers.name', 'manufacturers.id' )
    end
  end`
