### ISSUE TITLE
How to add NULL LAST to sorts

### ISSUE THREAD

**Issue by justin808** [activerecord-hackery/ransack#443]
I need NULL results to go last.

This is simple to do in a SQL statement. Just list "NULL LAST" right after the order predicate.

Where is the right place to put this?

Also, in the code for evaluate, I don't think relation.except(:order) is necessary, as the reorder takes care of removing the old order.

``` ruby
        def evaluate(search, opts = {})
          viz = Visitor.new
          relation = @object.where(viz.accept(search.base))
          if search.sorts.any?
            relation = relation.except(:order).reorder(viz.accept(search.sorts))
          end
          opts[:distinct] ? relation.distinct : relation
        end
```

**Comment by blklane** [comment]
Any progress on this? Would be interested in how others solved this issue.

**Comment by 3du4** [comment]
a

**Comment by jonatack** [comment]
Please see this new blog post by @radar, our co-maintainer: http://ryanbigg.com/2015/11/open-source-work/

This is free, DIY, OSS software that no one is paid to work on, yet many companies use it for making apps.

The issue tracker isn't intended for feature requests.

If there was "progress", you would see it here. 

If the feature is important to you, contribute a PR or pay someone to do it.

Please don't request progress on new OSS features without doing anything because it just wastes people's time.

I'm now alone maintaining this and am very short of time to contribute.

Thanks for your understanding.

**Comment by aldrinmartoq** [comment]
The solution given by @jonatack does not work if the sort column is an association (in my case a self association).

I got it working with the following code for Postgresql:
```ruby
search = Model.ransack(…)
…
result = search.result
orders = result.orders.map { |order| order.direction == :asc ? "#{order.to_sql} NULLS FIRST" : "#{order.to_sql} NULLS LAST" }
result = result.except(:order).order(orders.join(", ")) if orders.count > 0
```

Hope this helps, cheers.

**Comment by spovich** [comment]
I think `reorder()` should work:

```
result = result.reorder(orders.join(", ")) if orders.count > 0
```

**Comment by jordanmaguire** [comment]
This is a very old issue but it showed up in my search results when trying to implement this so I figured I'd put a nicer solution here.

From the README you can see instructions for creating a virtual field to sort on, so if you wanted to sort on an attribute called "name" you could do:

In your model:

```ruby
# These scopes are used by Ransack's sort
scope :sort_by_name_nulls_last_asc, -> { order("name ASC NULLS LAST") }
scope :sort_by_name_nulls_last_desc, -> { order("name DESC NULLS LAST") }
```

in your view:

```ruby
<th><%= sort_link(@q, :name_nulls_last, "Name") %></th>
```

**Comment by aoozdemir** [comment]
One issue I found recently is this. If I do this in the controller, the direction is always `ASC`.

```
@q = Consent.ransack(params[:q])
@q.sorts = ['consent_given_at desc nulls last'] if @q.sorts.empty?
```

```
Consent Load (11.5ms)  SELECT  "consents".* FROM "consents" ORDER BY consent_given_at asc NULLS LAST LIMIT $1 OFFSET $2  [["LIMIT", 100], ["OFFSET", 0]]
```

**Comment by jigarbhatt2711** [comment]
> This is a very old issue but it showed up in my search results when trying to implement this so I figured I'd put a nicer solution here.
> 
> From the README you can see instructions for creating a virtual field to sort on, so if you wanted to sort on an attribute called "name" you could do:
> 
> In your model:
> 
> ```ruby
> scope :sort_by_name_nulls_last_asc, -> { order("name ASC NULLS LAST") }
> scope :sort_by_name_nulls_last_desc, -> { order("name DESC NULLS LAST") }
> ```
> 
> in your view:
> 
> ```
> <th><%= sort_link(@q, :name_nulls_last, "Name") %></th>
> ```

This solution is working. You saved my day. Thanks a lot.

**Comment by andrewdesmondm** [comment]
> One issue I found recently is this. If I do this in the controller, the direction is always `ASC` in the query that runs.
> 
> ```
> @q = Consent.ransack(params[:q])
> @q.sorts = ['consent_given_at desc nulls last'] if @q.sorts.empty?
> ```
> 
> ```
> Consent Load (11.5ms)  SELECT  "consents".* FROM "consents" ORDER BY consent_given_at asc NULLS LAST LIMIT $1 OFFSET $2  [["LIMIT", 100], ["OFFSET", 0]]
> ```

I am having this same issue. Does anyone know the solution to this?

**Comment by spovich** [comment]
@andrewdesmondm this isn't ideal, but you can apply nulls last by doing a `reorder`.  This works because of active record using lazy evaluation, so only one query is executed with the proper sorting.

```
@search = scope.ransack(params[:q])
@search.sorts = "foobar asc" if @search.sorts.empty?
result = @search.result
result = result.reorder("#{@search.sorts.first.name} #{@search.sorts.first.dir} NULLS LAST")
@items = result.page(params[:page])
```

**Comment by amirali-ashraf** [comment]
Just for the others who might visit this page again, you can add the option for postgres so it puts the nulls either first or last.

Link to code is:

https://github.com/activerecord-hackery/ransack/blob/e13cf7b503d72e9645ee6ce623e10f3f2fd6ec9d/lib/ransack/configuration.rb#L170C8-L170C8

Also you can find the options here:
https://github.com/activerecord-hackery/ransack/blob/e13cf7b503d72e9645ee6ce623e10f3f2fd6ec9d/lib/ransack/adapters/active_record/context.rb#L45

So, you can change the config file to change the behaviour of ransack within your app (initializers/ransack.rb):

```ruby
Ransack.configure do |config|
  config.postgres_fields_sort_option = :nulls_first # :nulls_last, :null_always_first, :null_always_last
end
```
