### ISSUE TITLE
Compound ransacker

### ISSUE THREAD

**Issue by glebm** [activerecord-hackery/ransack#45]
Hi!

How do I create a ransacker that depends on two arguments?

Example:

I want to search by `max_price` based on `max_price_amount` and `max_price_currency`.

I tried the following

```
ransacker :max_price, args: [:amount, :currency] do |price_per_hour, currency|
  usd_cents = Money.new(price_per_hour.to_i * currency.subunit_to_unit, currency).exchange_to(:usd).cents
  Arel::Nodes::InfixOperation.new('<=', parent.table[:price_per_hour_usd_cents], usd_cents)
end
```

I tried the code below for the view; it generates the view, but on submit gives a different error: 
`No valid predicate for max_price`

```
= f.fields_for :max_price do |mpf|
  = mpf.text_field :amount
  = mpf.select :currency
```

**Comment by deeTEEcee** [comment]
uhh is it alright if i ask... what is a compound?? while learning ransack, one of the options for arel predicates is "compounds: true" and yet, i find nothing about compounds in arel nor anywhere else.

**Comment by Genkilabs** [comment]
@deeTEEcee , I haven't messed with this in a while, here are some comments I found in my own code
```ruby
Ransack.configure do |config|
	config.add_predicate 'eq_any_or_nil',
						# What non-compound ARel predicate will it use? (eq, matches, etc)
						:arel_predicate => 'eq_any',
						# Format incoming values as you see fit. (Default: Don't do formatting)
						:formatter => proc {|val|
							"nil" == val ? nil : val
						},
						# Validate a value. An "invalid" value won't be used in a search.
						# Below is default.
						 # :validator => proc {|v| v.present?},
						:validator => proc {|val|
							val.present? && !val.blank?
						},
						# Should compounds be created? Will use the compound (any/all) version
						# of the arel_predicate to create a corresponding any/all version of
						# your predicate. (Default: true)
						:compounds => false,
						# Lets us force per item array handling in the valiator and formatter
						:wants_array => true
						# Force a specific column type for type-casting of supplied values.
						# (Default: use type from DB column)
						# :type => :string
end
```

This is to deal with a situation where someone might search several terms, or want to include no terms. ie. searching Table.color for 'red, green, nil' where an unpainted table is a valid option. For some reason the users wanted 'nil' as a string to represent the 'its ok to have it be blank too' results.

Leaving Compound 'true' would create a query with both an "IN" comparison and "=" comparisons for each element and then join them. It used correct parentheses and creates valid SQL but returns erroneous results due to the requirement of including NULLness.

Hope that helps.

**Comment by Genkilabs** [comment]
This is coming back to me now... I remember never finding any docs on this feature and coming to my own conclusions after digging into the source and then experimenting. Sorry but thats all I can offer. If anyone else finds more conclusive docs on this param, other than my example, please link 'em here for others who come this way. Thanks

**Comment by deeTEEcee** [comment]
@Genkilabs much appreciated sir. 
yeah, regarding the docs, ernie claims most of the issues users are having understanding this are out of lack of understanding of arel. but.. i dont think i can agree with that. of course, i myself dont fully understand arel but the docs could use some huge improvement imo which i would love to help if i ever get to dig further into this gem :)

**Comment by jonatack** [comment]
@deeTEEcee @Genkilabs anyone can edit/update the Ransack wiki and that would be the best place to share your doc improvement suggestions :smiley:
