### ISSUE TITLE
PG::UndefinedFunction: ERROR:  could not identify an equality operator for type json

### ISSUE THREAD

**Issue by jspillers** [activerecord-hackery/ransack#453]
When trying to use ransack on a table that has a postgresql json column it causes the following error:

PG::UndefinedFunction: ERROR:  could not identify an equality operator for type json

Only occurs when passing distinct: true to #result

**Comment by Emerson** [comment]
Seeing this on `master` as well

**Comment by Emerson** [comment]
This is probably the same issue outlined here: https://github.com/mbleigh/acts-as-taggable-on/pull/496

**Comment by ridget** [comment]
Ran into this error before, when calling uniq on a model that had a json field in postgres 9.3. If you are able to upgrade, switching the column to type jsonb and updating to >= postgres 9.4 will fix this.

**Comment by seanlinsley** [comment]
I can confirm that upgrading to Postgres 9.4 and using JSONB fixes this.
```ruby
select '{}'::json = '{}'::json;
ERROR:  operator does not exist: json = json

select '{}'::jsonb = '{}'::jsonb;
 ?column? 
----------
 t
(1 row)
```

**Comment by seanfcarroll** [comment]
I suggest we add to the README that jsonb in Postgres 9.4+ should be used for json-type fields in Ransack operations.

**Comment by pnomolos** [comment]
@seanfcarroll You should note that you'll have to use a JSONB column in PG 9.4+ (or note that in general JSON columns will not work).  The non-JSONB JSON types have no equality operator, hence the original error (DISTINCT with no arguments compares every column of each record, including those with no equality operator).

**Comment by jonatack** [comment]
For what it's worth, SQL DISTINCT is a bit of a code smell. It can mean the queries are not well written and that they are needlessly loading duplicates.

**Comment by seanfcarroll** [comment]
Closed due to inactivity
