### ISSUE TITLE
Sql Server RuntimeError: No table named ... exists

### ISSUE THREAD

**Issue by rdaniels** [activerecord-hackery/ransack#459]
It appears that Ransack errors when referencing the database name in the model. I am using MS SQL with activerecord-sqlserver-adapter. I need to reference another database in my Customer model with:
self.table_name = 'LincolnMain.dbo.customers'

My rails database isn't LincolnMain, referencing an alternate database like this allows me to pull this table and works throughout my Rails app, except with Ransack. When i execute:

Customer.search(first_name_eq: "rob").result
RuntimeError: No table named LincolnMain.dbo.customers exists
from /Users/robdaniels/.rvm/gems/ruby-2.1.1/gems/ransack-1.4.1/lib/ransack/adapters/active_record/context.rb:29:in `type_for'

Most of my code uses .where
Customer.where(first_name: "rob")
which pulls correctly

ruby 2.1.1
rails 4.1.6
ransack 1.5.0

any ideas?
Rob

**Comment by lahirisan** [comment]
b

**Comment by lahirisan** [comment]
hi @jonatack 
Im trying to use ransack  sorting feature with 2 different db connections, using many to many relation between my  models
I have 3 models with this relation among them:

`class SqlServerIncidente < ApplicationRecord
  establish_connection :sql_server
  self.table_name_prefix = "Alto.dbo."
  self.table_name = 'Incidente'
  has_many :sql_server_incidente_linkages,  foreign_key:  "sql_server_incidente_id"
  has_many :linkages,  :through => :sql_server_incidente_linkages
end`

`class Linkage < ApplicationRecord`

	has_many :sql_server_incidente_linkages, dependent: :destroy
	has_many :sql_server_incidentes, :through => :sql_server_incidente_linkages
`end`


`class SqlServerIncidenteLinkage < ApplicationRecord
	belongs_to :linkage
	belongs_to :sql_server_incidente
end`

In rails console i can do this successfully
`SqlServerIncidente.first.sql_server_incidente_linkages.first.linkage.name`

but when a try to sort with ransack the field name for Linkage model using the previous defined relation i get this error:

`(TinyTds::Error: Invalid object name `'sql_server_incidente_linkages'.`

it is  like rails do  not recognize the relation among MS SQLServer and Mysql. 

Any Idea???
Sorry by my english by the way.
Thanks
