### ISSUE TITLE
ransacker validator option

### ISSUE THREAD

**Issue by glebm** [activerecord-hackery/ransack#47]
Here is my ransacker definition:

```
  ransacker :price_per_hour_usd, type: :integer,
            formatter: lambda { |v| v.to_i * 100 },
            validator: lambda { |v| v.present? && v.to_i > 0 } do |parent|
    parent.table[:price_per_hour_usd_cents]
  end
```

It appears the `validator` option has no effect. Is it possible to ignore negative/zero values for a ransacker?

**Comment by ivobenedito** [comment]
Tried that and it isn't working. 
I suspect the validator isn't being executed.

**Comment by seanfcarroll** [comment]
Closed
