### ISSUE TITLE
How to use Predicates for each field

### ISSUE THREAD

**Issue by vixlima** [activerecord-hackery/ransack#471]
Friend,
I would like choose the type of predicate for each field. 

![filters](https://cloud.githubusercontent.com/assets/113282/5148978/736ac54a-71ab-11e4-9bee-4f6de9d9d44e.png)

  <%= f.label :issue_on %>
  <%= f.predicate_select only: i%(el lt gt) %>
  <%= f.text_field :issue_on %>

  <%= f.label :city %>
  <%= f.predicate_select only: i%(cont eq) %>
  <%= f.text_field :city %>

I receive error: **No valid predicate for issue_on**
how I do it?

Thanks

**Comment by jonatack** [comment]
Your code example has several syntax errors. I'm not sure how to reproduce the issue. Please provide the information requested in the Contributing Guide. Until then, closing this as stalled. Thanks.
