### ISSUE TITLE
id column not receiving array for custom ransacker

### ISSUE THREAD

**Issue by johnrees** [activerecord-hackery/ransack#472]
I have a ransacker called `:student_users` and use the filter `student_users_in`

I've simplified the code below to try and show what is happening

```
ransacker :student_users, :formatter => proc { |v|
  [10,11]
} do |parent|
  parent.table[:id]
end
...
SELECT DISTINCT "users".* FROM "users" WHERE "users"."id" IN (NULL)
```
I'd expect the above to return `SELECT DISTINCT "users".* FROM "users" WHERE "users"."id" IN (10,11)`

If I return an integer in the proc then it behaves as I'd expect

```
ransacker :student_users, :formatter => proc { |v|
  10
} do |parent|
  parent.table[:id]
end
...
SELECT DISTINCT "users".* FROM "users" WHERE "users"."id" IN (10)
```

If I filter the `first_name` (string) field instead of `id`, it shows that the array is actually getting passed from the proc

```
ransacker :student_users, :formatter => proc { |v|
  [10,11]
} do |parent|
  parent.table[:first_name]
end
...
SELECT DISTINCT "users".* FROM "users" WHERE "users"."first_name" IN ('---
- 10
- 11
')
```

Have I misunderstood something here?

**Comment by ideanl** [comment]
I am experiencing the same issue, and have looked through the source a bit, but I'll keep digging for the bug. It appears that the first name is being passed in incorrectly, so that's also an issue right?

**Comment by jonatack** [comment]
@johnrees, @ideanl, thanks for the issue.

The first step to take would be to write a test for the problem that works with Arel 5 and that fails with Arel 6 or Arel master.

This would allow others to reproduce the problem easily and then work efficiently to solve it.

**Comment by jonatack** [comment]
@johnrees, @ideanl, thanks for the issue.

The first step would be to contribute a test for the problem that works with Arel 5 and that fails with Arel 6 or Arel master.

This would allow others to reproduce the problem easily and then work efficiently to solve it.

I often spend more time trying to reproduce the problem and the OP's environment than in finding the bug. Even if you don't have an answer to the problem, contributing regression specs encourages others who aren't encountering the issue to have a look with their limited time ;).

**Comment by jonatack** [comment]
@johnrees, @ideanl, thanks for the issue.

The first step would be to contribute a test for the problem that works with Arel 5 and that fails with Arel 6 or Arel master.

This allows others to reproduce the issue easily and then work efficiently to solve it.

It often takes way more time to reproduce the issue and the OP's environment, than to fix the bug itself afterward. In practice, with edge case issues if I have not encountered the issue myself and if no tests are provided by the OP, than it's usually not very efficient to try reproducing it and I tend to work on the issues that I'm already encountering myself (like Arel 7 and Rails 5 already making breaking changes...).

So even if you don't have an answer to the problem, contributing regression specs encourages others who aren't encountering the issue to have a look with their limited time ;)

**Comment by jonatack** [comment]
Update: #486 fixes compatibility with Arel 6.0. Filtering on a string field instead of on `id` as per the OP's last example is still not working.

**Comment by ideanl** [comment]
Filtering on a string field works now in PR #488

**Comment by jonatack** [comment]
Great job. Closing this.
