### ISSUE TITLE
WORKAROUND: Bad SQL code being generated when 'Contains' is used on an Integer field?  UPDATED

### ISSUE THREAD

**Issue by jdrago** [activerecord-hackery/ransack#475]
Update:  FIXED It looks as though this issue is a duplicate of #85 previously reported.  Although, the condition selected is presented from as a choice from all table fields and all search criteria.   

Adding a ransacker to each model for each integer type fixes this issue!

I am using a simple example of a field containing a value for an integer (operator_id).  It looks as though the SQL generated does not have the correct syntax for ILIKE.

Ransack: Version 1.5.1 from Github Master
Rails: Version 3.2.16
Ruby: 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin13.0.0]

The errant SQL code:

Broadcast Load (0.5ms)  SELECT "broadcasts".\* FROM "broadcasts" WHERE ("broadcasts"."operator_id" ILIKE 0) ORDER BY "broadcasts"."location_name" ASC LIMIT 6 OFFSET 0
PG::UndefinedFunction: ERROR:  operator does not exist: integer ~~\* integer
LINE 1: ...M "broadcasts"  WHERE ("broadcasts"."operator_id" ILIKE 0) O...

I'm thinking that the ILIKE clause should be generated as:

WHERE ("broadcasts"."operator_id" ILIKE '%0%')

Could this possibly be an issue with the SQL generated in Ransack?

Thank you,
John

**Comment by ideaoforder** [comment]
I'm VERY late to the game here, but I don't think this is a duplicate of #85.

The conditions here are pretty explicit (and it's easy to reproduce):

1. Custom ransacker (not using `parent[:column]`)
2. Compound condition

I.e. `Resource.ransack(reference_id: 123, custom_ransacker_in: ['ABC', 'XXX'])` will result in something like:

```sql
"SELECT `resources`.* FROM `resources`  WHERE ((`resources`.`reference_id` = 1 AND CONVERT(UPPER(SUBSTR(name, 4, 2)), CHAR(8)) IN (0, 0)))"
```

**Comment by ideaoforder** [comment]
I've posted the above #914, not realizing this was actually the same issue.
