### ISSUE TITLE
Sorting associated columns not working, param is getting ignored

### ISSUE THREAD

**Issue by atrapp** [activerecord-hackery/ransack#476]
Hi, I am trying to sort my view by an associated column (Location has_many lessons). The param is being sent in the url but it is getting ignored:

Started GET "/search?phrase=&q%5Bs%5D=locations.loc_name+asc&x=0&y=0" for 127.0.0.1 at 2014-11-26 11:46:48 -0500
Processing by SearchController#index as HTML
Parameters: {"phrase"=>"", "q"=>{"s"=>"locations.loc_name asc"}, "x"=>"0", "y"=>"0”}

The field is not being added to the query:
(0.6ms)  SELECT COUNT(_) FROM "lessons"
Lesson Load (0.5ms)  SELECT  "lessons"._ FROM "lessons"  LIMIT 10 OFFSET 0
Location Load (1.2ms)  SELECT "locations".\* FROM "locations"  WHERE "locations"."id" IN (1, 8, 6)

Call on the SearchController:
@search = Lesson.search(params[:q])
@lessons = @search.result.includes(:location).page(params[:page])

Current versions:
Ruby 2.1.1p76
Rails 4.1.7
Ransack 1.5.1 (master branch)

I also tried the specific Ransack version 1.2.4 for Rails 4.1.

Thanks for your support.

**Comment by robinbortlik** [comment]
Hi I think, issue is that when you want to sort by relation you have to use convention model_attribute and not model.attribute . See this issue https://github.com/activerecord-hackery/ransack/issues/13
