### ISSUE TITLE
RethinkDB support through NoBrainer

### ISSUE THREAD

**Issue by mbrock** [activerecord-hackery/ransack#489]
Hello. In order to make ActiveAdmin work with RethinkDB and the NoBrainer ORM, I'd like to add NoBrainer support to Ransack. Since @Zhomart added support for Mongoid (#407), there seems to be an extension point for new ORM adapters. Of course, I'll add specs for this, and our organization will (if all goes as planned) use this functionality in production—at least the subset touched by ActiveAdmin. I will fork the project and start working actively in the hopes of getting it working as soon as possible.

**Comment by jonatack** [comment]
Sure, go for it! @Zhomart did help organizing the Ransack codebase to facilitate adding new adapters. The main caveat with that, as with Mongoid, is that the current maintainers will likely maintain the Active Record parts of the codebase only, so keeping Mongoid and RethinkDB working will depend on the people who use them actively maintaining them :).

**Comment by mbrock** [comment]
... on second thought, we will make an attempt to get `rails_admin` working with NoBrainer instead, since this seems to be a simpler project. Maybe if we outgrow `rails_admin`, we'll get back to this, but feel free to delete this issue.

**Comment by jonatack** [comment]
No problem. I have no opinion on RailsAdmin vs ActiveAdmin, having never used them. Good luck!
