### ISSUE TITLE
undefined method `map' for 76:Fixnum

### ISSUE THREAD

**Issue by dominicwong617** [activerecord-hackery/ransack#493]
I am upgrading an app from Rails 4 to 4.2 and I am having issues with ransack. I am using ransacker for my ActiveAdmin filters and I am seeing an error on [this line](https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters/active_record/ransack/nodes/condition.rb#L34)

It is saying that `predicate.right[0]` equals to 76 (the first location id in my params[:q][:location_assignments_location_id_in] array), which obviously cannot be mapped.

There is a `FIXME` [here](https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters/active_record/ransack/nodes/condition.rb#L27) that makes me suspect it's somewhere in ransack that causes this issue, which I haven't been able to figure out yet.

I appreciate your help.

app/admin/users.rb
```ruby
ActiveAdmin.register User do
  filter :locations, as: :select, multiple: true, collection: proc{ Location.order(:name).load }
end
```

app/models/user.rb
```ruby
class User < ActiveRecord::Base
  has_many :location_assignments, dependent: :destroy
  has_many :locations, through: :location_assignments, dependent: :destroy
end
```

app/models/location_assignment.rb
```ruby
class LocationAssignment < ActiveRecord::Base
  self.table_name = :locations_users
  attr_accessible :location_id, :user_id
  belongs_to :location, touch: true
  belongs_to :user, touch: true
end
```

The request parameters
```ruby
{
    "utf8" => "✓",
    "q" => {
        "location_assignments_location_id_in" => ["76", "81", "98", "4", "53", "52", "11", "58"] 
    },
    "commit" => "Filter",
    "order" => "id_desc"
}
```

**Comment by jonatack** [comment]
Thanks. Seems to be the same issue as #492.

**Comment by dominicwong617** [comment]
@jonatack Thank you.
