### ISSUE TITLE
search_form_for does no longer work with arrays

### ISSUE THREAD

**Issue by daniel-rikowski** [activerecord-hackery/ransack#494]
Previously it was possible to use `search_form_for` with an array parameter, just like `form_for`

e.g.
```
search_form_for [:admin, @q] do |f|
```
In Ransack 1.6.x this no longer works. It look like c6c163c2ac7075508d8ea6e4c372782dc335f87e has removed some brackets which were in fact necessary to ensure the correct code execution order.

**Comment by jonatack** [comment]
Thank you. Will re-add the parentheses right away. The test suite never raised this issue, so we'll need to add tests for this.

**Comment by jonatack** [comment]
Regression test added.

**Comment by daniel-rikowski** [comment]
Thank you very much!
