### ISSUE TITLE
Sorting on association field with distinct true yields PGSQL error

### ISSUE THREAD

**Issue by k4roshi** [activerecord-hackery/ransack#495]
I have a Patient model with a ward association. I want to sort patients by ward name. 
Sorting alone produces the correct SQL:
```
Patient.ransack({s: "ward_name asc"}).result.to_sql
=> "SELECT \"patients\".* FROM \"patients\" LEFT OUTER JOIN \"wards\" ON \"wards\".\"id\" = \"patients\".\"ward_id\"  ORDER BY \"wards\".\"name\" ASC" 
```

Sorting distinct produces wrong SQL statement:
```
Patient.ransack({s: "ward_name asc"}).result(distinct: true).to_sql
    => "SELECT DISTINCT \"patients\".* FROM \"patients\" LEFT OUTER JOIN \"wards\" ON \"wards\".\"id\" = \"patients\".\"ward_id\"  ORDER BY \"wards\".\"name\" ASC" 
```

that in turn yields this error:
```
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ... ON "wards"."id" = "patients"."ward_id"  ORDER BY "wards"."n...
```

**Comment by jonatack** [comment]
Hi @k4roshi, did you see where this is discussed in the README docs? Closing this for now. Don't hesitate to provide more information if you feel this is a different issue.

**Comment by mikel** [comment]
Perhaps solved by https://github.com/activerecord-hackery/ransack/pull/599 ?

**Comment by brendon** [comment]
A quick note: If you're using `.includes()` you can also use `.references()` to force those tables to be joined in the query (rather than loaded on the side (at Rail's discretion)). You can then safely add `.select()` to the query to select all the fields you'll be ordering on.
