### ISSUE TITLE
Disabling Search or Navigation for New Actions?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [activerecord-hackery/ransack#500]
I'm getting errors inside of my application.html.erb when I attempt to create a new form.

ArgumentError in Events#new
ActionView::Template::Error (No Ransack::Search object was provided to search_form_for!):
    80:                       <%= search_form_for @search do |f| %>
    81:                       <%= f.text_field :title_cont, placeholder: 'Search for an Event' %>
  app/views/layouts/application.html.erb:80:in `_app_views_layouts_application_html_erb___391031124_50750424'

This also happens when I try to manually route to the events/index without providing information to the search query. It tells me that 'name' is undefined.

I'm trying to make the search box available throughout all controllers. But, I think that it's stopping certain actions from firing off. [search bar embedded into navigation]

In my application_controller.rb
before_filter :set_search, except: [:new, :create, :edit, :update]

  def set_search
  @search = Event.search(params[:q])
  end

**Comment by jonatack** [comment]
Your code shows that your `before_action` is not setting the search for the `new` action.

**Comment by jonatack** [comment]
`before_filter :set_search, except: [:new, :create, :edit, :update]`
