### ISSUE TITLE
Wrong result and errors for join/group/having scope with certain values (0 and 1)

### ISSUE THREAD

**Issue by gkop** [activerecord-hackery/ransack#502]
Testing ransack v1.6.3, rails 4.1.8

```ruby
class Cart < ActiveRecord::Base
  has_many :items

  def self.items_count_equals(n)
    joins(:items).group("carts.id").having("count(items.id) = ?", n)
  end

  def self.ransackable_scopes
    [:items_count_equals]
  end
end

# when 0 is passed in to ransack, no filtering is performed, and all Cart records are
# returned. (in fact, the scope method is never called)
# meanwhile the class method *does* produce correct results with 0 passed in
> Cart.ransack(items_count_equals: 0).result.length == Provider.items_count_equals(0).length
=> false

# when 1 is passed in to ransack, the scope method is called
# but `true` comes in for `n` which is eventual converted to
# a "t", which causes a SQL error
> Cart.ransack(items_count_equals: 1).result
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "t"
LINE 1: ...rts"."id" GROUP BY carts.id HAVING count(items.id) = 't'
```

Passing in positive integer values other than 0 and 1 appears to produce the expected results.

This unexpected behavior also appears when using named scopes rather than class methods and when querying for `<` and `>` in addition to `=`.

When using named a named scope and a lambda, the error is different in the case when 1 is passed in:
```ruby
ArgumentError: wrong number of arguments (0 for 1)
```

This suggests to me this bug may be connected to #404 .

**Comment by dan532** [comment]
+1 here but looks like fix 502 will see us through. Thank you!

**Comment by jaredbeck** [comment]
I think this commit might break a really common use case.

Let's say there's a checkbox like:

```html
<input name="search[my_bool_eq]" value="0">
```

And that value goes straight into a search, like:

```ruby
MyRecord.search(params['search'])
```

Before this commit, `search(my_bool: '0')` only finds `false` records.  After this commit, it finds all records.

So, this commit breaks a really common use case, right?  We'd have to do some manual typecasting in our controller now.  Was that an intentional change?  If so, I'd recommend bumping the major version of ransack, because I think it's gonna break a lot of apps out there.

**Comment by avit** [comment]
@jonatack please see my comment on the pull request #503

**Comment by gkop** [comment]
@avit so I just change my code to this?

```ruby
Cart.ransack(items_count_equals: [1]).result
```

**Comment by avit** [comment]
@gkop yup, that's right!

**Comment by gkop** [comment]
Ah excellent. I suppose I will need to patch activeadmin now :)

**Comment by tekniklr** [comment]
It seems that this is also a problem when the strings 't' or 'f' are passed in.
