### ISSUE TITLE
FR: Ransack::Condition is accessible in Ransack::Attribute

### ISSUE THREAD

**Issue by sineed** [activerecord-hackery/ransack#508]
Hi! I have a feature request.

Sometimes it can be useful to have instance of `Ransack::Condition` as instance variable of `Ransack::Attribute`. If so, condition can be bound into ransacker block. You can create a ransacker that can be based on condition values. For example,

```ruby
ransacker :test, args: [:condition] do |condition|
  value = condition.values.first.value
  if some_condition_based_on(value)
    Arel.sql('some SQL')
  else
    Arel.sql('another SQL')
  end
end
```

I don't know if it fits to main philosophy of `ransack` so before implementing some code I want to know if it can be useful not only for me.

**Comment by avit** [comment]
I do some funky things in ransackers to work around things myself, but I don't remember off the top of my head. Can you give an example use case? (the search params & the resulting query)

**Comment by jonatack** [comment]
Thanks. It might be useful to people and I'm curious to see an example as well.

**Comment by sineed** [comment]
@avit @jonatack Thanks for the quick feedback.

In my current project there are entities (say, `Product`) which can have custom fields  (say, `CustomField`). One `Product` has one `CustomFieldValue` also `CustomFieldValue` has a reference to `CustomField`:

```ruby
[21] pry(main)> CustomFieldValue
=> CustomFieldValue(id: integer, value: string, product_id: integer, custom_field_id: integer, created_at: datetime, updated_at: datetime) 
```

I want to search products by custom field value that has specific custom field id. And I want to use predicate logic as well for `CustomFieldValue`' value field.

So If `Ransack::Attribute` has a reference to its `Ransack::Condition` I need only *one* ransacker:

```ruby
ransacker :custom_field_value, args: [:condition] do |condition|
  custom_field_id = condition.values.shift
  Arel.sql("(SELECT value FROM custom_field_values cfv INNER JOIN custom_fields cf ON cfv.custom_field_id = cf.id WHERE products.id = cfv.product_id AND cf.id = #{custom_field_id.value})")
end
```

And usage of this ransacker:

```ruby
Product.ransack(c: [{ v: [custom_field_id, value], p: 'eq', a: ["custom_field_value"] }])
```

I don't like that I pass custom_field_id in `values` key. Maybe it can be another key in `Condition` build options that can be accessed in `Attribute` instance (e.g. `meta`)?

@jonatack is this still useful for other people?

**Comment by avit** [comment]
My case is very similar but I worked around it using the formatter option to chain a condition, using the callable field as an "identity no-op" (`id = id AND conditions`) instead:

```
ransacker :custom_field_value,
  formatter: ->(v) {
    arel_table.create_and([arel_table[:id], Arel.sql("other conditions")])
  },
  callable: ->(parent) {
    parent.table[:id] 
  }
```

It would definitely be helpful to have some flexibility around building the whole condition, not just formatting the right hand (value) side, which I'm obviously cheating my way around using AND...

**Comment by sineed** [comment]
@avit your solution works but yes, it is like a hack. I've proposed a PR and I will be glad if you share some thoughts about it.
