### ISSUE TITLE
Multiple string  search in single query

### ISSUE THREAD

**Issue by jenorish** [activerecord-hackery/ransack#510]
I want to do search like 

`SELECT "users".* FROM "users" WHERE  email LIKE 'kin%' OR name LIKE 'jeno%' ORDER  BY 1;`

so i have tried 

1) `User.search(:email_cont => ["kingston@jenorish.com","admin@jenorish.com"]).result`

2) `User.search(:email_cont => "kingston@jenorish.com","admin@jenorish.com").result`

But i failed to get the result,so please giude me How to do?

**Comment by jonatack** [comment]
Please have a look at the ReadMe, Contributing Guide and Wiki. 

Basically, use a form with two search fields (email and name) and use an `or` combinator.

If you read the documentation, you'll see it.

**Comment by jenorish** [comment]
@jonatack  am not asking about two fields search, Am asking one field with two different value.

see example 

    `User.search(:email_cont => ["kingston@jenorish.com","admin@jenorish.com"])`

**Comment by avit** [comment]
@jenorish yes, you can still do that with the same field. I'm not sure it's shown very well anywhere in the docs but you can combine different conditions like this too:

User.ransack(
  m: "or", 
  c: [
    {a: "email", p: "cont", v: "x@example.com"}, 
    {a: "email", p: "cont", v: "y@example.com"}
  ]
)

(a/p/v = attribute, predicate, value)

**Comment by jonatack** [comment]
@jenorish Yes. Once again, it's in the ReadMe. I took the time to add it to the documentation some time ago and it seems to me that it would be common courtesy to read the docs before filing a bug report on the issue tracker. Thanks.
