### ISSUE TITLE
Can sort_link sort according to a foreign attribute without a belongs_to?

### ISSUE THREAD

**Issue by nalereza** [activerecord-hackery/ransack#529]
I've read through the documentation and haven't found any information about this specific problem. I have a table of Projects, each of which contains Assigned_To and Created_By columns. These columns contain integers that correspond to the Users table. I want to allow people to sort the table alphabetically by the name of the user assigned to the project or the one who made it, but the Project itself doesn't have access to that information. It's important to note that there is no relationship between Projects and Users (ie Projects don't belong to or have Users and vice versa).

I'd like to be able to do a sort_link that maps the :assigned_by field to the user table and sorts according to the corresponding names, such as:

<%= sort_link @q, User.find(:assigned_by).name, "Creator" %>

Is something like that possible to do in Ransack?

**Comment by jonatack** [comment]
Hello @nalereza ! Could you please use StackOverflow for questions/help, where a wider community will be able to help you? The issues tracker is for bug reports. Thanks for your understanding :smiley:
