### ISSUE TITLE
how-to-make-search-dynamic-with-ransack-and-wicegrid

### ISSUE THREAD

**Issue by ddpdevang** [activerecord-hackery/ransack#532]
https://stackoverflow.com/questions/29575106/how-to-make-search-dynamic-with-ransack-and-wicegrid

**Comment by jonatack** [comment]
Hello @ddpdevang, please read the Ransack documentation and wiki and have a look at [http://railscasts.com/episodes/370-ransack](http://railscasts.com/episodes/370-ransack). The issues tracker is for bug reports only, not for personal support or feature requests. Thanks for your understanding :smiley:
