### ISSUE TITLE
Sort link on a last login timestamp for an associated model

### ISSUE THREAD

**Issue by jclemans** [activerecord-hackery/ransack#533]
Is it possible to sort using timestamps on an associated model? 

I'm dealing with a situation where a Parent class has many Children. In my view I am displaying each parents last child to sign in to the app. To do this I created a scope (last_child_sign_in) on my Parent model that does a complex sql query. I put that scope in my controller so that it has `@search = Parent.last_child_sign_in.search(params[:q])`. I then run another query on top of that result to get an Order count from another associated table.

In my view I have a `sort_link(@search, :last_child_sign_in, 'Last login')`, but it does no sorting. Any ideas would be appreciated.

**Comment by jonatack** [comment]
Hello @jclemans!

    Is it possible to sort using timestamps on an associated model?

Yes, it is :smiley: please have a look at the readme, the contributing guide, the wiki and the past issues.

P.S. The issues tracker is for bug reports only and not personal support, so closing this bug report. Thanks for your understanding.
