### ISSUE TITLE
Introduce ransack! so that invalid filters raise an exception

### ISSUE THREAD

**Issue by linkyndy** [activerecord-hackery/ransack#535]
It would be very useful to provide a method, `ransack!`, that will raise an exception if, say, a filter is not valid. Here's an example:

```ruby
class Client
  has_one :address
end

class Address
  belongs_to :client
end
```

If you do:

```
Address.ransack('client_name_cont' => 'bla')
```

and `name` is a valid field of `Client`, the above would work. But if you do:

```
Address.ransack('filter_not_existing_cont' => 'bla')
```

an error would be more appropriate to be raisen instead of returning all addresses (`SELECT "addresses".* FROM "addresses"`).

I find `ransack!` to be very useful; what do you think?

**Comment by jonatack** [comment]
Hi @linkyndy, there is a configuration option `ignore_unknown_conditions ` described [here in the wiki](https://github.com/activerecord-hackery/ransack/wiki/Configuration), that when set to false raises if a query contains an unknown predicate or attribute. Do you mean something different?

**Comment by linkyndy** [comment]
Indeed, that's what I was referring to. While it's already there, I believe having a `!` counterpart to `ransack` would be both intuitive and helpful.

**Comment by jonatack** [comment]
Feel free to make a PR :smiley:
