### ISSUE TITLE
Monkeypatching Object with a klass method breaks ransack

### ISSUE THREAD

**Issue by mharris717** [activerecord-hackery/ransack#539]
It's due to the `obj.respond_to? :klass` branch in a klassify method. The resulting error is ransackable_attributes is a missing method when you do something like Widget.ransack(color_cont: 'Green')

Rails 4.2 & 4.2.1
Ransack 1.6.6 and master

Don't know if you even consider it a bug or not. Adding klass globally could be a "do at your own risk" move. 

Let me know if you would like more details, happy to provide.

**Comment by mharris717** [comment]
Didn't mean to leave an issue without proper info. Just not sure if you even consider it a bug or not. If not, then no reason to provide more. If you do, happy to generate better info.

**Comment by jonatack** [comment]
Hi @mharris717, thanks for reporting the issue. Yes, more info as per the Contributing Guide would be helpful in order to understand and reproduce it. Will re-open if you provide it. Thanks!
