### ISSUE TITLE
Hot to add rel nofollow?

### ISSUE THREAD

**Issue by woto** [activerecord-hackery/ransack#540]
Hi, thanks for the gem. I have a question. Is there a way to add rel="nofollow" to sort_link helper?
I've tried like `<%= sort_link(@q, :..., rel: 'nofollow') %>` but it doesn't work.

**Comment by jonatack** [comment]
Hi @woto, I'm not familiar with using that outside of the html head section, and don't really know why you would, but I imagine you could put it in the markup around the sort_link, or in the html options part of a `content_tag`, like this:

```erb
<%= content_tag :th, sort_link(@q...), rel: 'nofollow' %>
```

**Comment by woto** [comment]
@jonatack Hi, thanks for response. Because English is not my first language, it's hard to explain my thoughts. May be you will view this [link](https://support.google.com/webmasters/answer/96569?hl=en)?
