### ISSUE TITLE
using a joins scope generates wrong sql queries

### ISSUE THREAD

**Issue by tland** [activerecord-hackery/ransack#543]
Hi,

I have a ransacker which maps the value of a column to different values. 

```
STATUS_SQL = %{CASE
  WHEN books.name = 'A' THEN 'STATUS_FOO'
  WHEN books.name = 'B' THEN 'STATUS_BAR'
END}

ransacker :status, type: :string do 
  Arel::Nodes::SqlLiteral.new(STATUTS_SQL)
end
```

It works perfectly fine when the query doesn't involve any table joins like below.
```
Book.select('books.*').search(status_eq: 'STATUS_FOO').result.to_sql

=> SELECT books.* FROM books WHERE CASE WHEN books.name = 'A' THEN 'STATUS_FOO' WHEN books.name = 'B' THEN 'STATUS_BAR' END = 'STATUS_FOO'
```

However, if there's a joins, the passed in string 'STATUS_FOO' is casted to integer 0.

```
Book.select('books.*').joins(:book_stores).search(status_eq: 'STATUS_FOO').result.to_sql

=> SELECT books.* FROM books INNER JOIN book_stores ON  books.store_id = book_stores.id WHERE case when books.name = 'A' THEN 'STATUS_FOO' WHEN books.name = 'B' THEN 'STATUS_BAR' END = 0
```

**Environment:**

Rails: 3.2.21
Ransack: 1.5.1

**Comment by romainbx** [comment]
I got the same problem with joins, but only when I use a ransacker for one of the field.
```ruby
ransacker :name, type: :string do
  Arel.sql("`users`.`name`")
end
# NB: the real ransacker is used to search with the Postgres 'unaccent' extension
```
```
User.joins(:school).ransack({:name_cont => "He"}).result.size

=> SELECT COUNT(*) FROM `users` INNER JOIN `schools` ON `schools`.`id` = `users`.`school_id` WHERE (`users`.`name` LIKE 0)
```
Without the ransacker, the problem disappear :
```
User.joins(:school).ransack({:name_cont => "He"}).result.size

=> SELECT COUNT(*) FROM `users` INNER JOIN `schools` ON `schools`.`id` = `users`.`school_id` WHERE (`users`.`name` LIKE '%He%')
```
If I write the joins myself, it is also working, even with the ransacker :
```
User.joins("INNER JOIN `schools` ON `schools`.`id` = `users`.`school_id`").ransack({:name_cont => "He"}).result.size

=> SELECT COUNT(*) FROM `users` INNER JOIN `schools` ON `schools`.`id` = `users`.`school_id` WHERE (`users`.`name` LIKE '%He%')
```

**Environment:**

Ransack: 1.6.6
Ruby: 2.1.2p95
Rails: 3.2.13

**Comment by jonatack** [comment]
Thanks. This appears to be a duplicate report of a long-running issue. Please see #85, #442 and #475 for possible workarounds. Leaving #85 open as the original issue.

**Comment by ideaoforder** [comment]
I'm VERY late to the game here, but I don't think this is a duplicate of #85.

The conditions here are pretty explicit (and it's easy to reproduce):

1. Custom ransacker (not using `parent[:column]`)
2. Compound condition

I.e. `Resource.ransack(reference_id: 123, custom_ransacker_in: ['ABC', 'XXX'])` will result in something like:

```sql
"SELECT `resources`.* FROM `resources`  WHERE ((`resources`.`reference_id` = 1 AND CONVERT(UPPER(SUBSTR(name, 4, 2)), CHAR(8)) IN (0, 0)))"
```

I've posted the above #914, not realizing this was actually the same issue.
