### ISSUE TITLE
Non existent path error 

### ISSUE THREAD

**Issue by campgurus** [activerecord-hackery/ransack#545]
I have an Events model that I want to make searchable on a variety of fields. 

my controller action:
def index
  	@search = Event.ransack(params[:q])
	@events = @search.result(distinct: true)
  end

my search form in index.html.erb:

<%= search_form_for @search do |f| %>
  <%= f.text_field :name_cont, class: "radius-left expand", placeholder: "Event Name" %>
<% end %>

However, in loading the page, I get the error 
ActionView::Template::Error (undefined method `events_path' for #<#<Class:0x007fc08e6c6de8>:0x007fc08b3fa838>):
    1: <h1>Events</h1>
    2: 
    3: <%= search_form_for @search do |f| %>
    4:   <%= f.text_field :name_cont, class: "radius-left expand", placeholder: "Event Name" %>
    5: <% end %>
    6: 
  app/views/events/index.html.erb:3:in `_app_views_events_index_html_erb___2056451196739971413_70232473324180'

when I rake routes, I get:

             events_show GET    /events/show(.:format)         events#show
            events_index GET    /events/index(.:format)        events#index

what do I need to do to specify the correct path for the form?

**Comment by jonatack** [comment]
Looks good to me. The problem is probably elsewhere. Please use the issue tracker for reporting bugs with Ransack following the Contributing Guide, not for personal support. Thanks for your understanding!

**Comment by campgurus** [comment]
I thought it was an issue with Ransack, which is why I posted here. Thanks.

**Comment by lahgazisafae** [comment]
@campgurus  did you figure out the issue? I'm having the same problem.
