### ISSUE TITLE
Search#sanitized_scope_args coercion issue

### ISSUE THREAD

**Issue by karlentwistle** [activerecord-hackery/ransack#547]
Given the following simplified example of my model

````ruby
class Thing < ActiveRecord::Base

  scope :payback, -> (years) do
    if years == '12+'
      where('projected_payback_timeframe >= 12')
    else
      where('projected_payback_timeframe <= ?', years)
    end
  end

  private

  def self.ransackable_scopes(auth_object = nil)
    %i(payback)
  end
end
````

The following works

````ruby
Thing.ransack({payback: 2})
Thing.ransack({payback: 3})
# etc
````

However if I pass
````ruby
Thing.ransack({payback: 1})
````

It raises the exception

````
ArgumentError: wrong number of arguments (0 for 1)
from /Users/karl/local/curve/app/models/thing.rb:64:in `block in <class:Investment>'
````

This seems to be an issue with the sanitized_scope_args method here https://github.com/activerecord-hackery/ransack/blob/3e4b6e34abc4addc2bf258e2b51459910a03e04a/lib/ransack/search.rb#L141-L153

specifically the fact Constants::TRUE_VALUES includes 1

````ruby
Constants::TRUE_VALUES => #<Set: {true, 1, "1", "t", "T", "true", "TRUE"}>
````

Which leads to sanitized_scope_args incorrectly coercing my Integer to True.

Have I missed a trick, am I 'doing it wrong' or is this a bug?

Any help much appreciated

**Comment by karlentwistle** [comment]
It's also occurred to me that if your parameter was 'f' or 't' or 'F' or 'T' while searching alphabetical that would also incorrectly coerce into True or False class.

**Comment by karlentwistle** [comment]
Also 


````ruby
#Gemfile
ruby "2.2.0"
gem 'rails', '4.2.1' 
gem 'ransack' #(1.6.6)
````

**Comment by avit** [comment]
You should be passing scope args within an array. This should not get coerced:

    Thing.ransack({payback: [1]})

Scopes can have multiple arguments, these get splatted when an array is passed. Omitting the array is a convenience, but has some consequences.

**Comment by karlentwistle** [comment]
Ah yes I can see that in the documentation 

If the true value is being passed via url params or by some other mechanism that will convert it to a string (i.e. active: 'true' instead of active: true), the true value will not be passed to the scope. If you want to pass a 'true' string to the scope, you should wrap it in an array (i.e. active: ['true']).

Cheers avit
