### ISSUE TITLE
Ransack not working

### ISSUE THREAD

**Issue by acetinick** [activerecord-hackery/ransack#55]
As soon as I try render a search form  I get this:

undefined method `validators_on' for Ransack::Search:Class

 <%= search_form_for @q, :url => admin_users_url do |f| %>
8:     <div class="clearfix">
9:       <%= f.label :email_cont %>
10:       <div class="input">
11:         <%= f.text_field :email_cont %>
12:       </div>

**Comment by mohsinali** [comment]
got any solution to this?

**Comment by Blue-Dog-Archolite** [comment]
I also have this issue. Rails 3.X

**Comment by Blue-Dog-Archolite** [comment]
Turns out some idiot in my code base wrote a custom form wrapper that overloaded the def of 'validations_on' and breaks about every search and form interaction gem out there. Thanks dude!
