### ISSUE TITLE
rel="nofollow" last question

### ISSUE THREAD

**Issue by woto** [activerecord-hackery/ransack#550]
Hi @jonatack sorry for annoying, but i don't sure that you saw this answer https://github.com/activerecord-hackery/ransack/issues/540#issuecomment-107247049
The absence of <a rel="nofollow"... lead to bad SEO results where it should be used. 

<blockquote>
Before nofollow was used on individual links, preventing robots from following individual links on a page required a great deal of effort (for example, redirecting the link to a URL blocked in robots.txt). That's why the nofollow attribute value of the rel attribute was created. This gives webmasters more granular control: instead of telling search engines and bots not to follow any links on the page, it lets you easily instruct robots not to crawl a specific link. For example:
</blockquote>

<blockquote>
 &lt;a href="signin.php" rel="nofollow"&gt;sign in&lt;/a&gt;
How does Google handle nofollowed links?
</blockquote>

<blockquote>
In general, we don't follow them. This means that Google does not transfer PageRank or anchor text across these links. Essentially, using nofollow causes us to drop the target links from our overall graph of the web. However, the target pages may still appear in our index if other sites link to them without using nofollow, or if the URLs are submitted to Google in a Sitemap. Also, it's important to note that other search engines may handle nofollow in slightly different ways.
</blockquote>

Do you planning to add this feature or i should monkey patch gem?
Here is result of indexed pages which are same (difference only in sorting)

https://www.google.ru/search?q=site:avtorif.ru+275/70+R22.5&newwindow=1&es_sm=93&filter=0&biw=1215&bih=689

**Comment by avit** [comment]
A pull request for this is welcome. I would suggest setting this as `html_options: {rel: 'nofollow'}`.

(If you are concerned about diluted link juice for SEO, note that you can also set a `rel="canonical"` on the destination page if it should live somewhere else.)

**Comment by woto** [comment]
@avit, I'm sorry, I don't have enough experience to make a good pull request.

**Comment by seanfcarroll** [comment]
Closed
