### ISSUE TITLE
Sort by if an association exists

### ISSUE THREAD

**Issue by JoshuaNovak919** [activerecord-hackery/ransack#554]
I am trying to sort by if an association exists. For example, if I have a User model, a Book model, and a UsersBook model. There would be users, books, and users would have books through UsersBook. How can I sort users showing users that have books first in asc and last in desc?

**Comment by jonatack** [comment]
If Ransack's sort_link options don't suffice, you can modify the ransack search object sorts hash. It's been described in answers to issues from a year or two ago here.
