### ISSUE TITLE
Ransacker argument passing failing

### ISSUE THREAD

**Issue by MaximilianoFelice** [activerecord-hackery/ransack#559]
I've been trying the last few days to replicate what is explained here:

https://github.com/activerecord-hackery/ransack/wiki/Using-Ransackers#6-passing-arguments-to-a-ransacker

But it doesn't seem to be working. In fact, I copied exactly the same code but I keep getting the following error:

NoMethodError: undefined method `ransacker_args' for Attribute <author_max_title_of_article_where_body_length_between>:Ransack::Nodes::Attribute

Anyone experiencing the same problem?

**Comment by cpilegard** [comment]
I am getting the same error @MaximilianoFelice , were you able to solve the problem?

**Comment by MaximilianoFelice** [comment]
@cpilegard I'm sorry for the delay on answering. I did solve this issue by taking several measures.

What I think was the core of it, is updating the gem to it's last release. I found that there was an old version of Ransack (probably locked by ActiveAdmin Gem) that had this issue.

Try a full update (and check it on your gemfile.lock), and I'll reopen this thead if need be.

Good luck!!
