### ISSUE TITLE
Case Insensitive Query with Postgres

### ISSUE THREAD

**Issue by borderBite** [activerecord-hackery/ransack#57]
Is there a way to have Ransack pass case-insensitive queries to Postgres?
Can Ransack generate queries using [ILIKE](http://www.postgresql.org/docs/8.3/static/functions-matching.html) instead of LIKE?

Example:
If i use the _eq_ predicate, the generated query is case-sensitive.

```
= search_form_for @q do |f|
  = f.label :code
  = f.text_field :code_eq

= f.submit
```

**Comment by abhishek77in** [comment]
@spovich As you mentioned for `ILIKE` would be used by default for postgresql. How do I disable this functionality? I want to default to `LIKE`.
