### ISSUE TITLE
PG::InvalidDatetimeFormat when using _present

### ISSUE THREAD

**Issue by JFimex** [activerecord-hackery/ransack#570]
I am not 100% sure whether this is a bug or a misconfiguration on my part
ransack version: 1.6.6

I have a model Order that has the migration:     
      t.date :completed_on
      #irreverent others

Order.ransack(completed_on_present: false).result.to_sql
#SELECT "orders".* FROM "orders" WHERE ("orders"."completed_on" IS NULL OR "orders"."completed_on" = '')
#throws PG::InvalidDatetimeFormat 

whereas the activerecord equivalent is
Order.where(completed_on: nil).to_sql
#SELECT "orders".* FROM "orders" WHERE "orders"."completed_on" IS NULL

**Comment by ASnow** [comment]
For second result you can write:
``` ruby
Order.ransack(completed_on_null: true).result.to_sql
```
As I see it's not bug because ransack don't validate column types

**Comment by jonatack** [comment]
Thanks @ASnow. 

Seeing Ransack::Constants. The `_present` predicate searches on `nil` or empty `''`.

You could perhaps use the `_eq` predicate: `Order.ransack(completed_on_eq: nil)`

Or override `DERIVED_PREDICATES` with your modified version of the `_present` predicate.

Or use a ransacker.
