### ISSUE TITLE
Searches with scopes fail when the scope has a single argument and integer 1 is passed as a parameter

### ISSUE THREAD

**Issue by AndrewSwerlick** [activerecord-hackery/ransack#580]
Here's a fun little bug that had me scratching my head for a while. If you try to do a search using a scope which takes a single parameter, your search will fail if you try to use the value 1 as the parameter. Failing test case here https://github.com/AndrewSwerlick/ransack/blob/scope_bug/spec/ransack/adapters/active_record/base_spec.rb#L66

The test errors out with 

```
 ArgumentError:
      wrong number of arguments (0 for 1)
    # ./spec/support/schema.rb:48:in `block in <class:Person>'
    # ./lib/ransack/context.rb:50:in `public_send'
    # ./lib/ransack/context.rb:50:in `chain_scope'
    # ./lib/ransack/search.rb:130:in `add_scope'
    # ./lib/ransack/search.rb:45:in `block in build'
    # ./lib/ransack/search.rb:39:in `each'
    # ./lib/ransack/search.rb:39:in `build'
    # ./lib/ransack/search.rb:31:in `initialize'
    # ./lib/ransack/adapters/active_record/base.rb:15:in `new'
    # ./lib/ransack/adapters/active_record/base.rb:15:in `ransack'
    # ./spec/ransack/adapters/active_record/base_spec.rb:67:in `block (4 levels) in <module:ActiveRecord>'
```

I believe the problem actually stems from https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/search.rb#L138. Basically the sanitized_scope_args method converts the 1 to a true, which then changes how it's handled by `Context#chain_scope`.

This issue appears to have been introduced in 1.6.0, as it only cropped up in my application since we upgraded from 1.5.1. The santizied_scope_args method does not appear to existing in 1.5.1.

**Comment by kwerle** [comment]
This has bit me, too.  Reverting to 1.5.1 does the trick.

**Comment by adisos** [comment]
https://github.com/activerecord-hackery/ransack/issues/593

**Comment by haobole** [comment]
:+1:

**Comment by bolshakov** [comment]
:+1:

**Comment by bolshakov** [comment]
I think this should be fixed in ransack. My current fix:

```ruby
constants_to_remove = Set.new([1, '1', 't', 'T'])
Ransack::Constants::TRUE_VALUES = Ransack::Constants::TRUE_VALUES - constants_to_remove
Ransack::Constants::FALSE_VALUES = Ransack::Constants::FALSE_VALUES - constants_to_remove
Ransack::Constants::BOOLEAN_VALUES = Ransack::Constants::BOOLEAN_VALUES - constants_to_remove
```

**Comment by avit** [comment]
Agreed. See my comments in #509, I'm thinking to standardize this if it makes sense to everyone.

**Comment by tekniklr** [comment]
I just found a related problem. While passing 'true' to a ransackable scope works fine, passing 'TRUE' will also get read as a boolean and will trigger the same error.

**Comment by Fire-Dragon-DoL** [comment]
So, I stumbled upon this bug too, but it hit me much harder:

I created a scope which searches for name starting with a given text. Obviously, the user wanted all records starting with `T`, and T means `true` for ransack... and yeah, everything exploded

Thanks @bolshakov for the hotfix, I used it (although I made sure to remove also `f` and the various false values)

**Comment by seanfcarroll** [comment]
Closed by https://github.com/activerecord-hackery/ransack/pull/742

**Comment by truonglocbinh93** [comment]
@bolshakov Where I can add your code to fix this bug. I have same problem. Thanks

**Comment by bolshakov** [comment]
@truonglocbinh93 after loading the gem. If you are using rails, write it in initializer

**Comment by bolshakov** [comment]
Note, my workaround worked 3 years ago. Not sure if ot still aplicable

**Comment by truonglocbinh93** [comment]
@bolshakov Thank you. Now I have some case want to keep convert string to boolean but I have a case need pass as params, not as boolean. Do you know any custom config for only special scope with ransack ?

**Comment by bolshakov** [comment]
@truonglocbinh93 I have not used ransack for couple of years, so can't really help you. Probably it's better to validate and preprocess parameters before passing to ransack.
