### ISSUE TITLE
Chekboxes "0" should not be translated to != 't' Should instead be IS NOT TRUE

### ISSUE THREAD

**Issue by NielsKSchjoedt** [activerecord-hackery/ransack#585]
When a checkbox is not checked in a searchform it's submitted as `"q"=>{"is_enabled_true"=>"0"}` which will then render: `WHERE is_enabled  != 't'` in the SQL. This is bad, because it will not find nils. Instead it should render `WHERE is_enabled IS NOT TRUE` or maybe be left out completely of the search, since the the definition of `_true` is that you either want ONLY true values or you don't care.

**Comment by ml** [comment]
I noticed this problem too

**Comment by Eric-Guo** [comment]
I have the same problem, resolved by writing some code like below as a workaround.

```ruby
def index
  authorize User
  @q = User.search(params[:q].try { |q| q.reject { |k, v| v == '0' && k.end_with?('true') } })
  @employees = @q.result.paginate(page: params[:page], per_page: 10)
end
```

**Comment by avit** [comment]
See my comments on #509. I'm thinking to implement it that way if we are in agreement.

**Comment by seanfcarroll** [comment]
Can we close this issue, because of https://github.com/activerecord-hackery/ransack/pull/742
