### ISSUE TITLE
Search gives the error `PG::UndefinedFunction: ERROR:  operator does not exist` when trying to filter by ID

### ISSUE THREAD

**Issue by THPubs** [activerecord-hackery/ransack#586]
Im trying to filter the records by the `ID`. Here's my search form :

    <%= search_form_for @search, url: dash_orders_path, id: 'searchForm' do |f| %>
        <div class="col-md-4 margin-top-15">
            <%= f.search_field :id_cont, class: 'form-control', placeholder: 'Order id' %>
        </div>
        <span class="button-sec pull-left width-wide center-text searchBtn">
            <%= f.submit "Search", class: "button-big blue" %>
            <%= f.submit "Clear", class: "button-big red", onclick: "$('#searchForm')[0].reset();" %>
        </span>
    <% end %>

When trying to do the search, it gives an error like this :

    PG::UndefinedFunction: ERROR:  operator does not exist: integer ~~* integer
    LINE 1: ...CT  "orders".* FROM "orders" WHERE ("orders"."id" ILIKE 0)  ...
                                                                 ^
    HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
    : SELECT  "orders".* FROM "orders" WHERE ("orders"."id" ILIKE 0)  ORDER BY "orders"."updated_at" DESC LIMIT 2 OFFSET 0

What might be the issue?

**Comment by jonatack** [comment]
Please do have a look at the gem documentation and past issues before filing personal support requests in the issues tracker. Hint: Wiki -> Ransackers -> example 4.

**Comment by jonatack** [comment]
P.S. per the error message you supplied: "You might need to add explicit type casts", you are trying to use a predicate for use with strings on an integer field.
