### ISSUE TITLE
Convert JSON or hstore attributes to an integer?

### ISSUE THREAD

**Issue by jcohenho** [activerecord-hackery/ransack#587]
I noticed in the Wiki the ability to convert an integer db field into a string in order to use a `cont` predicate.      ```
ransacker :id do
  Arel.sql("to_char(id, '9999999')")
end```

I am assuming ransack predicates are enabled based on the column type by default, but when it comes to json or hstore attributes they can't assume the type. Is it possible to convert an hstore or json attribute to an integer? What would this look like?
 I'm currently using the following ransacker for a json attribute but need to search with greater than and less than predicates:
```
ransacker :order_amount do |parent|
    Arel::Nodes::InfixOperation.new('->', parent.table[:order_payload], Arel::Nodes.build_quoted('order_amount'))
  end
```

**Comment by bbozo** [comment]
@jcohenho did you ever figure this out? :-D

**Comment by jcohenho** [comment]
> @jcohenho did you ever figure this out? :-D

No, I ended up using a different library.
