### ISSUE TITLE
Change zh.yml to zh-CN.yml

### ISSUE THREAD

**Issue by ethanyoung** [activerecord-hackery/ransack#588]
"zh" is not a valid locale in [I18n](https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale). If user set "zh" in `Rails.locale` then Rails raises errors. Hence the file zh.yml will never be used.

The existing [zh.yml](https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/locale/zh.yml) file contains Simplified Chinese, which corresponds to [zh-CN.yml](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/zh-CN.yml) in I18n.

**Comment by jonatack** [comment]
Thanks! Would you like to make a pull request?

**Comment by ethanyoung** [comment]
Sure, I will do it.

On 19 Sep 2015 9:38 am, Jon Atack <notifications@github.com> wrote:
Thanks! Would you like to make a pull request?

---
