### ISSUE TITLE
Add support for alias_attribute

### ISSUE THREAD

**Issue by martndemus** [activerecord-hackery/ransack#589]
For example, I'm working on top of a legacy database which has all it's column names in german. I use `alias_attritbute` to map english names to the german column names. If I were to use Ransack I would have to support using the german attributes as query params.

With this example:

```ruby
class Location < ActiveRecord::Base
  self.table_name = 'orte'
  alias_attribute :code, :bezeichnung
end
```

The request `/api/locations?q[code_eq]=bremen` will not work. As it will construct the query as `where orte.code = 'bremen'`, while it should be translated to `where orte.bezeichnung = 'bremen'` .

**Comment by jonatack** [comment]
Hello @martndemus, thank you for highlighting this. It seems like an edge case feature request rather than a bug with the current code. I do not plan to work on this feature request, but you are more than welcome to make a pull request to add it if it is worthwhile to you. Cheers!
