### ISSUE TITLE
Ransack with will_paginate not working

### ISSUE THREAD

**Issue by puneetpandey** [activerecord-hackery/ransack#591]
Hi,

I am using ransack in one of my project. It works great. However, if I try to add pagination on search results, search term vanishes as I move to page 2
Gem details:
Ruby: 1.9.3
Rails: 3.2.11
Ransack: 1.7.0
Below is my code snippet:

    #{PATH_TO_APP}/config/initializers/ransack.rb
    Ransack.configure do |config|
      config.search_key = :query
    end

    #config/routes.rb
    namespace :abc
      resources :acts do
        collection do
          match 'search' => 'acts#search', via: [:get, :post], as: :search
        end
      end
      root to: 'home#index'
    end

    #app/controllers/abc/home_controller.rb
    def index
      @search = Act.ransack(params[:query])
    end

    #app/views/abc/home/index.html.erb
    search_form_for @search, url: search_abc_acts_path, html: {method: :post} do |f|
      ##logic from railscasts episode
    end

    #app/controllers/abc/acts_controller.rb
    def index
      @search = Act.ransack(params[:query])
      @results = @search.result.paginate(page: params[:page], per_page: ITEMS_PER_PAGE)
    end
    def search
      index
      respond_to do |format|
        format.html { render action: :index }
      end
    end

    #app/views/abc/acts/index.html.erb
    will_paginate @results

**Comment by jonatack** [comment]
I'm closing this for the moment as this doesn't seem to be a bug in Ransack and not all of the code needed to reproduce it is provided (the models and views are missing). If you provide a full gist that allows us to reproduce what you are doing and that shows the issue to be a bug in Ransack, this can be re-opened. Thanks!
