### ISSUE TITLE
Parameter `1` automatically translated to `true`

### ISSUE THREAD

**Issue by adisos** [activerecord-hackery/ransack#593]
My workaround:
tag_id = 1 if tag_id == true

**Comment by sjaveed** [comment]
Nice.  An alternate workaround (which I just put in place before looking here) is to pass in values as floats:
```ruby
class Post < ActiveRecord::Base
  scope :with_value, -> (val) { where(field_with_value: val.to_i) }

  def self.ransackable_scopes (auth_object = nil)
    %i/with_value/
  end
end
```
Use ransack like so:
```ruby
  Post.ransack({ with_value: 1.0 }).results
```

**Comment by avit** [comment]
I think the plan should be to require Array for scope params without converting types, otherwise the value is just true/false for including the scope or not. See my comments on #509.

**Comment by mostafa-zahran** [comment]
Another workaround is to make scope parameter as an optional parameter with default value 1 in case of ransack hash is dynamically created or stored in DB

**Comment by seanfcarroll** [comment]
Closed by https://github.com/activerecord-hackery/ransack/pull/742
