### ISSUE TITLE
Ransack silently fails when the field is missing

### ISSUE THREAD

**Issue by firedev** [activerecord-hackery/ransack#595]
I have spent almost a day on this. I had search by 'title_or_body_cont' and removed `body` attribute from the table.

It simply stopped searching silently swallowing errors. I couldn't figure it out, was comparing branches, gem versions, and only after I have compared tables I have figured out that the field is missing.

Please raise an error. Thank you.

**Comment by jonatack** [comment]
Hi @firedev, please read the [documentation](https://github.com/activerecord-hackery/ransack/wiki/Configuration) before filing issues :smiley: Thank you :wink:

**Comment by firedev** [comment]
I see, thanks, maybe it would make sense to reverse the default then.

**Comment by jonatack** [comment]
That would break existing apps on a large install base (2M+ downloads), so
it would require a deprecation warning and period, and then a major version
release.
