### ISSUE TITLE
Mongoid 5 querying scope is using wrong context

### ISSUE THREAD

**Issue by sbounmy** [activerecord-hackery/ransack#597]
Given I have the following code :
```ruby
class User
 scope :author -> { where(author: true) }
end

class Article
 scope :authored -> {
  author_ids = User.author.pluck(:id)
  where(author_id.in: author_ids)
 } 
end
Article.ransack(authored: true).result #is empty
```

After debugging through ```authored``` scope, I noticed ```User.author.pluck(:id)``` uses the *wrong context*:
```
{"find"=>"articles", "filter"=>{"author"=>true}}
# instead of {"find"=> "users", "filter" => {"author" => true}}
```
In pry scope#authored :
```cli
User.last
#<Article _id: 56090792408ff12cc100005a
```
This happened with mongoid 5, I hope @Zhomart can give me an insight so I can PR this :)

**Comment by Zhomart** [comment]
Ransack is initially was implemented to support ActiveRecord only. Basically what I did is I've copied all classes that uses ARs unique syntax that is not supported by Mongoid into `lib/ransack/adapters/mongoid` and tried to add similar behaviour. 
For example ransack uses Arel's Attributes. You can find immitation of Arel's attributes in `lib/ransack/adapters/mongoid/attributes`.
Also Arel has thingy called `Predications` that doesn't exist in Mongoid. It's also immitated.

Let me know if you have questions.

**Comment by sbounmy** [comment]
thanks @Zhomart , I actually decided to move away from ransack for mongoid.
While doing so, my bug still appear, it is actually a mongoid 5 issue AFAIK.
For those interested here is the mongoid issue: https://jira.mongodb.org/browse/MONGOID-4159
