### ISSUE TITLE
Custom ransacker with a formatter and not_in not working correctly

### ISSUE THREAD

**Issue by yan-hoose** [activerecord-hackery/ransack#601]
I ran into an issue with a custom ransacker that has a formatter and the `not_in` predicate.
Here is a test case:

``` ruby
gem 'activerecord', '4.2.4'
gem 'ransack', '1.7.0'
gem 'sqlite3'
require 'active_record'
require 'ransack'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :projects, force: true do |t|
    t.integer :type_id
  end
end

def get_array_of_type_ids
  [1, 2, 5]
end

class Project < ActiveRecord::Base
  ransacker :type_id, formatter: proc { |v| get_array_of_type_ids } do |parent|
    parent.table[:type_id]
  end
end

class BugTest < Minitest::Test
  def test_type_id_ransacker
    sql = Project.ransack({type_id_in: 5}).result.to_sql
    assert_equal "SELECT \"projects\".* FROM \"projects\" WHERE \"projects\".\"type_id\" IN (1, 2, 5)", sql

    sql = Project.ransack({type_id_not_in: 5}).result.to_sql
    assert_equal "SELECT \"projects\".* FROM \"projects\" WHERE (\"projects\".\"type_id\" NOT IN (1, 2, 5))", sql
  end
end
```

Basically the formatter takes a type_id and finds other types based on some business logic. It works fine with the `type_id_in` predicate but not with `type_id_not_in`.

Instead of the expected SQL of:

``` sql
SELECT "projects".* FROM "projects" WHERE ("projects"."type_id" NOT IN (1, 2, 5));
```

it returns:

``` sql
SELECT "projects".* FROM "projects" WHERE ("projects"."type_id" NOT IN (NULL));
```

`not_in` works fine on other columns where I don't have a custom ransacker set.

I'm using:
- Rails 4.2.4
- Ruby 2.2.3
- Ransack 1.6.6 and tried also 1.7.0 and master branch
- Using PostgreSQL 9.4 but the test fails also with SQLite
- Ubuntu Linux 15.04

**Comment by avit** [comment]
I'm not sure if there is still an underlying bug here, but "in" and "not_in" should normally expect an array.

**Comment by yan-hoose** [comment]
The formatter will turn the input into an array, but it does work without an array too.

**Comment by ahoernecke** [comment]
Having the same issue on:
Rails 4.2.5
Ruby 2.2.2
Ransack 1.4.1+
Postgres 9.5

Interestingly the same configuration worked fine on Rail 4.0 with Ransack 1.2.3...

**Comment by ajporterfield** [comment]
I just ran into this same issue.  Not exactly sure why, but using not_in_all worked for me.
