### ISSUE TITLE
Matching with special characters 

### ISSUE THREAD

**Issue by JWesorick** [activerecord-hackery/ransack#606]
Is there a way to match an attribute ignoring special characters? 

For example lets say in the database I have a place `Place.create(name: "Jake's Place")` and then I want it to be returned when I have a query `name_cont: 'Jakes Place'`

**Comment by jonatack** [comment]
Hi @JWesorick, this is up to you to handle, either in Ruby or your SQL. There are several ways to go about it. I've provided examples in replies to various Ransack issues over the years, don't hesitate to look through them. Cheers.
