### ISSUE TITLE
Loading all locales should be configurable

### ISSUE THREAD

**Issue by why-el** [activerecord-hackery/ransack#607]
One consequence of ransack's loading of all its I18n YAML files is that all of them end up being added to `I18n.available_locales`. This will break for apps that rely on `I18n.available_locales` to hold the primary locales of the application. 

For instance in our app we loop over `I18n.available_locales` to show a dropdown of languages for users to translate the app to (similar to what Airbnb does). 

I suggest we add a simple configuration option that instructs Ransack to load only its translations that match locales returned by `I18n.available_locales`.

**Comment by jonatack** [comment]
Hi @why-el, thanks for the issue. When I run `I18n.available_locales` to reproduce what you are seeing in an app, it returns only the locales in `app/config/locales` and not all the Ransack locale files. Could you provide more information to reproduce your issue and I'll re-open this and have a look? See the Contributing Guide for what would help us to reproduce. Thanks.
