### ISSUE TITLE
Order of search parameters adversely affects the SQL generated

### ISSUE THREAD

**Issue by laserlemon** [activerecord-hackery/ransack#608]
I was able to demonstrate the issue in [this Gist](https://gist.github.com/laserlemon/3f68d1901e30de54a4e1). If [lines 76 and 77](https://gist.github.com/laserlemon/3f68d1901e30de54a4e1#file-ransack_bug_demo-rb-L76-L77) are swapped, one permutation will produce invalid SQL and the other behaves as expected.

**Comment by gariggio** [comment]
I have the same problem!

**Comment by jonatack** [comment]
Thanks for the helpful gist, that makes all the difference in reproducing the issue.

The issue might be only because you're missing a join on `comments`.

Here's [my gist that works](https://gist.github.com/jonatack/cd201e6817221b214d9b).

**Comment by jonatack** [comment]
PS - I ran the gist with Ransack master, Ruby 2.3.0, Active Record 5.0.0.alpha, Arel 7.0.0.alpha and SQLite3 1.3.11.
