### ISSUE TITLE
undefined method `name' for nil:NilClass error

### ISSUE THREAD

**Issue by AnnaErshova** [activerecord-hackery/ransack#609]
Just playing around with a simple rails app with only one model that I have scaffolded just for this project. 

Inside a `search_form_for`, I have a  `<%= f.label :name_cont %>`  and  `<%= f.text_field :name_cont%>`  -- basically as per RailsCasts and the ReadMe. 

I get  `undefined method name' for nil:NilClass` error.  My model does have a `name` column and the `<%= sort_link(@q, :name, "Name") %>` filter works fine. 

I run Ruby 2.2.0, Rails 4.2.0, and Ransack 1.7.0.

Any ideas? Thanks.

**Comment by jonatack** [comment]
Hi @AnnaErshova, could you please provide the information needed to reproduce your exact issue? Please see the Contributing Guide. I'm not sure that it's a bug with Ransack. I'll re-open this when you've given enough info to reproduce what you're seeing. OK? Thanks :smiley:

**Comment by AnnaErshova** [comment]
@jonatack I did fix it, but I think it was something with Ransack. It went away after I updated command tools I think (that was a while back). Just keep an eye out for it if someone else reports it. Thanks!

**Comment by shlajin** [comment]
Just noticed that occurs after `@search.build_condition` call.

E.g.
```
@search = model.search(params[:q])
@search.name_cont # ok
@search.build_condition
@search.name_cont # raises nil pointer error
```

**Comment by StandardNerd** [comment]
It's 2019 and It's still reproduceable.
