### ISSUE TITLE
Force sorting by one field

### ISSUE THREAD

**Issue by shir** [activerecord-hackery/ransack#610]
Hi. Is there any way to force sort by one column and custom by other? So results should be always sorted at first by one column, and next column is user defined.

I've tried next:
```rb
if @q.sorts.blank?
  @q.sorts = ['is_priority desc', 'due_date desc']
else
  @q.sorts.insert 'is_priority desc'
end
```
but have no success. If no user sorting is provided it works as expected, but if user sort by some field, `is_priority` is not applied to it.

This one doesn't work too:
```rb
@q = Model.order('is_priority desc').search(params[:q])
@records = @q.result
```
In this case sorting by `is_priority` is just skipped and sorting from ransack is applied.

**Comment by shir** [comment]
Sorry. It should be
```
@q.sorts.insert 0, 'is_priority desc'
```
Got error on this. After source investigating found worked solution:
```
if @q.sorts.blank?
  @q.sorts = ['is_priority desc', 'due_date desc']
else
  @q.sorts.insert 0, Ransack::Nodes::Sort.extract(@q.context, 'is_priority desc')
end
```
Not sure if it's a best way.

**Comment by jonatack** [comment]
Hi @shir, not super sure what you what to do, but perhaps you could do something like:

```ruby
@q.result.reorder(:default_order, :user_order)
```
In other words:
```ruby
@q.result.reorder(is_priority: :desc, due_date: :desc)
```
