### ISSUE TITLE
Missing :en locales

### ISSUE THREAD

**Issue by jinixdme** [activerecord-hackery/ransack#611]
Hi, I'm using ransack v1.6.5 through ActiveAdmin v1.0.0.pre2 (Rails 3.2.21).
To avoid translation_missing error I had to add the following locales:

en:
  ransack:
    predicates:
      equals: equals
      greater_than: greater than
      less_than: less than
      contains: contains
      starts_with: starts with
      ends_with: ends with

Regards,
Jens

**Comment by jonatack** [comment]
It looks like you are only changing the ones ending with `_than` and `_with`.

I believe it is an issue being introduced by ActiveAdmin changing the predicate names so it may be more useful to report the issue there.

Thanks.
