### ISSUE TITLE
Upgrading MetaSearch to Ransack

### ISSUE THREAD

**Issue by billxinli** [activerecord-hackery/ransack#613]
I am in the process of upgrading MetaSearch to Ransack, for a rather large Application, therefore I can not just replace the MetaSearch Gem.

In the process of upgrading, I discovered that both gems uses `sort_link` as a helper method. It is a sound solution to load Ransack before meta_search in the Gemfile, so that we can still take advantage of `sort_link` from MetaSearch?

**Comment by jonatack** [comment]
Hi @billxinli, I doubt that Ransack was written with any plan for running at the same time as MetaSearch. You could change the `sort_link` name with a monkey-patch or fork of one of the two gems.

**Comment by jonatack** [comment]
Closing this as it is outside of Ransack's intended scope. Thanks for your understanding.

**Comment by billxinli** [comment]
This is great pointer! Thanks.

**Comment by jonatack** [comment]
I'm probably going to go to programmer hell for that suggestion.
