### ISSUE TITLE
PG::UndefinedFunction: ERROR:  could not identify an equality operator for type polygon

### ISSUE THREAD

**Issue by JWesorick** [activerecord-hackery/ransack#615]
I added a column on one of my tables of type 'polygon' and now I get this error on all ransack queries that include that table and `result(distinct: true)`:
```
PG::UndefinedFunction: ERROR:  could not identify an equality operator for type polygon
```

**Comment by jonatack** [comment]
You've provided no information on your environment, nor your stack trace. Please see Contributing Guide about needed information for reporting issues. Closing this until we have more to go on. Thanks.
