### ISSUE TITLE
search a eager_load relation cause a duplicate LEFT OUTER JOIN

### ISSUE THREAD

**Issue by kikyous** [activerecord-hackery/ransack#621]
```ruby
Keyword.eager_load(:trendings).search(params[:q]).result
```

SELECT `keywords`.`id` AS t0_r0, `keywords`.`name` AS t0_r1, `keywords`.`target` AS t0_r2, `keywords`.`user_id` AS t0_r3, `keywords`.`created_at` AS t0_r4, `keywords`.`updated_at` AS t0_r5, `keywords`.`ranking` AS t0_r6, `keywords`.`trend` AS t0_r7, `keywords`.`google_trends` AS t0_r8, `keywords`.`url` AS t0_r9, `keywords`.`status` AS t0_r10, `trendings`.`id` AS t1_r0, `trendings`.`ranking` AS t1_r1, `trendings`.`keyword_id` AS t1_r2, `trendings`.`created_at` AS t1_r3, `trendings`.`updated_at` AS t1_r4 FROM `keywords` LEFT OUTER JOIN `trendings` ON `trendings`.`keyword_id` = `keywords`.`id` LEFT OUTER JOIN `trendings` `trendings_keywords` ON `trendings_keywords`.`keyword_id` = `keywords`.`id` WHERE (`keywords`.`target` = 'buyextracts.com' AND `trendings`.`created_at` >= '2015-09-30 16:00:00' AND `trendings`.`created_at` <= '2015-12-31 15:59:59')

**Comment by kikyous** [comment]
I can do this with following code
```ruby
Keyword.joins(:trendings).search(params[:q]).result.eager_load(:trendings)
```
SELECT `keywords`.`id` AS t0_r0, `keywords`.`name` AS t0_r1, `keywords`.`target` AS t0_r2, `keywords`.`user_id` AS t0_r3, `keywords`.`created_at` AS t0_r4, `keywords`.`updated_at` AS t0_r5, `keywords`.`ranking` AS t0_r6, `keywords`.`trend` AS t0_r7, `keywords`.`google_trends` AS t0_r8, `keywords`.`url` AS t0_r9, `keywords`.`status` AS t0_r10, `trendings`.`id` AS t1_r0, `trendings`.`ranking` AS t1_r1, `trendings`.`keyword_id` AS t1_r2, `trendings`.`created_at` AS t1_r3, `trendings`.`updated_at` AS t1_r4 FROM `keywords` INNER JOIN `trendings` ON `trendings`.`keyword_id` = `keywords`.`id` WHERE (`keywords`.`target` = 'buyextracts.com' AND `trendings`.`created_at` >= '2015-09-30 16:00:00' AND `trendings`.`created_at` <= '2015-12-31 15:59:59')

but maybe it can be more smart

**Comment by jonatack** [comment]
Hi @kikyous, could you please give us more information (including Rails, Ruby, and db versions) to reproduce your environment? Please see the CONTRIBUTING.md file for more information about creating bug reports. Closing, will re-open when actionable info is provided. Thanks!
