### ISSUE TITLE
Polymorphic searchs (reverse)

### ISSUE THREAD

**Issue by manoelneto** [activerecord-hackery/ransack#629]
Hi,

following this link https://github.com/activerecord-hackery/ransack/wiki/Polymorphic-searches we can get all Location of house type ... but how do the oposite?

I have this model

```
class User < ActiveRecord::Base
  has_many :comments, as: :resource, :class_name => 'ActiveAdmin::Comment'
end

class ActiveAdmin::Comment
  # this model has body field (text)
  belongs_to :resource, polymorphic: true
end
```

I tried to do User.ransack({comments_of_User_type_body_cont: 'testing'}).result.to_sql and I got "SELECT \"users\".* FROM \"users\""

What I`m doing wrong?

**Comment by avit** [comment]
You could try debugging with `Ransack.options[:ignore_unknown_conditions]` if it shows the error.

Are you sure you need the "User_type" when searching from User? I think you only need that if searching back from Comment (for "resource_of_User_type")
