### ISSUE TITLE
ransack overwrite any ordering

### ISSUE THREAD

**Issue by aka47** [activerecord-hackery/ransack#63]
Lets say you have a rating which belongs to a user.

```
Rating.joins(:user).order("rateable_id ASC").ransack.result.to_sql 
"SELECT `ratings`.* FROM `ratings` INNER JOIN `users` ON `users`.`id` = `ratings`.`user_id`"
```

but should result in:

```
"SELECT `ratings`.* FROM `ratings` INNER JOIN `users` ON `users`.`id` = `ratings`.`user_id` ORDER BY rateable_id ASC"
```

so every order is overwriten/removed from ransack. We need more complicated ordering and it does not work with ransack right now.

thanks

**Comment by vigneshacker** [comment]
+1

**Comment by kirqe** [comment]
Any updates on this to keep the default order? The original query might have no ordering at all `where(id: scope1.select(:id) + scope2.select(:id))`
