### ISSUE TITLE
What does the I18n features offer?

### ISSUE THREAD

**Issue by jmuheim** [activerecord-hackery/ransack#631]
I asked this question already on StackOverflow, but it seems nobody knows what the I18n features of ransack really offer.

http://stackoverflow.com/questions/34307149/i18n-my-ransack-search-fields-are-not-translated

So: I'd like the form fields to be translated automatically, but it seems they aren't.

    = search_form_for q
      = f.input :name_cont # I'm using simpleform gem for forms

Result:

![image](https://cloud.githubusercontent.com/assets/1814983/11835916/3bb32c32-a3d7-11e5-97b7-321d727c6294.png)

As far as I understand, I would expect the search field's label to be something like "Name contains", right?

At the moment, I'm doing something like `label: "#{User.human_attribute_name :name} #{t('ransack.predicates.cont')}"`, but this feels awkward.

**Comment by avit** [comment]
Some info is available in the wiki on [Form Customization][1]. Is it not working?

[1]: https://github.com/activerecord-hackery/ransack/wiki/Form-Customization
