### ISSUE TITLE
Didn't understand looking at the docs how I can do a Case Insensitive search with objects

### ISSUE THREAD

**Issue by andre0799** [activerecord-hackery/ransack#635]
neither this: https://github.com/activerecord-hackery/ransack/pull/405
or the docs explain very well how I can do a case insensitive search using "i_cont" when I want to send a full object as a parameter. Also is that even implemented?

On my case I wanna do a search like this
``` User.ransack(params[:q]) ```

where 
``` params[:q] = {"id_eq"=>"", "name_start"=>"andre", "real_name_start"=>"", "provider_user_credential_email_start"=>""} ````

any help is appreciated, I'm a beginner with Ruby, and I've been messing around with this for hours.

Thanks!

**Comment by andre0799** [comment]
I've tried this ``` params[:q][:name_start_i_cont] = params[:q].delete :name_start ``` but it didn't work
Also when I applied ```.result.to_sql ```after running the code above, it was interpreted to only to  ``` SELECT `users`.* FROM `users` ```

**Comment by jonatack** [comment]
@andre0799 Perhaps have a look at #218 or search the repo for "citex".

**Comment by jonatack** [comment]
Or #57.
