### ISSUE TITLE
Problem when using multiple DB-Connections

### ISSUE THREAD

**Issue by fpauser** [activerecord-hackery/ransack#64]
Using ransack & squeel I get failures, when using a second db-connection and specifiying the table-name:

The model:

``` ruby
class Train < ActiveRecord::Base
  establish_connection "#{Rails.env}_db2"
  self.table_name  = 'viewTrain'
end
```

This works:

``` ruby
Train.where(:trainDateIn.gteq => '2012-01-01')
```

This fails:

``` ruby
Train.search({"trainDateIn_gteq" => "2012-01-01"})
```

My workaround:

``` ruby
def index
  search = params[:q]
  where  = {}
  unless search.blank?
    %w(
      trainDateIn_gteq trainDateIn_lteq
    ).each do |search_param|
      if search[search_param]
        key = search_param.sub(/^(.*)_([^_]+)$/,"\\1").to_sym
        mod = search_param.sub(/^(.*)_([^_]+)$/,"\\2").to_sym
        where[key.send(mod)] = search[search_param]
      end
    end
  end
end
```

**Comment by seanfcarroll** [comment]
Probably pushing the limits of what Ransack should be doing.

**Comment by chagar** [comment]
A workaround for this issue is to create a View in your main database which simply selects from the table in the other database. The view should have the same name as the table.

Since ransack only reads from the database, this should work in all circumstances, not requiring an updateable view.
