### ISSUE TITLE
Sort link for SQL function fields

### ISSUE THREAD

**Issue by pastullo** [activerecord-hackery/ransack#651]
I would like to add sorting, using the sort_link feature, to sort by fields that i get from SQL directly

I opened a stackoverflow questions if any one can help:
http://stackoverflow.com/q/35945893/1490947

My query looks like this: 
`@q = Order.group(:suburb).select("suburb, COUNT(*) as count, SUM(total) as total, AVG(total) as average").ransack(params[:q])`

Using `sort_link @q, :total` does not work

**Comment by jonatack** [comment]
Hi @pastullo please refer to the wiki for ransackers and custom predicates. Thanks.
