### ISSUE TITLE
Ransack issue with find_in_batches

### ISSUE THREAD

**Issue by tomdracz** [activerecord-hackery/ransack#652]
I'm using ransack to search for results on my model and then try to call find_in_batches on the result.

When i call find_in_batches though, I'm only getting chunk of results.

Did a further digging and it seems quite weird.

```
search.results.size -> 2501
search.results.first(2501).size -> 2500 (?)
search.results.first(2502).size -> 2501
search.results.find_in_batches(batch_size: 200) -> returns 13 batches, but after getting to batch 6 it breaks because the batch.size is 199
```

However if I do:

```
@ids = search.results.map(&:id)
Model.where(id: @ids).find_in_batches(batch_size: 200)
```

All works as expected. Any clues?

**Comment by avit** [comment]
After you call `.results` you have an `ActiveRecord::Relation` so it's out of the hands of Ransack beyond there. You can try calling `.results.to_sql` to try and debug the query, it might be affected by some GROUP BY or HAVING clauses. The `first` and `find_in_batches` methods should just add LIMIT and OFFSET so try those and see what happens.
