### ISSUE TITLE
Add Predicate for HABM with String

### ISSUE THREAD

**Issue by rsiddle** [activerecord-hackery/ransack#656]
I cannot find any documentation to support has and belongs to many relationships via strings.

I'm looking to use the add_predicate initalizer rather than a form helper.

A User that can have multiple Roles (using the Rolify gem).

I'm looking to check to see if a user has any of the roles, separated by an input box with a comma (if more than one).

Tables
---------
users [:id]
users_roles [:user_id, :role_id]
roles [:id]

I'd like to search by the role name.

<img width="1355" alt="screen shot 2016-03-22 at 14 24 07" src="https://cloud.githubusercontent.com/assets/18415/13954707/d509024a-f039-11e5-98ce-a54cf2868933.png">

```
# This seems to work by taking the incoming value and splitting it into an array
Ransack.configure do |config|
  config.add_predicate 'all with split',
    arel_predicate: 'in',
    formatter: proc { |v| v.split(',') },
    validator: proc { |v| v.present? },
    compounds: false,
    type: :string
end
```

**Comment by jonatack** [comment]
Ransack works by providing access to Arel predicate methods and you can write any custom query with Arel. Have you searched on previous issues? Perhaps one like this: https://github.com/activerecord-hackery/ransack/issues/164.
