### ISSUE TITLE
Could not use Ransack with temporary table

### ISSUE THREAD

**Issue by bolshakov** [activerecord-hackery/ransack#657]
Hello,

I'm trying to use ransack with temporary table on PostgreSQL and get the following error:

``` ruby
RuntimeError: No table named movies exists
```

The problem is in [this check](https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters/active_record/context.rb#L29):

``` ruby
unless schema_cache.send(database_table_exists?, table)
  raise "No table named #{table} exists."
end
```

Method `#database_table_exists?` works only with tables, views, and materialized views. But it does not work with temporary tables.

We can fix the issue by just removing this check. In case of missing table on PostgreSQL, it will fail with clear error message:

``` ruby
=> PG::UndefinedTable: ERROR:  relation "movies" does not exist
```

My environment:
- ransack (1.6.6)
- activerecord (4.2.5)

**Comment by seanfcarroll** [comment]
The **database_table_exists?** is a wrapper over the Rails `:table_exists?` or  `:data_source_exists?` methods. 

You can see the code [here](https://github.com/activerecord-hackery/ransack/blob/442e5ad2b5934ac5f5ad5f0b21885a3a466bbf75/lib/ransack/adapters/active_record/context.rb#L201-L207)
