### ISSUE TITLE
ransack_alias doesn't store value

### ISSUE THREAD

**Issue by shir** [activerecord-hackery/ransack#658]
Using last from master (50af43e3a75e0c8a57b315deb035114d11c50c6b). Added `ransack_alias` for several attributes. And it works as expected, but previously inputted value is not shown. For example:

Model
```rb
class Task < ActiveRecord::Base
  ransack_alias :content, :description_or_notes
end
```
View
```erb
<%= search_form_for @q do |f| %>
  <%= f.label :content_cont, "Content" %>
  <%= f.search_field :content_cont %>
  <%= f.submit %>
<% end %>
```

I enter `Test` in "Content" field, click "Search" button and got tasks which contains `Test` in description or notes. But "Content" field now is empty.

If I use `description_or_notes_cont` directly for field name without alias functionality then all works ok.

**Comment by gurgelrenan** [comment]
I have the same problem here :/

**Comment by gurgelrenan** [comment]
In my case, a `has_one` association don't return any results. 

Model 

```ruby
class Responsible < ActiveRecord::Base
  has_one :profile
end

class Profile < ActiveRecord::Base
  # has a name attribute
end
```

In the lasted released version `Version 1.7.0 - 2015-08-20` The following code works

View (this view returns `Responsible` records)

```ruby
<%= f.label :profile_name_cont %>
<%= f.search_field :profile_name_cont, class: "form-control" %>
```

Now when I update Ransack to the version at master branch, this code has broken.

**Comment by jonatack** [comment]
Hi @shir, could you please give us more information (including Rails, Ruby, and db versions) to reproduce your environment? Please see the [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) file for more information about creating bug reports. Closing, will re-open when actionable info is provided. Thanks!

Hi @gurgelrenan, same thing, and please file your own issue as yours is different from the OP one. Thanks!

**Comment by minhdanh** [comment]
I'm having this same issue. Using ransack_alias, the input is not displayed after submitted.
My environment:

Ruby 2.3.5
Rails 5.2.0
Ransack 2.0.0
(Not using simpleform, activeadmin)

Model:

```
class Guest < ApplicationRecord
  ransack_alias :search, :name_or_phone_or_email
```

View:

```
    = search_form_for @q, url: admin_guests_path do |f|
      .row
        .col-sm-2
          .form-group
            = f.label :search, class: "control-label"
            = f.search_field :search_cont, class: "form-control"
```

**Comment by seliverstov-maxim** [comment]
👍 Why issue is closed?
