### ISSUE TITLE
Sql Literal with time based column sorting 

### ISSUE THREAD

**Issue by railsfactory-madhusudhan** [activerecord-hackery/ransack#660]
Do we have any option to add datetime in sqlliteral, I've a dynamic function which is used for sorting

```
ransacker field do
   Arel::Nodes::SqlLiteral.new("date(#{table_name}.#{field})")
end
```

but while working on timezone in different place it is not fetching the data correctly. I want something sort of this which should be able to consider time also

```
ransacker field do
   Arel::Nodes::SqlLiteral.new("datetime(#{table_name}.#{field})")
end
```

**Comment by jonatack** [comment]
Please don't cross post (see #99). Thanks!
