### ISSUE TITLE
Possible to have multiple predicates? 

### ISSUE THREAD

**Issue by MarkMurphy** [activerecord-hackery/ransack#662]
I'm wondering if there's a way to do something like this:

```ruby
<%= form.text_field :name_cont_or_id_eq %>
```

The query would try to match on records where the `name` field contains the query or where the `id` field is equal to the query.

**Comment by fidalgo** [comment]
Yes you can, just check the advanced search in provided example: http://ransack-demo.herokuapp.com/users/advanced_search

**Comment by ened** [comment]
Had the same problem, yet wanted a stable query parameter (`q`): 

```
.ransack({title_cont: params[:q], id_eq: params[:q]}, { grouping: Ransack::Constants::OR })
```
