### ISSUE TITLE
undefined method `ransacker'

### ISSUE THREAD

**Issue by charliefurniss** [activerecord-hackery/ransack#664]
Hey

I'm trying to create a ransack search form that allows users to search for a string or an integer. Following the suggestion [here](https://github.com/activerecord-hackery/ransack/wiki/using-ransackers) I am trying to use a ransacker to convert the integer into a string in the controller as follows:

`ransacker :id do
  Arel.sql("to_char(id, '9999999')")
end`

However, although I can get ransack to work with a search, it won't recognise the ransacker method, and I get the following error:

undefined method `ransacker'

And I can't understand why this is.

Any suggestions most welsome.

**Comment by jonatack** [comment]
Hi @charliefurniss, can you please provide a gist with a script that reproduces the error and the other missing info mentioned in the Contributing Guide and README?

See the [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) file for more information and a template for creating bug reports in a self-contained gist.

Closing, will re-open when actionable info is provided. Thanks!

**Comment by charliefurniss** [comment]
Hi Jon

Thanks for the message. Apologies for not reading the Contributing Guide. I
will provide the relevant info and resubmit.

Thanks

On 19 April 2016 at 22:39, Jon Atack <notifications@github.com> wrote:

> Hi @charliefurniss <https://github.com/charliefurniss>, can you please
> provide a gist with a script that reproduces the error and the other
> missing info mentioned in the Contributing Guide and README?
>
> See the CONTRIBUTING.md
> <https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md>
> file for more information and a template for creating bug reports in a
> self-contained gist.
>
> Closing, will re-open when actionable info is provided. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/activerecord-hackery/ransack/issues/664#issuecomment-212140592>
>



-- 
---

Charlie Furniss
Web Developer
charliefurniss.com

**Comment by zishe** [comment]
same bug
