### ISSUE TITLE
ActiveAdmin filter in simple setup leads to Ransack-Search crash

### ISSUE THREAD

**Issue by besi** [activerecord-hackery/ransack#673]
**Please note**: I did post this to the active_admin repository, but haven't heard anything since I created the issue in February. ActiveAdmin uses Ransack under the hood so the issue might be in better hands here in the ransack repository. I am not entirely sure how to best address the problem but in order to try to make some progress on the matter I am cross-posting the issue here.

Please see: activeadmin/activeadmin#4326

----

I have a simple setup with only one model which I want to manage in ActiveAdmin. I do have approx 9800 entries in the DB.

When I deploy this to heroku then I get an error (See whole stacktrace below).

>     undefined method `catalog_nr_contains' for #<Ransack::Search:0x007fd29d3681f8>

I then explicitly included all the filters except `catalog_nr` and then I just get the next error similar to the initial one:

>    ActionView::Template::Error (undefined method `created_at_gteq' for #<Ransack::Search:0x007facd42daf68>):

### ActiveAdmin Resource:

```ruby
ActiveAdmin.register ImportObject do
  permit_params :catalog_nr, :collection, :address
end
```

## Model
```ruby
class ImportObject < ActiveRecord::Base
end
```

## Schema

```ruby

  create_table "import_objects", force: :cascade do |t|
    t.string   "catalog_nr",       limit: 255
    t.string   "collection",       limit: 255
    t.datetime "created_at",                     null: false
    t.datetime "updated_at",                     null: false
    t.string   "address",          limit: 255
    t.string   "city",             limit: 255
    t.string   "name_de",          limit: 255
    t.string   "collected_at",     limit: 255
    t.string   "year",             limit: 255
    t.string   "donor",            limit: 255
    t.string   "species_fr",       limit: 255
    t.string   "species",          limit: 255
    t.string   "quantity",         limit: 255
    t.string   "order",            limit: 255
    t.string   "first_name",       limit: 255
    t.string   "origin",           limit: 255
    t.text     "remarks",          limit: 65535
    t.string   "sex",              limit: 255
    t.string   "systematics",      limit: 255
    t.string   "age",              limit: 255
    t.string   "condition",        limit: 255
    t.string   "storage_location", limit: 255
    t.string   "group",            limit: 255
  end

```

## excerpt from Gemfile

```yaml
GEM
  remote: https://rubygems.org/
  specs:
    # ...
    ransack (1.7.0)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.2)
    # ...    
    activeadmin (1.0.0.pre2)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails
    # ...    
    formtastic (3.1.3)
      actionpack (>= 3.2.13)
```

Internal reference `#8`

**Comment by jonatack** [comment]
Hi @besi !

Could you please provide more information to reproduce your issue? I don't use ActiveAdmin. If this is an error concerning Ransack, can you please provide a stand-alone, non-ActiveAdmin gist with a script that reproduces the error?

Please see the [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) file for more information and a template for creating bug reports.

Closing for now, happy to re-open if actionable info is provided. Thanks!
