### ISSUE TITLE
includes causes invalid count query

### ISSUE THREAD

**Issue by u007** [activerecord-hackery/ransack#675]
default activerecord.count need accomodate for join table,
example error being thrown:
PG::AmbiguousColumn: ERROR:  column reference "id" is ambiguous

SELECT COUNT(DISTINCT id) FROM "tableA" LEFT OUTER JOIN "tableB" ON "tableA"."id" = "tableB"."maker_id" 

my current work around is to run my own paginate with total_entries option:
example:
page_params[:total_entries] = @search.result.count("#{@model_class.table_name}.id").to_i

**Comment by jonatack** [comment]
H @u007! Could you please provide a standalone gist to reproduce your issue?

Please see the [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) file for more information and a template for creating bug reports.

Closing, happy to re-open if actionable info is provided. Thanks!
