### ISSUE TITLE
master branch attribute_select not show

### ISSUE THREAD

**Issue by nyrf** [activerecord-hackery/ransack#678]
When use master branch, attribute_select not show, predicate_select works.

```
<div class="form-inline">
<div class="form-group">
<%= f.attribute_fields do |a| %>
<%= a.attribute_select({}, :class => 'form-control') %>
<% end %>
<%= f.predicate_select({}, :class => 'form-control') %>
<%= f.value_fields do |v| %>
<%= v.text_field(:value, :class => 'form-control')%>
<% end %>
<%= link_to "remove", 'javascript:', class: "remove_fields btn btn-warning row_spacer" %>
</div>
<div class="row_spacer"></div>
</div>
```

**Comment by jonatack** [comment]
Hi! Could you please provide more information to reproduce your issue?

Please see the [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) file for more information and a template for creating bug reports.

Closing, will re-open when actionable info is provided. Thanks!
