### ISSUE TITLE
class << self ransackable scopes fails

### ISSUE THREAD

**Issue by jufemaiz** [activerecord-hackery/ransack#679]
I've recently been going through our codebase with Rubocop and found an interesting oddity.

http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Lint/IneffectiveAccessModifier

Shifting the recommended Class method for ransackable scopes to be within a class << self block along with a private access modifier:

```ruby
class Cat < ActiveRecord::Base
  class << self
    private

    def ransackable_scopes(auth_object  = nil)
      %i(pet wild)
    end
  end

  scope :pet, -> {  }
  scope :wild, -> {  }
end
```

I kept getting errors along the lines of:

```
undefined method `pet' for #Cat::ActiveRecord_Relation
```

However if I modified back to how it's shown these issues resolve:

```ruby
class Cat < ActiveRecord::Base
  scope :pet, -> {  }
  scope :wild, -> {  }

  def self.ransackable_scopes(auth_object  = nil)
    %i(pet wild)
  end
end
```

Any thoughts?

**Comment by jonatack** [comment]
Do these work?

```ruby
class Cat < ActiveRecord::Base
  scope :pet, -> {  }
  scope :wild, -> {  }

  class << self
    private
    def ransackable_scopes(auth_object  = nil)
      %i(pet wild)
    end
  end
end
```
```ruby
class Cat < ActiveRecord::Base
  scope :pet, -> {  }
  scope :wild, -> {  }

  def self.ransackable_scopes(auth_object  = nil)
    %i(pet wild)
  end

  private_class_method :ransackable_scopes
end
```

**Comment by jonatack** [comment]
Closing for now, more than happy to re-open if this is an issue with Ransack itself and not Ruby.

**Comment by jufemaiz** [comment]
@jonatack hmmmm. You may be onto something regarding Ruby. Upgraded to Ruby 2.3.1 and I can't recreate.
