### ISSUE TITLE
Ransack sorting deep associations is not working

### ISSUE THREAD

**Issue by safaa-alnablsi** [activerecord-hackery/ransack#680]
I have many to many relations between models:

```
model1 has many model2
model2 has many model3
model3 has one model4

```
sorting on attributes that come from model1 is working, but it didn't work neither for :

 `model2_attr` or `model2_first_model3_first_attr` or `model2_first_model3_first_model4_attr`

 I have a grid and I want the sort to be based on string field inside the model3, and it comes from the decorator not from the model.

**Comment by jonatack** [comment]
Hello!

Can you please provide a gist with a script that reproduces the error?

See the [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) file for more information and a template for creating bug reports in a self-contained gist.

Will re-open if actionable info is provided. Thanks!

**Comment by safaa-alnablsi** [comment]
No error nor exception, it's not sorting.
