### ISSUE TITLE
Ransack not working in tests.

### ISSUE THREAD

**Issue by jdguzman** [activerecord-hackery/ransack#681]
I'm trying to write some cucumber tests around some ransack searches and things don't seem to be working correctly.

In my development environment when I run the ransack search I get the following:

```shell
[1] pry(#<Dam::AssetsController>)> scope.search(name_contains: params[:q], description_contains: params[:q], tags_contains: params[:q], m: 'or').result
=> #<Mongoid::Criteria
  selector: {"active"=>true, "$or"=>[{"$or"=>[{"name"=>/nebula/i}, {"description"=>/nebula/i}]}, {"tags"=>/nebula/i}]}
  options:  {}
  class:    Dam::Asset
  embedded: true>
```

Running this same query in the test environment yields the folllowing:

```shell
[1] pry(#<Dam::AssetsController>)> scope.search(name_contains: params[:q], description_contains: params[:q], tags_contains: params[:q], m: 'or').result
=> #<Mongoid::Criteria
  selector: {"active"=>true}
  options:  {}
  class:    Dam::Asset
  embedded: true>
```

Why is it that the selector isn't getting created correctly?

EDIT: I'm getting the same behavior in rspec.

**Comment by jonatack** [comment]
I don't maintain the Mongoid adapter of Ransack, so it's up to the Mongo DB-using community.

If you are having the same problem using Active Record with Ransack, please let me know.

**Comment by jonatack** [comment]
Also, could you provide the versions info and a standalone gist to reproduce your issue? Please see [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) for more information and a bug report template to work from. Closing for now, will re-open if actionable info is provided. Thanks!

**Comment by jonatack** [comment]
Sorry, the info above would be enough, just the Ruby/Rails/Ransack versions are missing. The Mongoid adapter was working in with Mongoid 4 / Rails 4 but perhaps not other versions.
