### ISSUE TITLE
Customize params formatter

### ISSUE THREAD

**Issue by at-longhpv** [activerecord-hackery/ransack#683]
I tried to strip all params in params[:q] before query "search like" ransack but not working 
  config.add_predicate 'prev_cont', # Name your predicate
    arel_predicate: 'cont',
    formatter: proc { |v| v.strip },
    validator: proc { |v| v.present? },
    compounds: true,
    type: :string

**Comment by jonatack** [comment]
`params[:q]` is a query hash (`ActionController::Parameters` object that you can call `#to_unsafe_h` on) and manipulate directly.

**Comment by jonatack** [comment]
Hi @at-longhpv, `params[:q]` is a query hash you can manipulate directly.

In Rails 5, it's an `ActionController::Parameters` object that you can call `#to_unsafe_h` on to turn into a HWIA.
