### ISSUE TITLE
Rails 5 Deprecation

### ISSUE THREAD

**Issue by alejandrodevs** [activerecord-hackery/ransack#684]
In rails 5.0.0rc1 I'm getting this deprecation:

DEPRECATION WARNING: #table_exists? currently checks both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only check tables. Use #data_source_exists? instead.

**Comment by jonatack** [comment]
Until the next release is made, use the master branch which has been compatible with Rails 5 since more than a year now.

In general, try the master branch of any gem you're having problems with, since it will have the latest updates.
