### ISSUE TITLE
ransacker : how to acces to arguments passed by activeadmin filter

### ISSUE THREAD

**Issue by itkin** [activerecord-hackery/ransack#685]
Hello,

I'd like to override the way ransack search on a column (i'd like to use a pg_search scope), to achieve such a goal i've done a ransacker but arguments passed by the activeadmin filter are not accessible  

```
      ransacker :title, args: [:parent, :ransacker_args] do |parent, args|
        puts args
        => []
        
      end
```

**Comment by jonatack** [comment]
Hi @itkin, to localize the issue, does it work if you don't use ActiveAdmin? Have you looked at the ransacker examples in the wiki? If it still does not work using Ransack alone, could you please provide a gist as per the Contributing Guide to help reproduce? Closing for now, can re-open pending actionable info. Thanks.
