### ISSUE TITLE
Dynamic model scopes

### ISSUE THREAD

**Issue by glaucocustodio** [activerecord-hackery/ransack#686]
Hi folks. First I would like to thank you all for the great work!

I found myself with the same issue described here http://stackoverflow.com/questions/36883605/create-a-select-based-on-model-scopes-for-a-ransack-search-form-for.

Is there a way to dynamically choose a scope I would like to use (without JavaScript or html links)?

I need to create a select list with all possible model scopes that can be used to filter records.

Thanks.

**Comment by seanfcarroll** [comment]
Please ask on SO.
