### ISSUE TITLE
Rails 5 params / ActionController::Parameters compatibility

### ISSUE THREAD

**Issue by bastengao** [activerecord-hackery/ransack#687]
ActionController::Parameters params[:q] doesn't return hash in Rails 5. see https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/search.rb#L19

```
# works in Rails 5
@q = Person.ransack(params[:q].to_unsafe_h)
```

**Comment by maxehmookau** [comment]
Having the same issue... I tried to fix it using controller whitelists but it didn't appear to work. I'm looking at it in more detail now though.

```ruby
@q = @instance.videos.ransack(search_params)

def search_params
    params.permit(:utf8, :commit, q: [:title_eq]).to_h
end
```

**Comment by danieldocki** [comment]
Same here!

**Comment by jonatack** [comment]
Ransack master has been working with Rails 5 since a year and a half now:

```ruby
gem 'ransack', github: 'activerecord-hackery/ransack'
```

Will make a new official release very soon.

**Comment by danieldocki** [comment]
@jonatack I do not know what's more using the master branch does not render the attribute_select

**Comment by jonatack** [comment]
Hello @danieldocki, it sounds like you are reporting a different issue or regression. If so, would you please file a separate issue or pull request following the [CONTRIBUTING Guide](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md).

**Comment by paicha** [comment]
Any progress?

**Comment by jonatack** [comment]
Progress on what -- you be more specific please? This issue was solved a
year before it was filed, and is closed. The empty attributes_select was
fixed as well.

**Comment by g13ydson** [comment]
I'm having problems with the Rails 5.0.0.1 version.
I created a new project to test and is not working.

```
<%= search_form_for @q do |f| %>
  <%= f.label :name %>
  <%= f.search_field :name %>
  <%= f.submit %>
<% end %>
```

```
def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
    puts @users
end
```

I believe it is in params:

```
Processing by UsersController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>{"name"=>"Gleydson"}, "commit"=>"Search"}
```
