### ISSUE TITLE
sort_link can't be used safely with Rails 5

### ISSUE THREAD

**Issue by csuhta** [activerecord-hackery/ransack#693]
Rails 5 has changed `params` so that it is an `ActionController::Parameters` that tracks it's permitted status. Using `sort_link` in Rails 5 will result in an `ArgumentError` because of the way `sort_link` generates the URL internally. 

I've tried to distill my example down to a minimum:

```ruby
# Controller
def index
  @search = YourModel.ransack(nil)
end
```

```erb
<%# View %>
<%= sort_link(@search, :id) %>
```

You’ll get:

```
ArgumentError 
Attempting to generate a URL from non-sanitized request parameters! 
An attacker can inject malicious data into the generated URL, 
such as changing the host. Whitelist and sanitize passed 
parameters to be secure.
```

What you pass to `ransack()` doesn't seem to matter for this issue. The only way I could workaround it was to do:

```ruby
def index
  params.permit!
  @search = YourModel.ransack(nil)
end
```

But that's unsafe.

Here's a partial trace:

```
actionpack (5.0.0) lib/action_dispatch/routing/url_for.rb:176:in `url_for'
actionview (5.0.0) lib/action_view/routing_url_for.rb:96:in `url_for'
ransack (1.7.0) lib/ransack/helpers/form_helper.rb:84:in `url'
ransack (1.7.0) lib/ransack/helpers/form_helper.rb:47:in `sort_link'
[Below here is the huge trace from where I called sort_link in my ERB view]
```

- I'm not using Ransack through another gem
- Ruby 2.3.1, Rails 5.0.0, Ransack 1.7.0
- Postgres 9.5

**Comment by abinoam** [comment]
cc: #687

**Comment by csuhta** [comment]
This appears to be fixed on master using:

```ruby
gem "ransack", github:"activerecord-hackery/ransack", branch:"master"
```

**Comment by jonatack** [comment]
@csuhta is correct.

The master branch has been working with Rails 5 since a year and a half now.

Will make a new official release very soon.
