### ISSUE TITLE
search by association

### ISSUE THREAD

**Issue by mcmegavolt** [activerecord-hackery/ransack#696]
```ruby
class Shop
  has_many :cars
end

class Car
  belong_to :shop
  has_one :owner
end

class Owner
  belongs_to :car
end
```

If I have owner list, how to search by shop name, something like ```car_shop_name_cont``` ?

**Comment by jonatack** [comment]
Hi! If the README and Wiki didn't cover your question, please use StackOverflow for questions/help, where a wider community will be able to help you. We try to reserve the issues tracker for issues only. Thanks!
