### ISSUE TITLE
Issue when using ransack with rails_db gem

### ISSUE THREAD

**Issue by igorkasyanchuk** [activerecord-hackery/ransack#700]
Hello, I've noticed that new version of ransack doesn't works with rails_db gem (it's using it for search). Issue is connected with removing namespace "Ransack" from "Constants" module. Could we do something to fix this issue? Maybe revert this namespace back?

I believe this is true also for other gems.

ActionView::Template::Error (uninitialized constant Ransack::Constants::ASC):
    47:       <div class="field sorting_options">
    48:         Sort:
    49:         <%= f.sort_fields do |s| %>
    50:           <%= s.sort_select %>
    51:         <% end %>
    52:       </div>
    53:       <div class="actions"><%= f.submit "Search", class: 'button small' %></div>
  ransack (1.8.0) lib/ransack/helpers/form_builder.rb:179:in `sort_array'
  ransack (1.8.0) lib/ransack/helpers/form_builder.rb:70:in `sort_direction_select'
  ransack (1.8.0) lib/ransack/helpers/form_builder.rb:75:in `sort_select'
  /Users/igorkasyanchuk/Projects/rails_db/app/views/rails_db/tables/_data.html.erb:50:in `block (2 levels) in ___sers_igorkasyanchuk__rojects_rails_db_app_views_rails_db_tables__data_html_erb___4579710676106818382_70233866914900'
  actionview (4.2.4) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.4) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'

**Comment by jonatack** [comment]
Thank you, @igorkasyanchuk 💜. Can you try rails_db with ransack/master and let me know?

**Comment by jonatack** [comment]
@igorkasyanchuk If you report back that the issue is solved, I will release 1.8.1 right away with this fix.

**Comment by igorkasyanchuk** [comment]
thanks but I've found another issue, I will post more details to other existing issue #701
