### ISSUE TITLE
How to create query when using has_many :through association

### ISSUE THREAD

**Issue by f-shuto** [activerecord-hackery/ransack#707]
First, thank you for nice gem.

I am trying to create query by using has_many :through association. I need to search by column on model(Order) of has_many  association and by column on model(BatchLogHead) of has_many :through association. 
But I cannot get query I want. 

Model:
```
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :batch_log_heads, class_name: 'BatchLogHead', through: :orders
```

Output query: ('orders' have been different alias. But I want same alias.)
```
SELECT COUNT(DISTINCT customers.id) FROM customers 

LEFT OUTER JOIN orders 
ON orders.customer_id = customers.id 
LEFT OUTER JOIN batch_log_heads
ON batch_log_heads.id = orders.batch_id

LEFT OUTER JOIN orders orders_int_customers 
ON orders_int_customers.customer_id = customers.id 

WHERE 
(batch_log_heads.id = 16 ) 
AND
(orders_customers.level IN ('A'))
```

I want:
```
SELECT COUNT(DISTINCT customers.id) FROM customers 

LEFT OUTER JOIN orders 
ON orders.customer_id = customers.id 
LEFT OUTER JOIN batch_log_heads
ON batch_log_heads.id = orders.batch_id

WHERE 
(batch_log_heads.id = 16 ) 
AND
(orders .level IN ('A'))
```

How shoud I do?

Thanks.

**Comment by jonatack** [comment]
Hi @f-shuto , please see the readme/wiki/contributing guide, and search on earlier issues, for how to use Ransack. We try to reserve the issues tracker for issues/bugs only, not personal support requests. Thanks!

**Comment by oklas** [comment]
It would be good for them who search to leave a correct link or correct solution anyway.

**Comment by oklas** [comment]
If someone search here, check the docs:

https://github.com/activerecord-hackery/ransack#associations

And also when about **polymorphic** associations check [this](https://github.com/activerecord-hackery/ransack/wiki/Polymorphic-searches) and search substring `_of_` in [docs](https://github.com/activerecord-hackery/ransack)
