### ISSUE TITLE
Using Ransack to search child attributes from parent model

### ISSUE THREAD

**Issue by pradyumna2905** [activerecord-hackery/ransack#708]
Hi all,
I am trying to figure out a way to search in my child model and using Ransack from my parent model. Is there a way to do this?

```
class A
    has_one :b 
end
```
```

class B
  belongs_to :a 
end
```

I want to use Ransack from `A` to search for attributes in B's table and want to return the associated `A` object.

Thanks

**Comment by jonatack** [comment]
Hi @pradyumna2905, please see the readme/wiki/contributing guide for how to use Ransack. If that doesn't help, please use StackOverflow for questions/help, where a wider community will be able to help you. We try to reserve the issues tracker for issues/bugs only, not personal support requests. Thanks!
