### ISSUE TITLE
PG: operator does not exist: uuid ~~* unknown

### ISSUE THREAD

**Issue by zenati** [activerecord-hackery/ransack#709]
Hello, I have an UUID column as ID column. When I do:

`Campaign.search(id_cont: 'abc').result`

I get this error:
```
HINT:  No operator matches the given name and argument type(s).
You might need to add explicit type casts.
SELECT  "campaigns".* FROM "campaigns" WHERE "campaigns"."pro_user_id" = $1
AND "campaigns"."aasm_state" = 'drafted'
AND ("campaigns"."id" ILIKE NULL) 
ORDER BY "campaigns"."created_at" DESC
LIMIT 25
OFFSET 0

PG::UndefinedFunction: ERROR:  operator does not exist: uuid ~~* unknown
LINE 1: ...s"."aasm_state" = 'drafted' AND ("campaigns"."id" ILIKE NULL...
```

Any idea? Thanks.

**Comment by jonatack** [comment]
Hello @zenati, to help people help you, could you provide a gist to reproduce your issue?

Please see the [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) file for more information and a bug report template.

**Comment by jonatack** [comment]
Stalled. Closing for now.

**Comment by istvanfazakas** [comment]
same issue here. the IDs in the tables are not of type Integer, they are UUIDs. When passing the ids to ransacker, it tries to find the objects with 'ILIKE' method, instead of simple 'IN'

**Comment by kkarski82** [comment]
Here's a solution:

```ruby
module RansackUUIDHelper
  extend ActiveSupport::Concern

  included do
    ransacker :id do
      Arel.sql("\"#{table_name}\".\"id\"::varchar")
    end
  end
end
```

All you need to do then is `include RansackUUIDHelper` in your model.
