### ISSUE TITLE
I want to sort my records without searching through them

### ISSUE THREAD

**Issue by Alagaesia93** [activerecord-hackery/ransack#710]
Hi everybody,
I'm looking for a way to use ransack utilities to sort records, but without search. I need it because I already have my search code and works perfectly.
I have an @items and I want to sort it, but without filtering and search features. Is it possible? 

Thanks a lot!

**Comment by jonatack** [comment]
Hi! Please use StackOverflow for questions/help, where a wider community will be able to help you. We try to reserve the issues tracker for issues only. Thanks!

P.S. - Please begin by looking at the Ransack documentation before asking questions. In the README you'll find a section about Ransack `sort_link` view helpers that might possibly be suitable for your needs (or not, you'll have to read it).
