### ISSUE TITLE
search results returns full index 

### ISSUE THREAD

**Issue by nik-007** [activerecord-hackery/ransack#712]
I have used ransack in many models and all are working fine, while only one model not working. I am trying to search results but it returning with full index as it is. also I have implemented the methods as same as other models. why this is happening please help.

**Comment by jonatack** [comment]
Hello! To help us help you, could you provide a standalone gist to reproduce your issue? Please see [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) file for more information and a bug report template to work from.

For questions/personal support, please use StackOverflow, where a wider community will be able to help you. We try to reserve the issues tracker for issues (bugs) with Ransack itself.

Closing, will re-open if actionable info is provided. Thanks!
