### ISSUE TITLE
Custom Select Boxes

### ISSUE THREAD

**Issue by HangingClowns** [activerecord-hackery/ransack#715]
Hi,

Been searching for a while on stackoverflow, here, and just plain google, but cannot find the answer to this question. I have some values that I want to search for, so something like:

```
Number of people: Any, 1, 2, 3, >3
Cost price: Any, 1-5, 6-10, >10
```

But, i'm not sure what's the best way to implement this. It's not an gteq, cause i dont' have 2 or more if I input 2. How can I best represent this in the form for Ransack?

Thanks

**Comment by jonatack** [comment]
Please see the Ransack wiki, where [Custom predicates](https://github.com/activerecord-hackery/ransack/wiki/Custom-Predicates) would be one solution. Or creating a value object, or enum in Rails or SQL, etc.

Please use the Ransack issues tracker for bugs with Ransack only and not free personal support. Thanks!
