### ISSUE TITLE
Filter by relationship not working

### ISSUE THREAD

**Issue by henriquesacramento** [activerecord-hackery/ransack#725]
In my object i have a numeric id but i want to search by segment name

Example below:

```
<%= f.select :segment_id_cont, Segment.all.collect {|segment| [ segment.name, segment.id ] } %>
```

**Comment by jonatack** [comment]
Hi @henriquesacramento,

"Not working" isn't a lot to go on 😄. Could you please provide the info mentioned in CONTRIBUTING.md and ensure that this is really a bug with the code of Ransack itself? Closing for now, can re-open if you follow up on this.
