### ISSUE TITLE
Sorting with a complex SQL statement not working

### ISSUE THREAD

**Issue by Carpela** [activerecord-hackery/ransack#729]
Trying to set a default sort by specific ordering according to a status field. 

The sort works fine outside of ransack creating the following:

`Model.order("CASE WHEN status = 'X' then 0 WHEN status = 'Z' then 1 WHEN status = 'Y' then 2 END", "updated_at desc")
`
Lists X's by date, then Z's by date, then Y's by date. 

However, setting:

`@q.sorts = "CASE WHEN status = 'X' then 0 WHEN status = 'Z' then 1 WHEN status = 'Y' then 2 END"`
or
`@q.sorts = ["CASE WHEN status = 'X' then 0 WHEN status = 'Z' then 1 WHEN status = 'Y' then 2 END", "updated_at desc"]`

has no influence on the order. 

It's just dropping them somewhere.

**Comment by seanfcarroll** [comment]
Please post a failing test or link to a repo

**Comment by hendricius** [comment]
My suggestion here would be to write a view that holds your complex ordering query. That way you can just later on join the view and do the ordering. It's easier than to hack ransack into doing something like that.

**Comment by shobee** [comment]
If someone will run into this issue like me today (in my case I was trying to order by something like `FIELD(status, 'open', 'assigned', 'done')` which was silently dropped) the solution is to use scopes. See https://github.com/activerecord-hackery/ransack/pull/973/files for details on how to use it.
