### ISSUE TITLE
How to search on has_one association?

### ISSUE THREAD

**Issue by FX-HAO** [activerecord-hackery/ransack#731]
Example:

```
class User < ActiveRecord::Base
  has_one :profile
 end

class Profile < ActionRecord::Base
end
```

When i tired `/api/v1/users?q[profile_address_eq]=xxx`, it does not work. Any idea?

**Comment by seanfcarroll** [comment]
Does it work if you add the **:belongs_to** association?

**Comment by Romaboy** [comment]
And what to do about has_one :through?

**Comment by gregmolnar** [comment]
@Romaboy it's been closed by the person who opened it, so I assume his problem is solved.
Do you have an issue with has_one :through?

**Comment by Romaboy** [comment]
Did not notice that.
Yes, ransack ignores _table_name_column_ on _has_one_
Google does not know much about it, here is suspicious solution [on stackoverflow (first answer)](https://stackoverflow.com/questions/41795404/ransack-sorting-association-in-show-action)
While it works, it also opens the gates to SQL injections
