### ISSUE TITLE
Why is it recommended to install the gem via git in the README?

### ISSUE THREAD

**Issue by mcls** [activerecord-hackery/ransack#737]
I think it's good to mention the option, but I wonder why it's recommended?

I usually avoid installing via git unless I need to (e.g. an unreleased bug fix), because it seems to be a bit slower than via rubygems. Also the `:github` version is less secure because it doesn't use https (http://bundler.io/git.html#security).

**Comment by benlangfeld** [comment]
Where are you seeing this? The README I see already meets your request:

```
In your Gemfile, for the last officially released gem:

gem 'ransack'
If you would like to use the latest updates (recommended), use the master branch:

gem 'ransack', github: 'activerecord-hackery/ransack'
```

**Comment by seanfcarroll** [comment]
Thank you @benlangfeld for the clear explanation.

**Comment by mcls** [comment]
Sorry missed the previous comment. 

I'm not recommending it, I was just curious *why* the README is recommending it.

**Comment by benlangfeld** [comment]
You know, my comment was nonsense. I didn't see "(recommended)" until now. This is a valid issue after all.

**Comment by mcls** [comment]
My concern is that it could be confusing to newcomers, that's all. They might start installing all gems via git, which IMO is a bad idea.

**Comment by seanfcarroll** [comment]
I didn't write the recommendation, but I guess it would be so you have the latest code not yet cut as a gem.

**Comment by lenart** [comment]
I don't want to be rude but it's really [up to the user to understand how gems ecosystem work](http://bundler.io/git.html) and why one would like to install directly from git vs. rubygems. No need to open up issues for every project ;)

**Comment by mcls** [comment]
I agree that people should now how rubygems works. But IMO that doesn't mean the insecure way should be actively recommended.

**Comment by lenart** [comment]
I wanted to add to my previous comment that maybe we need to remove the word _recommended_. But then again I believe the authors don't want to be asked all the time to release new versions just because there is this one bugfix that someone might need. That's probably one of the main reasons they recommend github as gem's source. If you're concerned about security you can use github's https url instead.

**Comment by seanfcarroll** [comment]
A new version of the gem will soon be released.
