### ISSUE TITLE
Demo app broken

### ISSUE THREAD

**Issue by mollerhoj** [activerecord-hackery/ransack#761]
Hey guys.

I'm new to this gem. I tried the demo app, but it seems like the app is broken. Queries on posts:
<img width="589" alt="screen shot 2017-02-08 at 08 55 26" src="https://cloud.githubusercontent.com/assets/649188/22728091/62f40910-eddc-11e6-8a9e-547711b00ef4.png">
Result in:
<img width="568" alt="screen shot 2017-02-08 at 08 54 59" src="https://cloud.githubusercontent.com/assets/649188/22728107/732fa7e4-eddc-11e6-87f6-666962cd5cd3.png">

Anyways, just thought I'd let you know :-)

**Comment by seanfcarroll** [comment]
Thanks

**Comment by seanfcarroll** [comment]
Seems to be OK now, thanks for the issue.

Closed.
