### ISSUE TITLE
wrong order on sorting an integer field with integer search workaround implemented

### ISSUE THREAD

**Issue by cbajohr** [activerecord-hackery/ransack#765]
When I use the workaround from the wiki for searching on an integer field:
``` 
ransacker :id do
  Arel.sql(
    "regexp_replace(
      to_char(\"#{table_name}\".\"id\", '9999999'), ' ', '', 'g')"
  )
end
```
the order on the id sort_link is sorting by string instead of integer. 

So it is not like 1,2,3,4,5,6,...,130, it is like: 1,11,110,115,116,119,13,130

Any idea how to fix this?

PostgreSQL ORDER BY statement ends with: 
```
... ORDER BY regexp_replace(to_char("my_table"."id", '9999999'), ' ', '', 'g') ASC LIMIT 25 OFFSET 0
```

My PostgreSQL version is: 9.5.5.
Ransack gem is up to date.

**Comment by cbajohr** [comment]
Found a solution by myself. 

I did rename the custom ransacker to :idfilter instead of :id and renamed all filter form elements to :idfilter_cont and the sort link as (@q, :id).
That does the trick.

**Comment by Fiorella** [comment]
Work!! thanks!! :+1:
