### ISSUE TITLE
Throw exception for undefined ransacker

### ISSUE THREAD

**Issue by ml** [activerecord-hackery/ransack#77]
ATM when I do `Model.seach(undefined_field_in: [123]).result` it issues `SELECT models.* from models`. I think it should throw an exception.

**Comment by patientdev** [comment]
Was a PR ever submitted for this? If not, would one be accepted now?

**Comment by seanfcarroll** [comment]
Closed due to age

**Comment by emmanuelmillionaer** [comment]
You can use:  `ransack!` This method will throw an exception, if the search term is not valid. E.g 

```
Article.ransack!(unknown_attr_eq: 'Ernie')
# ArgumentError: Invalid search term unknown_attr_eq
```
