### ISSUE TITLE
Expose a configuration value to determine which adapter to use

### ISSUE THREAD

**Issue by yosi-dediashvili** [activerecord-hackery/ransack#775]
This is touching the ActiveRecord & Mongoid living together. 

The current solution of monkey patching the `instantiate_object_mapper` doesn't help when you use it with `ActiveAdmin` - by the time your patch is being applied ransack was loaded.

**Comment by seanfcarroll** [comment]
The Mongoid extension is troublesome ... it could be refactored out if it is not used.

**Comment by seanfcarroll** [comment]
I think a better solution would be to split Ransack -- "ransack" for activerecord and a new gem "ransack-mongo" for MongoDB. We could push shared code into a shared lib.

**Comment by seanfcarroll** [comment]
Mongo has been split out https://github.com/activerecord-hackery/ransack-mongoid
