### ISSUE TITLE
ransack 1.8.2 break rails 5.0.2 active_record.table_name_prefix configuration

### ISSUE THREAD

**Issue by qichunren** [activerecord-hackery/ransack#777]
Environment:
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
Rails 5.0.2
ransack 1.8.2
mysql 5.6.17

I configed mysql table name prefix in file **config/initializers/00_database.rb**

        Rails.application.config.active_record.table_name_prefix = "nt_"

Before I add **gem 'ransack'** to **Gemfile**, rails migration create expected tables, include table name prefix.

After I add ransack gem into my rails project, I drop created db, then create it, run bundle exec rake db:migrate, all table created by migration named unexpected, it did't add prefix 'nt_' to table name.

Then I remove ransack from my Gemfile, repeat steps, table naming is expected.

**Comment by qichunren** [comment]
After I use ransack directly from github 

    gem 'ransack', github: 'activerecord-hackery/ransack'

it worked as expected.

**Comment by seanfcarroll** [comment]
A new release of the gem is required. Sorry for the delay but we are refactoring, for now just hit github.
