### ISSUE TITLE
Advanced (post) mode with pagination

### ISSUE THREAD

**Issue by nocivus** [activerecord-hackery/ransack#78]
Is this possible? If so, can you give me some pointers on how to achieve it? Thanks!!

**Comment by seanfcarroll** [comment]
Will this do the trick?

      def index
        @search = Article.where({language_cd: current_user.target_language}).ransack params[:q]
        @articles = @search.result.page(params[:page]).per(params[:per_page])
     end

**Comment by jonatack** [comment]
See the last few comments of #80. Thanks.
