### ISSUE TITLE
How to search multiple columns with same multiple fields combination

### ISSUE THREAD

**Issue by MitsunChieh** [activerecord-hackery/ransack#783]
Is there any existed method to do in these 3 cases?

# Case 1:
User want to search [str1, str2] on column1 and column2 in models.
1. If column1 contains str1, column2 should contain str2
2. Or column1 contains str2, column2 should contain str1  

I can make this happened in the following way:
```ruby
Model.search( g: [{ column1_cont: str1,  column2_cont: str2 }, { column1_cont: str2,  column2_cont: str1 }], m: 'or' )
```

It made a query like this:
```sql
SELECT `models`.* FROM `models` WHERE (((`models`.`column1` LIKE '%str1%' AND `models`.`column2` LIKE '%str2%') OR (`models`.`column1` LIKE '%str2%' AND `models`.`column2` LIKE '%str1%')))
```

It totally what I needs.
**But I want to know is there a better way to do this?**

### ==== additional ====
This is a wrong way:
```ruby
Model.search( column1_and_column2_cont_any: [str1, str2] )
```

Actually it makes:
```sql
SELECT `models`.* FROM `models` WHERE (((`models`.`column1` LIKE '%str1%' OR `models`.`column1` LIKE '%str2%') AND (`models`.`column2` LIKE '%str1%' OR `models`.`column2` LIKE '%str2%')))
```

It will find out some records that both column1 and column2 contain str1, or both column1 and column2 contain str2.
### ==== additional closed ====

# Case 2:
Case 2 and 3 are similar.

User want to search [str1, str2, str3] on column1 and column2 in models.
1. If column1 contains str1, column2 should contain both str2 and str3
2. Or column1 contains str2, column2 should contain both str1 and str3
3. Or column1 contains str3, column2 should contain both str1 and str2
4. Or column2 contains str1, column1 should contain both str2 and str3
5. Or column2 contains str2, column1 should contain both str1 and str3
6. Or column2 contains str3, column1 should contain both str1 and str2

# Case 3:
User want to search [str1, str2, str3] on column1 and column2 in models.
1. If column1 contains str1, column2 should contain either str2 or str3
2. Or column1 contains str2, column2 should contain either str1 or str3
3. Or column1 contains str3, column2 should contain either str1 or str2
4. Or column2 contains str1, column1 should contain either str2 or str3
5. Or column2 contains str2, column1 should contain either str1 or str3
6. Or column2 contains str3, column1 should contain either str1 or str2

**Is there any existed method can help me making these combination?**

Thanks.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794

**Comment by mikehamlick** [comment]
MitsunChieh, did you ever figure out how to do this in Ransack? I've been looking very hard for a solution.

**Comment by seanfcarroll** [comment]
Closed
