### ISSUE TITLE
habtm search broken for models with postgres UUID

### ISSUE THREAD

**Issue by wefarrell** [activerecord-hackery/ransack#786]
[gist here](https://gist.github.com/wefarrell/d0c16e5eb372bc7365a94f6b11261f74)

I have a model with a uuid primary key, `Student` that has a habtm relationship with `Group`. 

When searching students by group_id: `Student.ransack({groups_id_eq: 2}).result` it converts the value to NULL:

    SELECT "students".* FROM "students"
    LEFT OUTER JOIN "groups_students" ON "groups_students"."student_id" = "students"."id" 
    LEFT OUTER JOIN "groups" ON "groups"."id" = "groups_students"."group_id" 
    WHERE "groups"."id" = NULL

**Comment by wefarrell** [comment]
I was able to narrow the problem down to `ActiveRecord::Associations::AliasTracker`. It's returning an arel table with a mismatched type_caster and table_name. I've been able to fix the issue with the following monkey patch:

```
module ActiveRecord
  module Associations
    class AliasTracker
      def aliased_table_for(table_name, aliased_name)
        table_class = table_name.classify
        type_caster = if Object.const_defined?(table_class) && table_class.constantize.respond_to?(:type_caster)
          table_name.classify.constantize.type_caster
        else
          @type_caster
        end

        if aliases[table_name].zero?
          # If it's zero, we can have our table_name
          aliases[table_name] = 1
          Arel::Table.new(table_name, type_caster: type_caster)
        else
          # Otherwise, we need to use an alias
          aliased_name = @connection.table_alias_for(aliased_name)

          # Update the count
          aliases[aliased_name] += 1

          table_alias = if aliases[aliased_name] > 1
            "#{truncate(aliased_name)}_#{aliases[aliased_name]}"
          else
            aliased_name
          end
          Arel::Table.new(table_name, type_caster: type_caster).alias(table_alias)
        end
      end
    end
  end
end
```

I will submit this as an issue to rails and propose a pull request.

**Comment by seanfcarroll** [comment]
Please link the pull request if its ready. As this is a Rails issue can this now be closed?

**Comment by seanfcarroll** [comment]
Assuming this can be closed.
