### ISSUE TITLE
Search with ransack gem

### ISSUE THREAD

**Issue by luis77** [activerecord-hackery/ransack#787]
I am showing the result of a query in my view, this query uses two different tables and for the data search I am using the ransack gem to perform the searches but it shows me the following error in the search form: `ActionView::Template::Error (undefined method `Producto_cont' for Ransack::Search<class: Stoc, base: Grouping <combinator: and>>:Ransack::Search):`

The field "Producto" I am getting it from another table called "productos" and it is the result of the query, it only shows me the error with the fields of the other one that I am relating in the query and not with the one that I am calling from the method that It's "Stoc"

this is my method controller: 

```
@search = Stoc.productos_de_un_stock(params).search(search_params)
@search.sorts = 'Stock desc' if @search.sorts.empty?
@stock = @search.result().page(params[:stock]).per(15)
```

this is my query: 
```
 def self.productos_de_un_stock(params)
      query = select("[stock].IdStock, [stock].Stock, [productos].Clave AS Clave_producto, [productos].Producto, [productosxpzas].PzaXCja AS PzaXCja")
              .joins('inner join productos ON stock.Articulo = productos.Clave inner join productosxpzas ON productos.Clave = productosxpzas.Producto')
              .where('stock.Ruta = ? AND stock.IdEmpresa = ?', (params[:search]), (params[:search6]))

      query
    end
```

this is my search form:

```
 <%= search_form_for @search, :remote=>"true", url: busqueda_stock_path, :method => :get do |f| %>
    <div class="rwd">
      <table class="table table-striped table-bordered table-condensed table-hover rwd_auto">
        <thead>
          <tr>
            <th class="component_name_header_col"><%= sort_link @search, :Articulo, "Clave","stoc", {}, { :remote => true, :method => :get } %></th>

            <th class="action_col"><%= t("basic.action") %></th>
          </tr>
          <tr>
            <th><%= f.text_field :Articulo_cont, class:"campo" %></th>
            <%= f.search_field :Producto_cont %>
              <input id="search" type="hidden" value="<%=params[:search] %>" name="search"/> 
            <input id="search6" type="hidden" value="<%=params[:search6] %>" name="search6"/>


            <th><%= f.submit "Buscar" %></th>
          </tr>

        </thead>
        <tbody>

        </tbody>
      </table>
    </div>
  <% end %>
```

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
