### ISSUE TITLE
Will_Paginate

### ISSUE THREAD

**Issue by morgz** [activerecord-hackery/ransack#80]
Out the box I'm struggling to get will_paginate to work with ransack. It filters the first page of results just fine but doesn't remember the query for the subsequent pages.

Am I just expecting too much?

**Comment by Oppenheimer1** [comment]
ffscalco If you go here this person(rvsingh) has resolved the issue:
 
http://railscasts.com/episodes/370-ransack?view=comments

per his comments:

Make this change in routes. And it works.

resources :styles do
collection do
match 'search' => 'styles#index', :via => [:get, :post], :as => :search
end
end

**Comment by jonatack** [comment]
@Oppenheimer1 Thanks!

**Comment by jonatack** [comment]
FWIW the README also suggests something similar for the routes.

**Comment by Oppenheimer1** [comment]
Hi Jon,

On a different topic, would you know of any good star rating gems that can
be added to a rails app. Just curious, with the current project I'm working
on the customer has requested it.

Thanks,
Lars

**Comment by jonatack** [comment]
Hm, not really (I'm not a good person to ask). A quick search turned up a couple of older plugins you could perhaps adapt:

https://github.com/rlivsey/acts_as_starred
https://github.com/azabaj/acts_as_rateable

**Comment by doekerqhtv** [comment]
To the contrary, this does not work with will_paginate with POST. If you use POST in your search method, parameters will not be passed to will_paginate.

Problem being will_paginate does not generate a form that will post, instead it generates links that will need to have params[:q] passed, which will end up being ugly as end users start moving about pagination.

This will actually get will_paginate working with POST, but the next page will then be switched to "GET" :
<%= will_paginate(@search, :params => { q: params[:q]}) %>

The way around all this is to look into will_paginate Link Rendering, and have a form with post be used to scroll through pages: https://github.com/mislav/will_paginate/wiki/Link-renderer.

Hope this can be helpful to someone.
