### ISSUE TITLE
undefined method `ransack' for #<Product::ActiveRecord_Relation...>

### ISSUE THREAD

**Issue by Shouheyhey** [activerecord-hackery/ransack#801]
Although I installed gem ransack (version:1.2.3)  as well as gem polyamorous(version:1.0.0), I couldn't use "ransack" method in my controller in local environment. I already restart local server, I checked that ransack is already installed through the command of "gem list ransack". Is this computer's problem or other problem?

My controller is like this.

Products_controller.rb
```
def landing
    @q = Product.order('id ASC').per_page_kaminari(params[:page]).per(10).ransa(search_params)
    @products = @q.result(distinct: true)
  end
end

private
def search_params
  params.permit(:title_count)
end
```

My viewfile is

landing.html.erb
```
...
<header>
  <div class="header_area clearfix">
    <div class="header_title_cussion">
    <div class="header_title">
  <h1 text="text-large">HOGEHOGEHOGE</h1>
    </div>
  </div>
    <div class="header_content">
      <div class="search_area">
        <%search_form_for(@q, url: search_products_path do |f| %>
      <div class="form_group">
        <div class="keyword_search">
        <%=f.label :title_cont ,"企業名から探す",class:"col-sm-2 control-label"%>
        <%=f.text :title_cont, class:"btn-search header",placeholder:"企業名で検索"%>
        <%=f.submit '検索', class:"btn-search header"%>
    </header>

        </div>
      </div>
    </div>
  <div>
    <% end %>
</header>
```

Also, when I checked "search" and "search_form_for" method, same error occurred.

**Comment by nimish13** [comment]
@Shouheyhey It would be really helpful if you can share the error log. Also in your controller
``ransack`` method is incorrectly spelled.
It should be ``@q = Product.order('id ASC').per_page_kaminari(params[:page]).per(10).ransack(search_params)`` instead of
``@q = Product.order('id ASC').per_page_kaminari(params[:page]).per(10).ransa(search_params)``

**Comment by chenweiyj** [comment]
I also met this problem, printing out 'NoMethodError (undefined method `ransack' for #<Order::ActiveRecord_Relation:0x007ff06a7edb48>)'

**Comment by seanfcarroll** [comment]
closed
