### ISSUE TITLE
Searching the fields 2 level above of associations

### ISSUE THREAD

**Issue by Aiken00** [activerecord-hackery/ransack#808]
```
class UserGroup
 has_many :users
end
class User
 has_many :posts
end
class Post
end
```
Can we search the fields in user_group in the position of post using ransack?

Thanks!

**Comment by nimish13** [comment]
@Aiken00 you may try something like ``Post.ransack(user_user_group_type_eq: 'admin')``

here I am assuming UserGroup class will have a column ``type`` and comparing it to value ``admin``

**Comment by nimish13** [comment]
@Aiken00 Are we good to close this issue?

**Comment by Aiken00** [comment]
Thx!

**Comment by nimish13** [comment]
@Aiken00 - cheers (Y)
