### ISSUE TITLE
search form for  remote true  

### ISSUE THREAD

**Issue by netmoleCBA** [activerecord-hackery/ransack#817]
good day there ,

i am use search_form_for  with ransack and kaminari when is not select criteria filled it shows all records but when  is valid criteria entered  then  is visible just form only

full sources to reproduce bug 
https://gist.github.com/netmoleCBA/1d4ad0a68352d04ace01f2c0c9499171

**Comment by seanfcarroll** [comment]
Sorry can you explain the problem a bit more? I don't really understand. Perhaps some screen shots.

**Comment by seanfcarroll** [comment]
Closed due to lack of information. We can look at it if you describe what the problem is. Cheers!
