### ISSUE TITLE
Another one way to avoid records duplication

### ISSUE THREAD

**Issue by quolpr** [activerecord-hackery/ransack#821]
I didn't find another way in `readme.md` about how to avoid records duplication. So, it is:

```ruby
persons = Person.where(
  id: Person.ransack(params[:q])
            .result
            .joins(:comments)
).page(params[:page])
```

Is it reasonable? I can create PR with updated readme if needed

**Comment by seanfcarroll** [comment]
Yes please

**Comment by seanfcarroll** [comment]
Closed due to inactivity
