### ISSUE TITLE
ArgumentError with has_many through and not_in

### ISSUE THREAD

**Issue by znz** [activerecord-hackery/ransack#827]
When use `not_in` via has_many through association, raises error.

```
> User.ransack(role_users_role_id_not_in: [1]).result
DEPRECATION WARNING: scope_chain is deprecated and will be removed from Rails 5.2 (called from irb_binding at (irb):2)
ArgumentError: wrong number of arguments (given 7, expected 5)
```

How to reproduce:

- `git clone https://github.com/znz/ransack-error-with-rails-5-1`
- `cd ransack-error-with-rails-5-1`
- `rails db:migrate`
- `rails r "User.ransack(role_users_role_id_not_in: [1]).result"`

**Comment by znz** [comment]
I add workaround to `config/initializers/ransack.rb` to remove `association` and `reflection.scope_chain` from arguments of `association.join_constraints`.

```ruby
# frozen_string_literal: true

require 'ransack/version'
if Ransack::VERSION != '1.8.3'
  raise 'Ransack version changed'
end

require 'ransack/adapters/active_record/context'
class Ransack::Adapters::ActiveRecord::Context
  def extract_joins(association)
    parent = @join_dependency.join_root
    reflection = association.reflection
    join_constraints = association.join_constraints(
      parent.table,
      parent.base_klass,
      Arel::Nodes::OuterJoin,
      association.tables,
      reflection.chain
    )
    join_constraints.to_a.flatten
  end
end
```

**Comment by hwhelchel** [comment]
A similar patch is in the master branch @seanfcarroll can we get a new gem release cut?

**Comment by znz** [comment]
I confirmed master branch works well.
Thank you for your information.
And I wait for new release.

**Comment by seanfcarroll** [comment]
Released. Thank you for your help.
