### ISSUE TITLE
Usage of JSON_CONTAINS of mysql

### ISSUE THREAD

**Issue by zeitnot** [activerecord-hackery/ransack#828]
As I see ransack does not have support for `JSON_CONTAINS` or any statetements related to JSON. I have did tons of search and reading but I did not deal with this problem. Creating a custom predicate does not work either. The question is I want to use this statement for my search queries. How can I proceed?

**Comment by seanfcarroll** [comment]
@zeitnot did you work it out?

**Comment by seanfcarroll** [comment]
Closed due to inactivity.
