### ISSUE TITLE
Ransack::Constants escape_wildcards() assumes that there is only one database in use

### ISSUE THREAD

**Issue by mcclumpherty** [activerecord-hackery/ransack#829]
There is an issue with Ransack when searching with multiple database connections in a Rails app.

My primary database is MySQL and searching works fine with this.
However, when I use a secondary database (Oracle), Ransack still escapes characters as it only uses ActiveRecord::Base.connection.adapter_name to determine which database is in use.

For this to work properly, escape_wildcards() needs to be better aware of which database is being queried.  I can see from further up the call stack that the Condition does have access to this information.  Perhaps it could pass this information down to the format call.  Alternatively, the Predicate could be enhanced to make this available.

**Comment by mcclumpherty** [comment]
Additional - at the moment I am monkey-patching it (v1.8.3) to work using the following - it's pretty awful, but works. 

```
class DbAwareString < String
	attr_accessor :connection
	def initialize(value, connection)
		super(value)
		self.connection = connection
	end
end

module Ransack
	module Nodes
		class Condition	
			def formatted_values_for_attribute(attr)
				formatted = casted_values_for_attribute(attr).map do |val|
					if attr.ransacker && attr.ransacker.formatter
						val = attr.ransacker.formatter.call(val)
					end
					val = predicate.format(DbAwareString.new(val, context.klass.connection))
					val
				end
				if predicate.wants_array
					formatted
				else
					formatted.first
				end
			end
		
		end
	end
end

module Ransack
	module Constants
		module_function	
		def escape_wildcards(unescaped)
			if unescaped.kind_of?(DbAwareString)
				adapter_name = unescaped.connection.adapter_name
			else
				adapter_name = ActiveRecord::Base.connection.adapter_name
			end
			case adapter_name
				when "Mysql2".freeze, "PostgreSQL".freeze
					# Necessary for PostgreSQL and MySQL
					unescaped.to_s.gsub(/([\\|\%|_|.])/, '\\\\\\1')
				else
					unescaped
			end
		end
	end
end
```

**Comment by seanfcarroll** [comment]
I think 2 databases is an edge case, especially when of different types. Does anyone in the community have an opinion on this?

**Comment by seanfcarroll** [comment]
Sorry @mcclumpherty I think we have to close this one as an edge case.

**Comment by mcclumpherty** [comment]
Hi @seanfcarroll - many thanks for taking the time to look at this and no worries for closing the issue.

**Comment by seanfcarroll** [comment]
Thanks for understanding @mcclumpherty
