### ISSUE TITLE
Searching for two associations (with and)

### ISSUE THREAD

**Issue by dmasur** [activerecord-hackery/ransack#83]
Hi Ernie,

thanks for your awesome work. At the moment I am changing the complex backendsearch to ransack.

But I stuck with one think. Our Clients can choose languages and the skill how good they are and i need to search for example for clients that have the language id 1 with skill 3 and the language id 2 with skill 4.

For this problem i build a test array like this:

```
  @g[0] = {}
  @g[0]["m"] = "and"
  @g[0]["c"] ||= {}
  @g[0]["c"][0] = {}
  @g[0]["c"][0]["a"] = ["language_proficiencies_the_language_id"]
  @g[0]["c"][0]["p"] = "eq"
  @g[0]["c"][0]["v"] = [1]
  @g[0]["c"][1] = {}
  @g[0]["c"][1]["a"] = ["language_proficiencies_skill_level"]
  @g[0]["c"][1]["p"] = "eq"
  @g[0]["c"][1]["v"] = [3]


  @g[1] = {}
  @g[1]["m"] = "and"
  @g[1]["c"] ||= {}
  @g[1]["c"][0] = {}
  @g[1]["c"][0]["a"] = ["language_proficiencies_the_language_id"]
  @g[1]["c"][0]["p"] = "eq"
  @g[1]["c"][0]["v"] = ["2"]
  @g[1]["c"][1] = {}
  @g[1]["c"][1]["a"] = ["language_proficiencies_skill_level"]
  @g[1]["c"][1]["p"] = "eq"
  @g[1]["c"][1]["v"] = ["4"]
```

This gives this output:

SELECT DISTINCT "users".\* FROM "users" LEFT OUTER JOIN "language_proficiencies" ON "language_proficiencies"."subject_id" = "users"."id" AND "language_proficiencies"."subject_type" = 'User' WHERE "users"."type" IN ('Student') AND (users.state != 'deleted') AND ((("language_proficiencies"."the_language_id" = 1 AND "language_proficiencies"."skill_level" = 3) AND ("language_proficiencies"."the_language_id" = 2 AND "language_proficiencies"."skill_level" = 4))) LIMIT 10 OFFSET 0

It is equal to the advanced demo form when you search for post.id 1 and post.id 2 (both are from user 4):

SELECT "users".\* FROM "users" LEFT OUTER JOIN "posts" ON "posts"."user_id" = "users"."id" WHERE (("posts"."id" = 1 AND "posts"."id" = 2))

I understand that not both of the conditions can be true on the same record. Searching for a way around it i found this query:

SELECT "users".id FROM "users" LEFT OUTER JOIN "language_proficiencies" ON "language_proficiencies"."subject_id" = "users"."id" AND "language_proficiencies"."subject_type" = 'User' WHERE "users"."type" IN ('Student') AND (users.state != 'deleted') AND ((("language_proficiencies"."the_language_id" = 1 AND "language_proficiencies"."skill_level" = 3) OR ("language_proficiencies"."the_language_id" = 2 AND "language_proficiencies"."skill_level" = 4))) GROUP BY users.id HAVING COUNT("users".id) >= 2 LIMIT 10 OFFSET 0

This does pretty much the job with pure sql.

But I hope that I can do the Job with Ransack, maybe with a custom constant. Is there any hope for me with my complex query.

Dominik

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
