### ISSUE TITLE
postgres ILIKE in type date queries

### ISSUE THREAD

**Issue by mateuszkitlas** [activerecord-hackery/ransack#834]
postgres doesn't support `ilike` on type `date`. option `contains` breaks the system. mayby consider casting to string?

**Comment by seanfcarroll** [comment]
Does it make sense to do a ILIKE on a date? I can't see how.

**Comment by seanfcarroll** [comment]
@mateuszkitlas Is this closable?

**Comment by mateuszkitlas** [comment]
yes

**Comment by mateuszkitlas** [comment]
yes
