### ISSUE TITLE
custom url for sort_link

### ISSUE THREAD

**Issue by nAzgalor** [activerecord-hackery/ransack#839]
Unable to change url for sorting.
My url_for returns a value that does not suit me. Maybe change def url(routing_proxy, options_for_url); end ?
@seanfcarroll

**Comment by seanfcarroll** [comment]
Hi, sorry your question is not very clear.

If this is a how-to, please post how-to questions on stackoverflow with the ransack tag.

https://stackoverflow.com/questions/tagged/ransack
