### ISSUE TITLE
How to build a Ransack predicate for column name with dots and special characters?

### ISSUE THREAD

**Issue by pedrofurtado** [activerecord-hackery/ransack#844]
If I have, on my model, a column with name like as 'Date of birthday' (with whitespaces), or 'No. of document' (with dots), how do I build a predicate  for these columns?

For example:

For a 'name' column, I can build a predicate like 'name_cont', 'name_eq', and so on.
But for 'No. of document', I can build a predicate like 'No. of document_cont' or 'No. of document_eq'?

My question is how to build a predicate condition with column names that have special characters (like whitespaces or dots)?

Thanks!

**Comment by pedrofurtado** [comment]
Any news about this issue?

**Comment by pedrofurtado** [comment]
Any news about this issue?

**Comment by pedrofurtado** [comment]
Any news about this issue?

**Comment by pedrofurtado** [comment]
Any news about this issue?

**Comment by seanfcarroll** [comment]
Can you rename the columns with standard rails names?

I'm surprised ActiveRecord doesn't choke on columns with those types of names...

**Comment by seanfcarroll** [comment]
Closing this, as this forum is for reporting bugs in Ransack. Please post how-to questions on stackoverflow with the ransack tag.

https://stackoverflow.com/questions/tagged/ransack
