### ISSUE TITLE
ActiveRecord 5.2 Support

### ISSUE THREAD

**Issue by bbonislawski** [activerecord-hackery/ransack#849]
Did someone succesfully run ransack with AR 5.2? Build is failing on rails master branch(actually it's failing everywhere). Is someone working on that?

**Comment by halo** [comment]
It's an underlying issue [over here](https://github.com/activerecord-hackery/polyamorous/issues/26).

**Comment by pioz** [comment]
Also in `lib/ransack/adapters/active_record/context.rb:282` pass 3 args to `JoinDependency.new` but with Rails 5.2 seems the constructor take 4.

**Comment by halo** [comment]
@pioz Haha, I just ended up in the same rabbit hole as you. You win :) Let me link to the linkes:

3 arguments passed here:
https://github.com/activerecord-hackery/ransack/blob/724d020442dad60a1a6d9e00bbae7681350c9fb1/lib/ransack/adapters/active_record/context.rb#L282-L284

4 required here:

https://github.com/rails/rails/blob/38b2904f2c9d89868e96edd71c5f3143ca235a88/activerecord/lib/active_record/associations/join_dependency.rb#L91

**Comment by halo** [comment]
Also, this override in ransack accepts an argument:

https://github.com/activerecord-hackery/ransack/blob/724d020442dad60a1a6d9e00bbae7681350c9fb1/lib/ransack/helpers/form_builder.rb#L9

But the original in Rails no longer takes an argument:

https://github.com/rails/rails/blob/38b2904f2c9d89868e96edd71c5f3143ca235a88/actionview/lib/action_view/helpers/tags/base.rb#L38

**Comment by pioz** [comment]
Also in the `join_root` attr used in https://github.com/activerecord-hackery/ransack/blob/724d020442dad60a1a6d9e00bbae7681350c9fb1/lib/ransack/adapters/active_record/ransack/context.rb#L34
is become protected:

https://github.com/rails/rails/blob/c5ab6e51a7b9ee05a2d262a72c7130b9c1d1b0ce/activerecord/lib/active_record/associations/join_dependency.rb#L159

**Comment by bbonislawski** [comment]
So I have working version for me:
https://github.com/spark-solutions/polyamorous
and
https://github.com/spark-solutions/ransack

**Comment by seanfcarroll** [comment]
https://github.com/activerecord-hackery/polyamorous/pull/28

**Comment by seanfcarroll** [comment]
Not sure if it is the same issue, but a branch of Ransack based on Polyamorous is available here for testing. https://github.com/activerecord-hackery/ransack/pull/858

**Comment by seanfcarroll** [comment]
Closed as fixed by https://github.com/activerecord-hackery/ransack/pull/868
