### ISSUE TITLE
_cont on Integer column issues unexpected LIKE query

### ISSUE THREAD

**Issue by SomeOfThemAreKillers** [activerecord-hackery/ransack#85]
Hi,

Using Ruby 1.9.3p0, Rails 3.2.2, MySQL 5.5.20, and Ransack 0.6.0, I'm unable to use '_cont' on an Integer column, while the database natively supports '%like%' queries there.

For the incoming search parameter "members_payments_amount_cont"=>"3" the SQL issued by Ransack is "WHERE (payments.amount LIKE 0)", which is obviously an issue.

If I use "members_payments_amount_eq"=>"3" the SQL is correct as shown here: "WHERE payments.amount = 3"

I suspect this is related to string vs. integer data types and am wondering if the behavior is intended or a bug?

**Comment by jonatack** [comment]
(Copied from my reply in #442):

Another workaround that worked for me, though it has been a couple years since I used it because I now use a dedicated, indexed search string column (far faster) with Ransack queries, is to make sure your search query (like "author_id_or_author_of_User_type_company_name_cont" above) _begins with a string column_ and not with an integer one. If all your query attributes are integer columns, then add a string column at the start that will never match the search and it should work.

**Comment by jakeonrails** [comment]
I don't have a trivial test case to share, but I did just discover that having an integer column in the scope you call `#search` on will cause this error to occur.

```
Company.where(id: nil).search(params).result.to_a # raise the postgres error
Company.search(params).result.to_a # no error raised
```

Digging into the source of Ransack now to see if there's a way to fix this at the source.

Not sure what you mean by adding `a string column at the start that will never match` - could you share a super simple example?

In my case I have a complex activerecord scope to filter by id and joins and other stuff, and then I'm searching a string field using ransack - a phone number field. It is the only query passed through Ransack. And like I've shown above - simply having a `integer not null` constraint somewhere in the scope is enough to cause the issue.

**Comment by jakeonrails** [comment]
After further investigation, I suspect this is either:

1. a misuse of the way Arel should be used in ActiveRecord relations
2. a bug in Arel or ActiveRecord

In `Context#evaluate`, there is this line of code:

```ruby
relation = @object.where(viz.accept(search.base))
```

In the simple test case I've created, `viz.accept(search.base)` returns an `Arel::Node::Matches` where the `left` and `right` are correctly set to `some_column_name` and `"%string pattern%"`.

When we now call `@object.where(arel_node_matches).to_sql`, it converts the `"%string pattern%"` to `0`, which is incorrect.

So either `Arel::Node::Matches` was never meant to be passed into `ActiveRecord::Relation#where`, or there is a bug in the way ActiveRecord/Arel build out the query.

From what I understand, `ActiveRecord::Relation#where` should be able to handle anything that responds to `#to_sql`, which `Arel::Node::Matches` does, but it seems that something is still falling down, and I don't know what yet.

**Comment by seanfcarroll** [comment]
Closed as related PR is merged.
