### ISSUE TITLE
Add Postgis to ActiveRecord connection adapter to escape wildcards

### ISSUE THREAD

**Issue by ldonnet** [activerecord-hackery/ransack#850]
Hi,

I use your great gem with postgresql project and it works very well

Now I use a project with postgresql and postgis and suddenly escaping wildcard for sql request as "LIKE" not works. I dig into the code and I find the culprit in lib/ransack/adapters/active_record/ransack/constants.rb

```ruby
 module_function
    # replace % \ to \% \\
    def escape_wildcards(unescaped)
      case ActiveRecord::Base.connection.adapter_name
      when "Mysql2".freeze, "PostgreSQL".freeze
        # Necessary for PostgreSQL and MySQL
        unescaped.to_s.gsub(/([\\|\%|_|.])/, '\\\\\\1')
      else
        unescaped
      end
    end
  end
```

When I test my ActiveRecord::Base.connection.adapter_name in my project i find : 

```ruby
# we use a gem activerecord-postgis-adapter that add this adapter
ActiveRecord::Base.connection.adapter_name 
=> "PostGIS"
```

Is it possible to add this connection adapter too?

Best regards
Luc Donnet

**Comment by seanfcarroll** [comment]
Hi @ldonnet I think a PostGIS extension would be really great. It would need a lot of work though - is anyone interested in working on this?

**Comment by seanfcarroll** [comment]
Closed due to inactivity
