### ISSUE TITLE
Filtering by associations using not condition taking more time

### ISSUE THREAD

**Issue by kishukan** [activerecord-hackery/ransack#855]
`class User < ActiveRecord::Base`
`has_and_belongs_to_many :labels, join_table: "user_tags", class_name: 'Tag'`
`end`

when I try to filter users by condition **doesn't contain with tags name**, it is taking more time(more than 35secs). I have about 2.5 million records. It runs the following query

`SELECT DISTINCT "users".* FROM "users" WHERE ("users"."id" NOT IN (SELECT "user_tags"."user_id" FROM "user_tags" INNER JOIN "tags" ON "tags"."id" = "user_tags"."tag_id" WHERE "user_tags"."user_id" = "users"."id" AND NOT ("tags"."name" NOT ILIKE '%testing%'))) LIMIT 15 OFFSET 0`

How could I achieve it fast since it is taking more time for all **doesn't contain with associated records attributes**

**Comment by seanfcarroll** [comment]
There are a lot of NOTs in that SQL. I think something like this is better written as custom code.

**Comment by seanfcarroll** [comment]
Closed.
