### ISSUE TITLE
Drop older Ruby and Rails support

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#857]
Bring Ransack into line with Polyamorous and drop some older versions.

https://github.com/activerecord-hackery/polyamorous/blob/master/.travis.yml

Posted here in case before proceeding in case this breaks other code, eg ActiveAdmin https://github.com/activeadmin/activeadmin/issues/5254  cc @varyonic

**Comment by seanlinsley** [comment]
I'm always a fan of reducing the complexity of libraries by only supporting the latest major versions of co-dependencies; it's not worth the extra burden it puts on maintainers. If people on old Rails versions want a new feature, they can patch it into their own fork or convince a maintainer to backport it.

Though I would recommend an X or Y version bump (of X.Y.Z) so that it's easy to release bug fixes to older versions if necessary.

**Comment by varyonic** [comment]
Ruby 2.2 is [EOL end of this March, 2018](https://www.ruby-lang.org/en/downloads/branches/).
Rails 4.2 will receive severe security fixes [until 6.0 is available](https://stackoverflow.com/questions/43050213/ruby-on-rails-4-2-end-of-life).
It would be nice to match these dates for library maintenance, but not required if it is indeed a burden.

**Comment by avit** [comment]
+1 on this to simplify everything. I had suggested moving the multiple version support around in #416 but never got back around to working on it.

I think it could be structured it so the *current* supported version is the explicit one, but there can still be some facility to include *backports* as separate modules if anyone wants to contribute them.

Personally I still depend on ransack with a Rails 3.2 application (I know, ouch), but can't expect the community to continue supporting that!

**Comment by seanfcarroll** [comment]
@varyonic that makes sense.

**Comment by seanfcarroll** [comment]
So do we go forward with :

#### Rails
5.1, 5.0 and 4.2

As per [this page](http://guides.rubyonrails.org/maintenance_policy.html#unsupported-release-series)

#### Ruby 
2.2 until end of March 2018
2.3
2.4
 
As per [this page](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/)
