### ISSUE TITLE
Does ransack works on array list ?

### ISSUE THREAD

**Issue by clubbavi** [activerecord-hackery/ransack#860]
Hello, 
I have something like:

` emails = ["abc@abc.com", "a@a.com", "b@b.com"]`
 ` users_list = emails.map{|a| User.where(email: a).first}`
 ` checked_in_users = Kaminari.paginate_array(users_list)`

This gives me proper list of users in the page. But if I want to search by email, what should I do ?

`@q = checked_in_users.ransack params[:q]`

This gives me "NoMethodError (undefined method `ransack' for #<Array" 

What would be the correct way to do it with ransack ?

**Comment by seanfcarroll** [comment]
Please open on SO. Sorry to close but we are trying to cleanup this repo and this is more of a 'how to' question.
