### ISSUE TITLE
Boolean filter not working

### ISSUE THREAD

**Issue by 8vius** [activerecord-hackery/ransack#861]
I'm trying to filter by a boolean column on my Users table and I've tried making it a select box and check box, neither method works

```
filter :admin_created
filter :admin_created, collection: [["Yes", true], ["No", false]]
filter :admin_created, as: :select, collection: [["Yes", true], ["No", false]]
filter :admin_created, as: :check_boxes, collection: [["Yes", true], ["No", false]]
```

Neither of the above filter properly: 

<img width="1251" alt="screen shot 2018-01-15 at 12 45 02 pm" src="https://user-images.githubusercontent.com/671929/34957158-f6c53ebc-f9f1-11e7-87f9-bbd039f546c6.png">

**Comment by Naokimi** [comment]
@8vius I have the same issue, how did you solve it?

**Comment by LondonAppDev** [comment]
@8vius / @Naokimi I have the same issue... Filtering by is_boolean_true=1, is_boolean_eq=t or any variation is not working. The filter is simply not applied.

**Comment by LondonAppDev** [comment]
I've solved my issue... It was unrelated to the boolean filter, and because I didn't add to `ransackable_attributes` as described in the docs: https://www.rubydoc.info/gems/ransack/1.7.0
