### ISSUE TITLE
Merge Wiki and README into a GitHub Pages site

### ISSUE THREAD

**Issue by scarroll32** [activerecord-hackery/ransack#871]
## Update - 10/3/22

- Launch a GitHub pages site for Ransack based on [just-the-docs](https://github.com/just-the-docs/just-the-docs), similair to [ViewComponents](https://viewcomponent.org/)
- Move in and reformat useful material from the Wiki
- Move all project information from the README into the pages site
- Change the README to be quite concise 

## Original proposal 

I'm proposing here that we cleanup and merge the Wiki into the Readme.

Why?

-  A single location for documentation, with up to date material only.
-  The Ransack docs could use a review
-  Acknowledgement for documentation work via PRs, where Wiki changes are in the Wiki repo which gets unnoticed.
-  Automatically deployed to [Rubydocs](http://www.rubydoc.info/gems/ransack)
- Will be part of the 3.0.0 release

Thoughts from the community?

**Comment by seanlinsley** [comment]
➕ from me. I've always disliked using wikis for documentation in open source projects.

**Comment by scarroll32** [comment]
@deivid-rodriguez FYI, I'll get a branch out with this over the coming weekend.

**Comment by scarroll32** [comment]
**Update**

I'm working on a [Docusaurus](https://docusaurus.io/) site which includes a blog, should be running very soon. 🤞
