### ISSUE TITLE
Ignore Param

### ISSUE THREAD

**Issue by QuickD** [activerecord-hackery/ransack#872]
Is it possible to have Ransack ignore a single param? I have a search form and id like a single field to be ignored by ransack.

**Comment by seanfcarroll** [comment]
You could try using params.except[:id]

https://apidock.com/rails/Hash/except

Closing this, as this forum is for reporting bugs in Ransack. Please post how-to questions on stackoverflow with the ransack tag.

https://stackoverflow.com/questions/tagged/ransack
