### ISSUE TITLE
undefined method `map' for #<Ransack::Configuration::PredicateCollection:

### ISSUE THREAD

**Issue by BabichSA** [activerecord-hackery/ransack#879]
Im using old gem https://github.com/kaspernj/simple_form_ransack and in "ransack" version >=1.8.5 I have an error "undefined method `map' for #<Ransack::Configuration::PredicateCollection:" when use  <%= f.input :fieldname_cont %>. Can you add method "map" for more compatibility?

**Comment by seanlinsley** [comment]
The internal object representation is now a hash instead of an array. So instead of delegating `map` to `@collection`, we may need to delegate it to `@sorted_names_with_underscores`.

**Comment by seanfcarroll** [comment]
Thanks @seanlinsley. Given we won't add map, is this type of issue better delegated to the dependent gem itself. The last commit was a year ago :-(

**Comment by seanlinsley** [comment]
From my perspective it seems completely reasonable to add. It'd be very little code:

```ruby
delegate :to_a, :each, :map, to: :@sorted_names_with_underscores
```

While I understand the argument that the 3rd party code should change, it seems likely that Ransack will end up with a lot of support tickets from people running into similar issues. We can nip those in the bud if we add this single line to improve compatibility with older code.

**Comment by seanfcarroll** [comment]
OK, works for me.

**Comment by seanlinsley** [comment]
Hmm, it's not that simple after all since `sorted_names_with_underscores` is a nested array.

**Comment by seanfcarroll** [comment]
Closed due to inactivity. Feel free to reopen and add a PR if it is still needed.
