### ISSUE TITLE
Ransack no longer works with Secondbase gem.

### ISSUE THREAD

**Issue by lcpriest** [activerecord-hackery/ransack#881]
I opened an issue on Secondbase here: https://github.com/customink/secondbase/issues/56.

It looks like moving from `@engine.connection.schema_cache` to `::ActiveRecord::Base.connection.schema_cache` will exclude tables provided in a secondary schema.

I was using Ransack with ActiveAdmin and Secondbase (to have an admin interface for my Rails app in another app, but share some parts of a database).
Ruby 2.5.0
Rails 5.1.4
Ransack 1.8.7

I understand if this is may not be an urgent/relevant issue. 
The commit that added the change is
https://github.com/activerecord-hackery/ransack/commit/d44575506ccc7cb00e618256707ed53732a07bca. 
I would love to understand what changes in Rails 5.2 it is adapting to, so that I can try submit another solution that will allow gems such as Secondbase to continue to work with Ransack.

If I have missed anything, please let me know and I am happy to add it.

**Comment by seanfcarroll** [comment]
Hi @varyonic, regarding this issue. Is there any reason we can't use ```@engine``` instead of ```::ActiveRecord::Base```. It looks like we are already using ```@engine``` in the same class.

Let me know, and I'll look after the changes.

**Comment by varyonic** [comment]
I was building on the [contribution by @bbonislawski](https://github.com/activerecord-hackery/ransack/pull/859/commits/4917cd8cfa5b8c2f7ef6f08a62aa3bce93c5c94f), my guess is the change was not intentional.

**Comment by varyonic** [comment]
I tried changing it back to `@engine` and the tests failed. It's going to need someone more motivated than me to fix this use case.
