### ISSUE TITLE
How can i implement a search function that doesn't return all records when there's no data that matches the parameters?

### ISSUE THREAD

**Issue by NishidaRyu416** [activerecord-hackery/ransack#883]
I've been looking for the ransack's result function that might have been determined to return all records when there's no data that matches the parameters,but I really couldn't find that part unfortunately.
So is there any way to achieve this?
The code im writing is below 

```
            @data =    User.includes(:currencies).ransack(name_cont_any:%W(#{params[:q]})).result.uniq
```

**Comment by seanfcarroll** [comment]
Please ask these types of questions on Stackoverflow

**Comment by NishidaRyu416** [comment]
Actually, I already asked the same question on stackoverflow.
However, it seemed that people didn't know how to realize what I asked.
That's why I asked this question here.

**Comment by seanfcarroll** [comment]
Hi @NishidaRyu416 sure, I understand. We are trying to clean up the Ransack codebase, and just don't have the capacity for how-to questions.

**Comment by NishidaRyu416** [comment]
I see.
Let me say that please implement a feature that `result` method can be not to return all records when there's no data that matches the parameter with an option.

**Comment by seanfcarroll** [comment]
Hi @NishidaRyu416, interesting ... Ransack acts as a filter, so how would we differentiate between not wanting any records (no criteria met) vs return all?

**Comment by NishidaRyu416** [comment]
I think when there's no data that matches the parameters shouldn't be returned all records with an option.
Because users who don't want to return all records basically care about letting rival services know the data such as the number of users,posts etc...

**Comment by NishidaRyu416** [comment]
And you know currently ransack returns all records when there's no data that matches the parameters and people may notice the fact easily, for me that's not appreciated.
