### ISSUE TITLE
Sorting by an association

### ISSUE THREAD

**Issue by rmaspero** [activerecord-hackery/ransack#884]
I've been troubleshooting this for a while and have seen a couple issues that seem to describe my problem but none of the solutions work.

I have two models property and listings, I want to add a sort link that will sort a list of properties by a field on the listing.

My models look like:

```
class Property < ApplicationRecord
  has_many :listings
end
```

```
class Listing < ApplicationRecord
  belongs_to :property
end
```

Controller does:

```
@q =Property.joins(:listings).select('id', 'full_address', 'price_pence', 'first_listed_date', 'property_type', 'bedrooms', 'listings.agency').ransack(params[:q])
@properties = @q.result
```

So how do I make my sort link work?

`<%= sort_link(@q, :listing_agency, 'Agency') %>`

**Comment by rmaspero** [comment]
My sort link should have been the plural e.g.

`<%= sort_link(@q, :listing_agency, 'Agency') %>`

https://stackoverflow.com/questions/48982277/ransack-sorting-association

**Comment by seanfcarroll** [comment]
Thanks for the clarification @rmaspero
