### ISSUE TITLE
recent commit damages multiple database connections

### ISSUE THREAD

**Issue by mabdelfattah** [activerecord-hackery/ransack#886]
Before this commit, it was working fine, but now I keep getting "Table not exists". I wonder why are we checking for table existence in base connection and not the connection that being used in that model.

https://github.com/activerecord-hackery/ransack/commit/d44575506ccc7cb00e618256707ed53732a07bca#r27784943

CC: @varyonic

**Comment by jsdalton** [comment]
Came here to report this issue. We too are seeing these "Table not exists" errors for models that are using our other database connection.

**Comment by varyonic** [comment]
Looks like a duplicate of #881.

**Comment by seanfcarroll** [comment]
Hi @mabdelfattah sorry it's been causing problems with secondbase. There are sometimes issues with other gems. If you would like to help solve this could you create a small repo with the problem evident ?(even better with a failing test).

**Comment by seanfcarroll** [comment]
Closed due to inactivity.
