### ISSUE TITLE
Ransack memory gem

### ISSUE THREAD

**Issue by richardrails** [activerecord-hackery/ransack#889]
Just let you know that I have made the gem for saving and autoloading search params into session:
https://github.com/richardrails/ransack_memory

**Comment by seanlinsley** [comment]
I don't know if your gem supports this exactly, but I've always wanted ActiveAdmin to be able to save a list of user-defined search queries ✨

**Comment by richardrails** [comment]
It is not necessary to be only ransack, it saves also another params into session, you can configurate it. Should work also for ActiveAdmin gem, it is only before_action method, that you should simply paste into your activeadmin basic controller.

**Comment by seanfcarroll** [comment]
It's a good idea. I've done this by hand but would be nice to have something out of the box.

**Comment by seanfcarroll** [comment]
Added to the Wiki
