### ISSUE TITLE
Problems after upgrade ransack version

### ISSUE THREAD

**Issue by owlbook** [activerecord-hackery/ransack#892]
Hello, I maintain some old application on Rails (4.1.0, gem from branch rails-4.1) and try to update newer version (4.2.10, gem from upstream), but after upgrade I got a strange results of search methods.

In my forms I use checkbox with _null postfix for find all rows or rows with filter.  My data is:

{"id_eq"=>"", "title_cont"=>"", "code_name_cont"=>"", "state_eq"=>"deleted", "created_at_gt"=>"", "created_at_lt"=>"", "order_type_eq"=>"", "service_id_eq"=>"", "service_id_null"=>"0"}

On old version my query was:

"SELECT \"orders\".* FROM \"orders\"  WHERE \"orders\".\"state\" = 'deleted'"

On new version my query is:

"SELECT \"orders\".* FROM \"orders\" WHERE (\"orders\".\"state\" = 'deleted' AND \"orders\".\"service_id\" IS NOT NULL)"

Tell me, please, how can I use filter only if value of field is true or "1"? For now I use delete_if before pass filter_params to search method, but maybe your gem provide simplest solution?

**Comment by seanfcarroll** [comment]
Rails 4.2 is no longer supported. If this issue occurs on a supported version please re-open this issue.
