### ISSUE TITLE
Regression in polymorphic associations in ActiveRecord 5.2

### ISSUE THREAD

**Issue by rzane** [activerecord-hackery/ransack#902]
This issue only affects Active Record 5.2.

In Active Record < 5.2, polymorphic joins will include a condition on the `_type` column.

```sql
LEFT OUTER JOIN "people"
ON "people"."id" = "notes"."notable_id" AND "notes"."notable_type" = 'Person'
```

In Active Record 5.2, the condition will not be included:

```sql
LEFT OUTER JOIN "people"
ON "people"."id" = "notes"."notable_id"
```

---

I created an issue on the polyamorous repo, but I figured more users are likely to see the issue here.

Sorry for the noise, here's the original issue: https://github.com/activerecord-hackery/polyamorous/issues/37

**Comment by seanfcarroll** [comment]
No problem re: noise. Is it possible to create some failing tests on a branch?

**Comment by rzane** [comment]
Sure, I'll see if I can come up with a reproduction case through the Ransack API. I use polyamorous for [baby_squeel](https://github.com/rzane/baby_squeel), and that's where I noticed the issue. Though, I'm pretty sure I was able to reproduce using ransack.

Since baby_squeel depended on polyamorous, and since polyamorous was merged into this repo, baby_squeel now has to depend on ransack. In my attempt to make baby_squeel compatible with Active Record 5.2.1, I think I 

https://github.com/activerecord-hackery/ransack/issues/955

**Comment by dholdren** [comment]
I ran into this issue as well. I'm using ransack 2.1.1 which now includes the polyamorous code

**Comment by gregmolnar** [comment]
@rzane Can you verify that this PR fixes your issue? https://github.com/activerecord-hackery/ransack/pull/1004

**Comment by seanfcarroll** [comment]
Closed due to inactivity.
