### ISSUE TITLE
Arabic translations

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#903]
In order to align the supported translations with ActiveAdmin, we are looking for a community member to provide **ar** translations.

**Comment by seanfcarroll** [comment]
Hey @alnnasr, @camilolunacom or @atefBB  ... would any of you be interested in helping out on this? I can get you started, just message me.

**Comment by atefBB** [comment]
Hey @seanfcarroll!
How can I help you!? 
Pleasure to help.

**Comment by atefBB** [comment]
Hey @seanfcarroll!
How can I help you!?
Pleasure to help.

**Comment by atefBB** [comment]
Hey @seanfcarroll !
How can I help you?

**Comment by seanfcarroll** [comment]
Hi @atefBB , thank you! In this repo there is an [locale file for en](https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/locale/en.yml). Please just copy this file and rename it as **ar.yml** and add the Arabic translations, then do a pull request.

Thank you!

**Comment by atefBB** [comment]
@seanfcarroll Work in progress !!

**Comment by atefBB** [comment]
@seanfcarroll Work done https://github.com/activerecord-hackery/ransack/pull/979 !

**Comment by gregmolnar** [comment]
Thank you @atefBB !

**Comment by atefBB** [comment]
I'm very happy to help! 
I never ever use your tool and I don't know who's selected me to be translated!
But it's fun to help anybody!
I'm who must say THAAAAAAAAAAAANK YOUUUUUUUUU !
