### ISSUE TITLE
Greek translations

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#908]
In order to align the supported translations with ActiveAdmin, we are looking for a community member to provide **el** translations.

**Comment by paraskevasleivadaros** [comment]
Hello, I'm more than happy to help setting something like that up. How to edit/add translations?

**Comment by seanfcarroll** [comment]
Hi @paraskevasleivadaros thank you very much for offering, but this has been done. I just made a [PR](https://github.com/activerecord-hackery/ransack/pull/960) with the translation file. 

How to do this for other languages, or if you see something that needs correction in the given translations ?

1) Fork this repo to your own 
2) Clone the repo locally
3) Make changes to the files (translations are in the lib directory)
4) Run rake to execute tests
5) Push the code back to your own repo
6) Do a pull request back to the main Ransack repo using the button.
