### ISSUE TITLE
paranoia issue with ransack on applying filter

### ISSUE THREAD

**Issue by ali-ssi** [activerecord-hackery/ransack#926]
I am using 
gem 'paranoia', '~> 2.3.1'
gem 'ransack', '~> 1.8', '>= 1.8.7'

and on applying the filter it is not working perfectly can anybody tell me what is the issue or do I need to add extra configurations to make paranoia runnable with ransack?

And without paranoia filters are perfectly working fine.

**Comment by gregmolnar** [comment]
@ali-ssi When you say filters are not working, what do you mean? Is there an error, or do they return the wrong records?

**Comment by ali-ssi** [comment]
@gregmolnar Actually the issue is when I use rasnack with paranoia it returns 0 records although there are records in the DB when I use ransack without paranoia it works fine.

I want to know is ransack works perfectly with paranoia?
If yes then do we need to add any extra configuration for that? I am using the ransack same way with paranoia and without paranoia.

**Comment by matiasgarcia** [comment]
You should provide an example. I use ransack with paranoia and I don't have any issues. Just consider that  paranoia adds a default scope `where deleted_at IS NULL`.

**Comment by gregmolnar** [comment]
@matiasgarcia Thanks for confirming that!
@ali-ssi Could you please create a failing test case based on this template?
https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by ali-ssi** [comment]
Actually, It is working and returning some record but when I apply filters to those records it gives me an empty array.

Here is the query for email filter which i applied with paranoia.

SELECT COUNT(DISTINCT "loan_applications"."id") FROM "loan_applications" LEFT OUTER JOIN "response_sets" ON "response_sets"."loan_application_as_response_set_id" = "loan_applications"."id" AND "response_sets"."deleted_at" IS NULL LEFT OUTER JOIN "users" "users_loan_applications" ON "users_loan_applications"."id" = "loan_applications"."user_id" AND "users_loan_applications"."deleted_at" IS NULL INNER JOIN "users" ON "loan_applications"."user_id" = "users"."id" WHERE "users"."partner_id" = $1 AND ("loan_applications"."deleted_at" IS NOT NULL) AND ("users"."email" IS NOT NULL) AND ("users"."is_pending_account_claim" != $2) AND ("loan_applications"."pipeline_status" IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14) AND "response_sets"."last_name" ILIKE '%test2%' AND "users_loan_applications"."email" ILIKE '%test-100%')  [["partner_id", 1], ["is_pending_account_claim", "t"]]
  LoanApplication Load (2.6ms)  SELECT  "loan_applications".* FROM "loan_applications" LEFT OUTER JOIN "response_sets" ON "response_sets"."loan_application_as_response_set_id" = "loan_applications"."id" AND "response_sets"."deleted_at" IS NULL LEFT OUTER JOIN "users" "users_loan_applications" ON "users_loan_applications"."id" = "loan_applications"."user_id" AND "users_loan_applications"."deleted_at" IS NULL INNER JOIN "users" ON "loan_applications"."user_id" = "users"."id" WHERE "users"."partner_id" = $1 AND ("loan_applications"."deleted_at" IS NOT NULL) AND ("users"."email" IS NOT NULL) AND ("users"."is_pending_account_claim" != $2) AND ("loan_applications"."pipeline_status" IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14) AND "response_sets"."last_name" ILIKE '%test2%' AND "users_loan_applications"."email" ILIKE '%test-100%')  ORDER BY "loan_applications"."id" DESC LIMIT 20 OFFSET 0  [["partner_id", 1], ["is_pending_account_claim", "t"]]

**Comment by ali-ssi** [comment]
@gregmolnar  @matiasgarcia 
Actually, I want to apply filters only deleted and with_deleted objects which are not working for me so do I need to explicitly pass the deleted_at is not NULL to ransack search?

**Comment by gregmolnar** [comment]
@ali-ssi yes, but applying that scope should also work.

**Comment by ali-ssi** [comment]
@gregmolnar can you please quote me an example how will it work? I mean may b an example according to my above statement.

**Comment by gregmolnar** [comment]
@ali-ssi 
```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
  gem "paranoia", "~> 2.2"
  gem "ransack"
end

require "active_record"
require "ransack"
require "paranoia"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.datetime :deleted_at
  end
end

class Post < ActiveRecord::Base
  acts_as_paranoid
end


class BugTest < Minitest::Test
  def test_ransack_with_paranoia
    Post.create!(title: "One")
    deleted_post = Post.create!(title: "two")
    deleted_post.destroy
    @q = Post.ransack(title_cont: "two")
    assert_includes @q.result.with_deleted, deleted_post
  end
end
```
