### ISSUE TITLE
Can not eagerly load the polymorphic association

### ISSUE THREAD

**Issue by ricsrock** [activerecord-hackery/ransack#93]
I'm using ransack and the acts_as_audited gem. I'm creating an admin area where admins can search/filter audit records using ransack. Acts_as_audited creates lots of polymorphic relationships between its audit records and the models it is auditing.

```
create_table :audits, :force => true do |t|
      t.column :auditable_id, :integer
      t.column :auditable_type, :string
      t.column :associated_id, :integer
      t.column :associated_type, :string
      t.column :user_id, :integer
      t.column :user_type, :string
      t.column :username, :string
      t.column :action, :string
      t.column :audited_changes, :text
      t.column :version, :integer, :default => 0
      t.column :comment, :string
      t.column :remote_address, :string
      t.column :created_at, :datetime
    end
```

Here's my search form that should allow users to search for audit records based on the login of the audit model's associated user.

```
<%= search_form_for [:admin,@q], :builder => SimpleForm::FormBuilder do |f| %>
    <%= f.input :user_login_cont, :label => "User Login" %>
    <%= f.submit nil, :class => "btn" %>
<% end %>
```

...but I get this error:

```
ActiveRecord::EagerLoadPolymorphicError in Admin::AuditsController#index

Can not eagerly load the polymorphic association :user
```

In a previous app currently in production using metasearch with acts_as_audited, this setup works fine.

I'm hoping this is a simple fix! Thanks.

**Comment by seanfcarroll** [comment]
Please provide a repo / test with failing code and reopen.
