### ISSUE TITLE
Swedish translations

### ISSUE THREAD

**Issue by pedrofurtado** [activerecord-hackery/ransack#945]
@johanandre Could you help us? You provided swedish translations for my project `timeliness-i18n` ( https://github.com/pedrofurtado/timeliness-i18n ) :+1:

**Comment by johanandre** [comment]
Sure! I’ll take a look at it asap! Probably later this weekend or next week!

**Comment by pedrofurtado** [comment]
@johanandre Thank you so much for your time and contribution! 🍻

**Comment by pedrofurtado** [comment]
@gregmolnar I also sent a post in Rubyflow, to provide some missing translations: http://www.rubyflow.com/p/k5r6rt-help-us-to-provide-translations-for-ransack-gem

**Comment by gregmolnar** [comment]
@pedrofurtado thank you!

**Comment by pedrofurtado** [comment]
🤝 🥇

**Comment by seanfcarroll** [comment]
Still looking for those Swedish translations!

**Comment by seanfcarroll** [comment]
Closing due to a lack of interest.
