### ISSUE TITLE
2.0.1 was released from other repository

### ISSUE THREAD

**Issue by gongo** [activerecord-hackery/ransack#957]
ransack 2.0.1 was released from [gregmolnar/ransack](https://github.com/gregmolnar/ransack/) , not this repository.
Will `gregmolnar/ransack` be the homepage of ransack in future?

**Comment by gregmolnar** [comment]
ups, nope. That's a mistake on my end. All following releases will come from activerecord-hackery.

**Comment by gregmolnar** [comment]
@gongo I pushed the tags to this repo as well now.

**Comment by gongo** [comment]
@gregmolnar Thanks! 🍕
