### ISSUE TITLE
cannot load such file -- polyamorous/activerecord_5.2.2_ruby_2/join_association

### ISSUE THREAD

**Issue by gabrieletassoni** [activerecord-hackery/ransack#987]
rails 5.2.2
ransack 2.1.0

Today I just made a bundle update and rails upgraded to 5.2.2, from there on, I tried to issue a 

`rails g migration AddLinkedinAuthKeys`

And it presented me with that error:

`cannot load such file -- polyamorous/activerecord_5.2.2_ruby_2/join_association`

**Comment by karensg** [comment]
Same issue, looks like it was fixed 5 days ago already. Can we release a new version? :)

**Comment by vcsjones** [comment]
I think this is fixed by https://github.com/activerecord-hackery/ransack/pull/985. We just need to wait for a release to occur.

**Comment by vcsjones** [comment]
If you don't want to rollback rails, you can unblock yourself with:

```ruby
gem 'ransack', github: 'activerecord-hackery/ransack', branch: '8daa87a0389d380f7c9fd7ea9cb5bda634d5dc7d'
```

**Comment by gabrieletassoni** [comment]
Thank you very much, already tested, it works for me.

**Comment by remofritzsche** [comment]
Yep, for me as well. Thanks a bunch @GBH 👍

**Comment by gregmolnar** [comment]
You're welcome guys.

**Comment by parse** [comment]
Thanks @gregmolnar !

**Comment by trojanh** [comment]
>Version 2.1.1 is out and it works with Rails 5.2.2

this version upgrade also helps fix following issues:

```
NameError:
  uninitialized constant Controller
```

and 
```
NameError:
  uninitialized constant Shoulda
# ./spec/spec_helper.rb:201:in `<top (required)>'
```

Adding it here to save someone's time though they are not related to this gem.

Thanks for the fix.
