### ISSUE TITLE
Rails 5.2.2 broken with polyamorous version?

### ISSUE THREAD

**Issue by chevinbrown** [activerecord-hackery/ransack#989]
We're getting build errors for rails 5.2.2. 
```
LoadError: cannot load such file -- polyamorous/activerecord_5.2.2_ruby_2/join_association
```
Looks like polyamorous is broken with rails 5.2.2?

This is a vague bug report--anything I can do to clarify?

**Comment by gregmolnar** [comment]
@chevinbrown Upgrade to 2.1.1 and it will be fine.
