### ISSUE TITLE
Searching in created_at by passing Boolean attribute 

### ISSUE THREAD

**Issue by majedbojan** [activerecord-hackery/ransack#995]
Hello, Hope someone help

I have model and want to pass tag called `new` when the tag is true i want to fetch all the records created_at >= 7.days.ago and if the tag is false need all the records those are created_at <= 7.days.ago

How can i do this using ransack

**Comment by stereobooster** [comment]
Something like this

```rb
scope :new, ->(val) do
  if val 
    where("created_at >= ?",  7.days.ago)
  else
    where("created_at < ?",  7.days.ago)
  end
end

def self.ransackable_scopes(_auth_object = nil)
  [:new]
end
```
