### ISSUE TITLE
Notes on SQL Injection in Ransack forms: I think it's safe

### ISSUE THREAD

**Issue by bdezonia** [activerecord-hackery/ransack#998]
I wanted to prove to myself that Ransack is safe from SQL Injection. I am attaching working notes so that perhaps people will be more confident in Ransack.

I have a Contact model with :id's and :first_names. If I use the advanced mode for searches and select Contact.first_name equals and enter the following string into the form field:

zuck%7F' order by `contacts`.`id` ASC; drop database reggie_rails_development; select `contacts`.* from `contacts` where `contacts`.`first_name` = %7F'boo

The generated SQL is:

`
SELECT DISTINCT `contacts`.* FROM `contacts` WHERE `contacts`.`first_name` = 'zuck%7F\' order by `contacts`.`id` ASC; drop database reggie_rails_development; select `contacts`.* from `contacts` where `contacts`.`first_name` = %7F\'boo' ORDER BY `contacts`.`id` ASC
`

The %7F's were in place so that the URL decoder might strip the next char from the string. As far as I can tell Ransack always escape-quotes single quote char and the URL decoding does not execute the %7F's as delete char actions.

I think Ransack is safe from SQL Injection in the forms. I thought this note might be useful for people to know.

(Note that this issue form does some code prettification that does not represent the exact text strings very well. I have edited as much as possible for the examples to look clear.)

**Comment by gregmolnar** [comment]
You can just try sqlmap to make sure this, but there shouldn't be any SQL injection vulnerabilities in the code as for today.
